// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: db/list_filters.proto
// Protobuf Java Version: 4.32.0

package cloud.stately.db;

@com.google.protobuf.Generated
public interface CelExpressionOrBuilder extends
    // @@protoc_insertion_point(interface_extends:stately.db.CelExpression)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * item_type is the itemType to evaluate the expression against.
   * </pre>
   *
   * <code>string item_type = 1 [json_name = "itemType"];</code>
   * @return The itemType.
   */
  java.lang.String getItemType();
  /**
   * <pre>
   * item_type is the itemType to evaluate the expression against.
   * </pre>
   *
   * <code>string item_type = 1 [json_name = "itemType"];</code>
   * @return The bytes for itemType.
   */
  com.google.protobuf.ByteString
      getItemTypeBytes();

  /**
   * <pre>
   * expression is the CEL expression to evaluate.
   * If the expression evaluates to true, the item is included in the results,
   * otherwise it is excluded.
   *
   * In the context of the CEL expression, 'this' refers to the item being evaluated.
   * For example, the expression is "this.foo == 'bar'" means that the item
   * must have a property 'foo' with the value 'bar' to be included in the results.
   * </pre>
   *
   * <code>string expression = 2 [json_name = "expression"];</code>
   * @return The expression.
   */
  java.lang.String getExpression();
  /**
   * <pre>
   * expression is the CEL expression to evaluate.
   * If the expression evaluates to true, the item is included in the results,
   * otherwise it is excluded.
   *
   * In the context of the CEL expression, 'this' refers to the item being evaluated.
   * For example, the expression is "this.foo == 'bar'" means that the item
   * must have a property 'foo' with the value 'bar' to be included in the results.
   * </pre>
   *
   * <code>string expression = 2 [json_name = "expression"];</code>
   * @return The bytes for expression.
   */
  com.google.protobuf.ByteString
      getExpressionBytes();
}
