// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: db/delete.proto
// Protobuf Java Version: 4.32.0

package cloud.stately.db;

@com.google.protobuf.Generated
public interface DeleteItemOrBuilder extends
    // @@protoc_insertion_point(interface_extends:stately.db.DeleteItem)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * key_path is the full path to the item. See Item#key_path for more details.
   * </pre>
   *
   * <code>string key_path = 1 [json_name = "keyPath"];</code>
   * @return The keyPath.
   */
  java.lang.String getKeyPath();
  /**
   * <pre>
   * key_path is the full path to the item. See Item#key_path for more details.
   * </pre>
   *
   * <code>string key_path = 1 [json_name = "keyPath"];</code>
   * @return The bytes for keyPath.
   */
  com.google.protobuf.ByteString
      getKeyPathBytes();
}
