// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: db/delete.proto
// Protobuf Java Version: 4.32.0

package cloud.stately.db;

/**
 * Protobuf type {@code stately.db.DeleteResult}
 */
@com.google.protobuf.Generated
public final class DeleteResult extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:stately.db.DeleteResult)
    DeleteResultOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 32,
      /* patch= */ 0,
      /* suffix= */ "",
      DeleteResult.class.getName());
  }
  // Use DeleteResult.newBuilder() to construct.
  private DeleteResult(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private DeleteResult() {
    keyPath_ = "";
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return cloud.stately.db.DeleteProto.internal_static_stately_db_DeleteResult_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return cloud.stately.db.DeleteProto.internal_static_stately_db_DeleteResult_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            cloud.stately.db.DeleteResult.class, cloud.stately.db.DeleteResult.Builder.class);
  }

  public static final int KEY_PATH_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object keyPath_ = "";
  /**
   * <pre>
   * The key_path of the item that was deleted.
   * </pre>
   *
   * <code>string key_path = 1 [json_name = "keyPath"];</code>
   * @return The keyPath.
   */
  @java.lang.Override
  public java.lang.String getKeyPath() {
    java.lang.Object ref = keyPath_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      keyPath_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * The key_path of the item that was deleted.
   * </pre>
   *
   * <code>string key_path = 1 [json_name = "keyPath"];</code>
   * @return The bytes for keyPath.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getKeyPathBytes() {
    java.lang.Object ref = keyPath_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      keyPath_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(keyPath_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 1, keyPath_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(keyPath_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(1, keyPath_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof cloud.stately.db.DeleteResult)) {
      return super.equals(obj);
    }
    cloud.stately.db.DeleteResult other = (cloud.stately.db.DeleteResult) obj;

    if (!getKeyPath()
        .equals(other.getKeyPath())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + KEY_PATH_FIELD_NUMBER;
    hash = (53 * hash) + getKeyPath().hashCode();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static cloud.stately.db.DeleteResult parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static cloud.stately.db.DeleteResult parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static cloud.stately.db.DeleteResult parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static cloud.stately.db.DeleteResult parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static cloud.stately.db.DeleteResult parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static cloud.stately.db.DeleteResult parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static cloud.stately.db.DeleteResult parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static cloud.stately.db.DeleteResult parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static cloud.stately.db.DeleteResult parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static cloud.stately.db.DeleteResult parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static cloud.stately.db.DeleteResult parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static cloud.stately.db.DeleteResult parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(cloud.stately.db.DeleteResult prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code stately.db.DeleteResult}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:stately.db.DeleteResult)
      cloud.stately.db.DeleteResultOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return cloud.stately.db.DeleteProto.internal_static_stately_db_DeleteResult_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return cloud.stately.db.DeleteProto.internal_static_stately_db_DeleteResult_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              cloud.stately.db.DeleteResult.class, cloud.stately.db.DeleteResult.Builder.class);
    }

    // Construct using cloud.stately.db.DeleteResult.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      keyPath_ = "";
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return cloud.stately.db.DeleteProto.internal_static_stately_db_DeleteResult_descriptor;
    }

    @java.lang.Override
    public cloud.stately.db.DeleteResult getDefaultInstanceForType() {
      return cloud.stately.db.DeleteResult.getDefaultInstance();
    }

    @java.lang.Override
    public cloud.stately.db.DeleteResult build() {
      cloud.stately.db.DeleteResult result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public cloud.stately.db.DeleteResult buildPartial() {
      cloud.stately.db.DeleteResult result = new cloud.stately.db.DeleteResult(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(cloud.stately.db.DeleteResult result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.keyPath_ = keyPath_;
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof cloud.stately.db.DeleteResult) {
        return mergeFrom((cloud.stately.db.DeleteResult)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(cloud.stately.db.DeleteResult other) {
      if (other == cloud.stately.db.DeleteResult.getDefaultInstance()) return this;
      if (!other.getKeyPath().isEmpty()) {
        keyPath_ = other.keyPath_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              keyPath_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object keyPath_ = "";
    /**
     * <pre>
     * The key_path of the item that was deleted.
     * </pre>
     *
     * <code>string key_path = 1 [json_name = "keyPath"];</code>
     * @return The keyPath.
     */
    public java.lang.String getKeyPath() {
      java.lang.Object ref = keyPath_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        keyPath_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * The key_path of the item that was deleted.
     * </pre>
     *
     * <code>string key_path = 1 [json_name = "keyPath"];</code>
     * @return The bytes for keyPath.
     */
    public com.google.protobuf.ByteString
        getKeyPathBytes() {
      java.lang.Object ref = keyPath_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        keyPath_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * The key_path of the item that was deleted.
     * </pre>
     *
     * <code>string key_path = 1 [json_name = "keyPath"];</code>
     * @param value The keyPath to set.
     * @return This builder for chaining.
     */
    public Builder setKeyPath(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      keyPath_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The key_path of the item that was deleted.
     * </pre>
     *
     * <code>string key_path = 1 [json_name = "keyPath"];</code>
     * @return This builder for chaining.
     */
    public Builder clearKeyPath() {
      keyPath_ = getDefaultInstance().getKeyPath();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The key_path of the item that was deleted.
     * </pre>
     *
     * <code>string key_path = 1 [json_name = "keyPath"];</code>
     * @param value The bytes for keyPath to set.
     * @return This builder for chaining.
     */
    public Builder setKeyPathBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      keyPath_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:stately.db.DeleteResult)
  }

  // @@protoc_insertion_point(class_scope:stately.db.DeleteResult)
  private static final cloud.stately.db.DeleteResult DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new cloud.stately.db.DeleteResult();
  }

  public static cloud.stately.db.DeleteResult getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<DeleteResult>
      PARSER = new com.google.protobuf.AbstractParser<DeleteResult>() {
    @java.lang.Override
    public DeleteResult parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<DeleteResult> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<DeleteResult> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public cloud.stately.db.DeleteResult getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

