// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: db/transaction.proto
// Protobuf Java Version: 4.32.0

package cloud.stately.db;

@com.google.protobuf.Generated
public interface GeneratedIDOrBuilder extends
    // @@protoc_insertion_point(interface_extends:stately.db.GeneratedID)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>uint64 uint = 1 [json_name = "uint"];</code>
   * @return Whether the uint field is set.
   */
  boolean hasUint();
  /**
   * <code>uint64 uint = 1 [json_name = "uint"];</code>
   * @return The uint.
   */
  long getUint();

  /**
   * <code>bytes bytes = 2 [json_name = "bytes"];</code>
   * @return Whether the bytes field is set.
   */
  boolean hasBytes();
  /**
   * <code>bytes bytes = 2 [json_name = "bytes"];</code>
   * @return The bytes.
   */
  com.google.protobuf.ByteString getBytes();

  cloud.stately.db.GeneratedID.ValueCase getValueCase();
}
