// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: db/item.proto
// Protobuf Java Version: 4.32.0

package cloud.stately.db;

@com.google.protobuf.Generated
public final class ItemProto {
  private ItemProto() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 32,
      /* patch= */ 0,
      /* suffix= */ "",
      ItemProto.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_stately_db_Item_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_stately_db_Item_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rdb/item.proto\022\nstately.db\032\034google/prot" +
      "obuf/struct.proto\"u\n\004Item\022\033\n\titem_type\030\001" +
      " \001(\tR\010itemType\022\026\n\005proto\030\002 \001(\014H\000R\005proto\022-" +
      "\n\004json\030\003 \001(\0132\027.google.protobuf.StructH\000R" +
      "\004jsonB\t\n\007payloadBf\n\020cloud.stately.dbB\tIt" +
      "emProtoP\001\242\002\003SDX\252\002\nStately.Db\312\002\nStately\\D" +
      "b\342\002\026Stately\\Db\\GPBMetadata\352\002\013Stately::Db" +
      "b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.StructProto.getDescriptor(),
        });
    internal_static_stately_db_Item_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_stately_db_Item_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_stately_db_Item_descriptor,
        new java.lang.String[] { "ItemType", "Proto", "Json", "Payload", });
    descriptor.resolveAllFeaturesImmutable();
    com.google.protobuf.StructProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
