// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: db/item.proto
// Protobuf Java Version: 4.32.0

package cloud.stately.db;

@com.google.protobuf.Generated
public interface ItemOrBuilder extends
    // @@protoc_insertion_point(interface_extends:stately.db.Item)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * item_type is the schema type of the item. It must correspond to one of the
   * schema's `itemType` declarations.
   * </pre>
   *
   * <code>string item_type = 1 [json_name = "itemType"];</code>
   * @return The itemType.
   */
  java.lang.String getItemType();
  /**
   * <pre>
   * item_type is the schema type of the item. It must correspond to one of the
   * schema's `itemType` declarations.
   * </pre>
   *
   * <code>string item_type = 1 [json_name = "itemType"];</code>
   * @return The bytes for itemType.
   */
  com.google.protobuf.ByteString
      getItemTypeBytes();

  /**
   * <pre>
   * proto is a serialized binary proto message, following the schema for this
   * item type. Clients will need to map the item_type to a protobuf message
   * descriptor to be able to unmarshal this.
   * </pre>
   *
   * <code>bytes proto = 2 [json_name = "proto"];</code>
   * @return Whether the proto field is set.
   */
  boolean hasProto();
  /**
   * <pre>
   * proto is a serialized binary proto message, following the schema for this
   * item type. Clients will need to map the item_type to a protobuf message
   * descriptor to be able to unmarshal this.
   * </pre>
   *
   * <code>bytes proto = 2 [json_name = "proto"];</code>
   * @return The proto.
   */
  com.google.protobuf.ByteString getProto();

  /**
   * <pre>
   * json is the JSON representation of the item's payload, as an alternative
   * to the binary proto representation. It exists only to support clients
   * that speak the Connect-JSON protocol. Using google.protobuf.Struct means
   * the JSON is embedded inline instead of being a string, and most languages
   * should have special support for it.
   * </pre>
   *
   * <code>.google.protobuf.Struct json = 3 [json_name = "json"];</code>
   * @return Whether the json field is set.
   */
  boolean hasJson();
  /**
   * <pre>
   * json is the JSON representation of the item's payload, as an alternative
   * to the binary proto representation. It exists only to support clients
   * that speak the Connect-JSON protocol. Using google.protobuf.Struct means
   * the JSON is embedded inline instead of being a string, and most languages
   * should have special support for it.
   * </pre>
   *
   * <code>.google.protobuf.Struct json = 3 [json_name = "json"];</code>
   * @return The json.
   */
  com.google.protobuf.Struct getJson();
  /**
   * <pre>
   * json is the JSON representation of the item's payload, as an alternative
   * to the binary proto representation. It exists only to support clients
   * that speak the Connect-JSON protocol. Using google.protobuf.Struct means
   * the JSON is embedded inline instead of being a string, and most languages
   * should have special support for it.
   * </pre>
   *
   * <code>.google.protobuf.Struct json = 3 [json_name = "json"];</code>
   */
  com.google.protobuf.StructOrBuilder getJsonOrBuilder();

  cloud.stately.db.Item.PayloadCase getPayloadCase();
}
