// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: db/list_token.proto
// Protobuf Java Version: 4.32.0

package cloud.stately.db;

/**
 * <pre>
 * ListToken is an opaque token that can be used to continue (paginate) or sync
 * results from a previous List operation.
 * </pre>
 *
 * Protobuf type {@code stately.db.ListToken}
 */
@com.google.protobuf.Generated
public final class ListToken extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:stately.db.ListToken)
    ListTokenOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 32,
      /* patch= */ 0,
      /* suffix= */ "",
      ListToken.class.getName());
  }
  // Use ListToken.newBuilder() to construct.
  private ListToken(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private ListToken() {
    tokenData_ = com.google.protobuf.ByteString.EMPTY;
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return cloud.stately.db.ListTokenProto.internal_static_stately_db_ListToken_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return cloud.stately.db.ListTokenProto.internal_static_stately_db_ListToken_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            cloud.stately.db.ListToken.class, cloud.stately.db.ListToken.Builder.class);
  }

  public static final int TOKEN_DATA_FIELD_NUMBER = 1;
  private com.google.protobuf.ByteString tokenData_ = com.google.protobuf.ByteString.EMPTY;
  /**
   * <pre>
   * token_data will always be returned, and can be used to expand the result
   * set via ContinueList (if can_continue is true), or to get changed items
   * within the result set via SyncList (if can_sync is true). The token_data
   * itself is opaque and cannot be parsed or modified by clients.
   * </pre>
   *
   * <code>bytes token_data = 1 [json_name = "tokenData"];</code>
   * @return The tokenData.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString getTokenData() {
    return tokenData_;
  }

  public static final int CAN_CONTINUE_FIELD_NUMBER = 2;
  private boolean canContinue_ = false;
  /**
   * <pre>
   * can_continue indicates that there are more results available by expanding
   * the pagination window by calling ContinueList with this token.
   * </pre>
   *
   * <code>bool can_continue = 2 [json_name = "canContinue"];</code>
   * @return The canContinue.
   */
  @java.lang.Override
  public boolean getCanContinue() {
    return canContinue_;
  }

  public static final int CAN_SYNC_FIELD_NUMBER = 3;
  private boolean canSync_ = false;
  /**
   * <pre>
   * can_sync indicates that you could call SyncList with this token later to
   * get updated items. This is determined by the type of store you're listing
   * from.
   * </pre>
   *
   * <code>bool can_sync = 3 [json_name = "canSync"];</code>
   * @return The canSync.
   */
  @java.lang.Override
  public boolean getCanSync() {
    return canSync_;
  }

  public static final int SCHEMA_VERSION_ID_FIELD_NUMBER = 4;
  private int schemaVersionId_ = 0;
  /**
   * <pre>
   * schema_version_id represents the version of the schema that was used to
   * generate token_data. For ContinueList calls, you must ensure the client's
   * schema version and this field are the same. A mismatch between the two
   * will result in a SchemaVersionMismatch error. For SyncList calls, you
   * only need to ensure you handle Reset events correctly by clearing your
   * local state and consuming a new list of items as Stately will handle
   * re-send items in the correct version along with a new token at the end.
   * </pre>
   *
   * <code>uint32 schema_version_id = 4 [json_name = "schemaVersionId"];</code>
   * @return The schemaVersionId.
   */
  @java.lang.Override
  public int getSchemaVersionId() {
    return schemaVersionId_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!tokenData_.isEmpty()) {
      output.writeBytes(1, tokenData_);
    }
    if (canContinue_ != false) {
      output.writeBool(2, canContinue_);
    }
    if (canSync_ != false) {
      output.writeBool(3, canSync_);
    }
    if (schemaVersionId_ != 0) {
      output.writeUInt32(4, schemaVersionId_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!tokenData_.isEmpty()) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(1, tokenData_);
    }
    if (canContinue_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(2, canContinue_);
    }
    if (canSync_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(3, canSync_);
    }
    if (schemaVersionId_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt32Size(4, schemaVersionId_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof cloud.stately.db.ListToken)) {
      return super.equals(obj);
    }
    cloud.stately.db.ListToken other = (cloud.stately.db.ListToken) obj;

    if (!getTokenData()
        .equals(other.getTokenData())) return false;
    if (getCanContinue()
        != other.getCanContinue()) return false;
    if (getCanSync()
        != other.getCanSync()) return false;
    if (getSchemaVersionId()
        != other.getSchemaVersionId()) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + TOKEN_DATA_FIELD_NUMBER;
    hash = (53 * hash) + getTokenData().hashCode();
    hash = (37 * hash) + CAN_CONTINUE_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getCanContinue());
    hash = (37 * hash) + CAN_SYNC_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getCanSync());
    hash = (37 * hash) + SCHEMA_VERSION_ID_FIELD_NUMBER;
    hash = (53 * hash) + getSchemaVersionId();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static cloud.stately.db.ListToken parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static cloud.stately.db.ListToken parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static cloud.stately.db.ListToken parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static cloud.stately.db.ListToken parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static cloud.stately.db.ListToken parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static cloud.stately.db.ListToken parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static cloud.stately.db.ListToken parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static cloud.stately.db.ListToken parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static cloud.stately.db.ListToken parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static cloud.stately.db.ListToken parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static cloud.stately.db.ListToken parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static cloud.stately.db.ListToken parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(cloud.stately.db.ListToken prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * ListToken is an opaque token that can be used to continue (paginate) or sync
   * results from a previous List operation.
   * </pre>
   *
   * Protobuf type {@code stately.db.ListToken}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:stately.db.ListToken)
      cloud.stately.db.ListTokenOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return cloud.stately.db.ListTokenProto.internal_static_stately_db_ListToken_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return cloud.stately.db.ListTokenProto.internal_static_stately_db_ListToken_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              cloud.stately.db.ListToken.class, cloud.stately.db.ListToken.Builder.class);
    }

    // Construct using cloud.stately.db.ListToken.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      tokenData_ = com.google.protobuf.ByteString.EMPTY;
      canContinue_ = false;
      canSync_ = false;
      schemaVersionId_ = 0;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return cloud.stately.db.ListTokenProto.internal_static_stately_db_ListToken_descriptor;
    }

    @java.lang.Override
    public cloud.stately.db.ListToken getDefaultInstanceForType() {
      return cloud.stately.db.ListToken.getDefaultInstance();
    }

    @java.lang.Override
    public cloud.stately.db.ListToken build() {
      cloud.stately.db.ListToken result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public cloud.stately.db.ListToken buildPartial() {
      cloud.stately.db.ListToken result = new cloud.stately.db.ListToken(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(cloud.stately.db.ListToken result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.tokenData_ = tokenData_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.canContinue_ = canContinue_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.canSync_ = canSync_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.schemaVersionId_ = schemaVersionId_;
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof cloud.stately.db.ListToken) {
        return mergeFrom((cloud.stately.db.ListToken)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(cloud.stately.db.ListToken other) {
      if (other == cloud.stately.db.ListToken.getDefaultInstance()) return this;
      if (!other.getTokenData().isEmpty()) {
        setTokenData(other.getTokenData());
      }
      if (other.getCanContinue() != false) {
        setCanContinue(other.getCanContinue());
      }
      if (other.getCanSync() != false) {
        setCanSync(other.getCanSync());
      }
      if (other.getSchemaVersionId() != 0) {
        setSchemaVersionId(other.getSchemaVersionId());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              tokenData_ = input.readBytes();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 16: {
              canContinue_ = input.readBool();
              bitField0_ |= 0x00000002;
              break;
            } // case 16
            case 24: {
              canSync_ = input.readBool();
              bitField0_ |= 0x00000004;
              break;
            } // case 24
            case 32: {
              schemaVersionId_ = input.readUInt32();
              bitField0_ |= 0x00000008;
              break;
            } // case 32
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private com.google.protobuf.ByteString tokenData_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <pre>
     * token_data will always be returned, and can be used to expand the result
     * set via ContinueList (if can_continue is true), or to get changed items
     * within the result set via SyncList (if can_sync is true). The token_data
     * itself is opaque and cannot be parsed or modified by clients.
     * </pre>
     *
     * <code>bytes token_data = 1 [json_name = "tokenData"];</code>
     * @return The tokenData.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getTokenData() {
      return tokenData_;
    }
    /**
     * <pre>
     * token_data will always be returned, and can be used to expand the result
     * set via ContinueList (if can_continue is true), or to get changed items
     * within the result set via SyncList (if can_sync is true). The token_data
     * itself is opaque and cannot be parsed or modified by clients.
     * </pre>
     *
     * <code>bytes token_data = 1 [json_name = "tokenData"];</code>
     * @param value The tokenData to set.
     * @return This builder for chaining.
     */
    public Builder setTokenData(com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      tokenData_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * token_data will always be returned, and can be used to expand the result
     * set via ContinueList (if can_continue is true), or to get changed items
     * within the result set via SyncList (if can_sync is true). The token_data
     * itself is opaque and cannot be parsed or modified by clients.
     * </pre>
     *
     * <code>bytes token_data = 1 [json_name = "tokenData"];</code>
     * @return This builder for chaining.
     */
    public Builder clearTokenData() {
      bitField0_ = (bitField0_ & ~0x00000001);
      tokenData_ = getDefaultInstance().getTokenData();
      onChanged();
      return this;
    }

    private boolean canContinue_ ;
    /**
     * <pre>
     * can_continue indicates that there are more results available by expanding
     * the pagination window by calling ContinueList with this token.
     * </pre>
     *
     * <code>bool can_continue = 2 [json_name = "canContinue"];</code>
     * @return The canContinue.
     */
    @java.lang.Override
    public boolean getCanContinue() {
      return canContinue_;
    }
    /**
     * <pre>
     * can_continue indicates that there are more results available by expanding
     * the pagination window by calling ContinueList with this token.
     * </pre>
     *
     * <code>bool can_continue = 2 [json_name = "canContinue"];</code>
     * @param value The canContinue to set.
     * @return This builder for chaining.
     */
    public Builder setCanContinue(boolean value) {

      canContinue_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * can_continue indicates that there are more results available by expanding
     * the pagination window by calling ContinueList with this token.
     * </pre>
     *
     * <code>bool can_continue = 2 [json_name = "canContinue"];</code>
     * @return This builder for chaining.
     */
    public Builder clearCanContinue() {
      bitField0_ = (bitField0_ & ~0x00000002);
      canContinue_ = false;
      onChanged();
      return this;
    }

    private boolean canSync_ ;
    /**
     * <pre>
     * can_sync indicates that you could call SyncList with this token later to
     * get updated items. This is determined by the type of store you're listing
     * from.
     * </pre>
     *
     * <code>bool can_sync = 3 [json_name = "canSync"];</code>
     * @return The canSync.
     */
    @java.lang.Override
    public boolean getCanSync() {
      return canSync_;
    }
    /**
     * <pre>
     * can_sync indicates that you could call SyncList with this token later to
     * get updated items. This is determined by the type of store you're listing
     * from.
     * </pre>
     *
     * <code>bool can_sync = 3 [json_name = "canSync"];</code>
     * @param value The canSync to set.
     * @return This builder for chaining.
     */
    public Builder setCanSync(boolean value) {

      canSync_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * can_sync indicates that you could call SyncList with this token later to
     * get updated items. This is determined by the type of store you're listing
     * from.
     * </pre>
     *
     * <code>bool can_sync = 3 [json_name = "canSync"];</code>
     * @return This builder for chaining.
     */
    public Builder clearCanSync() {
      bitField0_ = (bitField0_ & ~0x00000004);
      canSync_ = false;
      onChanged();
      return this;
    }

    private int schemaVersionId_ ;
    /**
     * <pre>
     * schema_version_id represents the version of the schema that was used to
     * generate token_data. For ContinueList calls, you must ensure the client's
     * schema version and this field are the same. A mismatch between the two
     * will result in a SchemaVersionMismatch error. For SyncList calls, you
     * only need to ensure you handle Reset events correctly by clearing your
     * local state and consuming a new list of items as Stately will handle
     * re-send items in the correct version along with a new token at the end.
     * </pre>
     *
     * <code>uint32 schema_version_id = 4 [json_name = "schemaVersionId"];</code>
     * @return The schemaVersionId.
     */
    @java.lang.Override
    public int getSchemaVersionId() {
      return schemaVersionId_;
    }
    /**
     * <pre>
     * schema_version_id represents the version of the schema that was used to
     * generate token_data. For ContinueList calls, you must ensure the client's
     * schema version and this field are the same. A mismatch between the two
     * will result in a SchemaVersionMismatch error. For SyncList calls, you
     * only need to ensure you handle Reset events correctly by clearing your
     * local state and consuming a new list of items as Stately will handle
     * re-send items in the correct version along with a new token at the end.
     * </pre>
     *
     * <code>uint32 schema_version_id = 4 [json_name = "schemaVersionId"];</code>
     * @param value The schemaVersionId to set.
     * @return This builder for chaining.
     */
    public Builder setSchemaVersionId(int value) {

      schemaVersionId_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * schema_version_id represents the version of the schema that was used to
     * generate token_data. For ContinueList calls, you must ensure the client's
     * schema version and this field are the same. A mismatch between the two
     * will result in a SchemaVersionMismatch error. For SyncList calls, you
     * only need to ensure you handle Reset events correctly by clearing your
     * local state and consuming a new list of items as Stately will handle
     * re-send items in the correct version along with a new token at the end.
     * </pre>
     *
     * <code>uint32 schema_version_id = 4 [json_name = "schemaVersionId"];</code>
     * @return This builder for chaining.
     */
    public Builder clearSchemaVersionId() {
      bitField0_ = (bitField0_ & ~0x00000008);
      schemaVersionId_ = 0;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:stately.db.ListToken)
  }

  // @@protoc_insertion_point(class_scope:stately.db.ListToken)
  private static final cloud.stately.db.ListToken DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new cloud.stately.db.ListToken();
  }

  public static cloud.stately.db.ListToken getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ListToken>
      PARSER = new com.google.protobuf.AbstractParser<ListToken>() {
    @java.lang.Override
    public ListToken parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<ListToken> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ListToken> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public cloud.stately.db.ListToken getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

