// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: db/list.proto
// Protobuf Java Version: 4.32.0

package cloud.stately.db;

@com.google.protobuf.Generated
public interface ListPartialResultOrBuilder extends
    // @@protoc_insertion_point(interface_extends:stately.db.ListPartialResult)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * results is a list that contains one entry for each Item that was found.
   * </pre>
   *
   * <code>repeated .stately.db.Item items = 1 [json_name = "items"];</code>
   */
  java.util.List<cloud.stately.db.Item> 
      getItemsList();
  /**
   * <pre>
   * results is a list that contains one entry for each Item that was found.
   * </pre>
   *
   * <code>repeated .stately.db.Item items = 1 [json_name = "items"];</code>
   */
  cloud.stately.db.Item getItems(int index);
  /**
   * <pre>
   * results is a list that contains one entry for each Item that was found.
   * </pre>
   *
   * <code>repeated .stately.db.Item items = 1 [json_name = "items"];</code>
   */
  int getItemsCount();
  /**
   * <pre>
   * results is a list that contains one entry for each Item that was found.
   * </pre>
   *
   * <code>repeated .stately.db.Item items = 1 [json_name = "items"];</code>
   */
  java.util.List<? extends cloud.stately.db.ItemOrBuilder> 
      getItemsOrBuilderList();
  /**
   * <pre>
   * results is a list that contains one entry for each Item that was found.
   * </pre>
   *
   * <code>repeated .stately.db.Item items = 1 [json_name = "items"];</code>
   */
  cloud.stately.db.ItemOrBuilder getItemsOrBuilder(
      int index);
}
