// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: db/list_token.proto
// Protobuf Java Version: 4.32.0

package cloud.stately.db;

@com.google.protobuf.Generated
public interface ListTokenOrBuilder extends
    // @@protoc_insertion_point(interface_extends:stately.db.ListToken)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * token_data will always be returned, and can be used to expand the result
   * set via ContinueList (if can_continue is true), or to get changed items
   * within the result set via SyncList (if can_sync is true). The token_data
   * itself is opaque and cannot be parsed or modified by clients.
   * </pre>
   *
   * <code>bytes token_data = 1 [json_name = "tokenData"];</code>
   * @return The tokenData.
   */
  com.google.protobuf.ByteString getTokenData();

  /**
   * <pre>
   * can_continue indicates that there are more results available by expanding
   * the pagination window by calling ContinueList with this token.
   * </pre>
   *
   * <code>bool can_continue = 2 [json_name = "canContinue"];</code>
   * @return The canContinue.
   */
  boolean getCanContinue();

  /**
   * <pre>
   * can_sync indicates that you could call SyncList with this token later to
   * get updated items. This is determined by the type of store you're listing
   * from.
   * </pre>
   *
   * <code>bool can_sync = 3 [json_name = "canSync"];</code>
   * @return The canSync.
   */
  boolean getCanSync();

  /**
   * <pre>
   * schema_version_id represents the version of the schema that was used to
   * generate token_data. For ContinueList calls, you must ensure the client's
   * schema version and this field are the same. A mismatch between the two
   * will result in a SchemaVersionMismatch error. For SyncList calls, you
   * only need to ensure you handle Reset events correctly by clearing your
   * local state and consuming a new list of items as Stately will handle
   * re-send items in the correct version along with a new token at the end.
   * </pre>
   *
   * <code>uint32 schema_version_id = 4 [json_name = "schemaVersionId"];</code>
   * @return The schemaVersionId.
   */
  int getSchemaVersionId();
}
