// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: db/list.proto
// Protobuf Java Version: 4.32.0

package cloud.stately.db;

/**
 * Protobuf type {@code stately.db.ListPartialResult}
 */
@com.google.protobuf.Generated
public final class ListPartialResult extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:stately.db.ListPartialResult)
    ListPartialResultOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 32,
      /* patch= */ 0,
      /* suffix= */ "",
      ListPartialResult.class.getName());
  }
  // Use ListPartialResult.newBuilder() to construct.
  private ListPartialResult(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private ListPartialResult() {
    items_ = java.util.Collections.emptyList();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return cloud.stately.db.ListProto.internal_static_stately_db_ListPartialResult_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return cloud.stately.db.ListProto.internal_static_stately_db_ListPartialResult_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            cloud.stately.db.ListPartialResult.class, cloud.stately.db.ListPartialResult.Builder.class);
  }

  public static final int ITEMS_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private java.util.List<cloud.stately.db.Item> items_;
  /**
   * <pre>
   * results is a list that contains one entry for each Item that was found.
   * </pre>
   *
   * <code>repeated .stately.db.Item items = 1 [json_name = "items"];</code>
   */
  @java.lang.Override
  public java.util.List<cloud.stately.db.Item> getItemsList() {
    return items_;
  }
  /**
   * <pre>
   * results is a list that contains one entry for each Item that was found.
   * </pre>
   *
   * <code>repeated .stately.db.Item items = 1 [json_name = "items"];</code>
   */
  @java.lang.Override
  public java.util.List<? extends cloud.stately.db.ItemOrBuilder> 
      getItemsOrBuilderList() {
    return items_;
  }
  /**
   * <pre>
   * results is a list that contains one entry for each Item that was found.
   * </pre>
   *
   * <code>repeated .stately.db.Item items = 1 [json_name = "items"];</code>
   */
  @java.lang.Override
  public int getItemsCount() {
    return items_.size();
  }
  /**
   * <pre>
   * results is a list that contains one entry for each Item that was found.
   * </pre>
   *
   * <code>repeated .stately.db.Item items = 1 [json_name = "items"];</code>
   */
  @java.lang.Override
  public cloud.stately.db.Item getItems(int index) {
    return items_.get(index);
  }
  /**
   * <pre>
   * results is a list that contains one entry for each Item that was found.
   * </pre>
   *
   * <code>repeated .stately.db.Item items = 1 [json_name = "items"];</code>
   */
  @java.lang.Override
  public cloud.stately.db.ItemOrBuilder getItemsOrBuilder(
      int index) {
    return items_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < items_.size(); i++) {
      output.writeMessage(1, items_.get(i));
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < items_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, items_.get(i));
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof cloud.stately.db.ListPartialResult)) {
      return super.equals(obj);
    }
    cloud.stately.db.ListPartialResult other = (cloud.stately.db.ListPartialResult) obj;

    if (!getItemsList()
        .equals(other.getItemsList())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getItemsCount() > 0) {
      hash = (37 * hash) + ITEMS_FIELD_NUMBER;
      hash = (53 * hash) + getItemsList().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static cloud.stately.db.ListPartialResult parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static cloud.stately.db.ListPartialResult parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static cloud.stately.db.ListPartialResult parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static cloud.stately.db.ListPartialResult parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static cloud.stately.db.ListPartialResult parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static cloud.stately.db.ListPartialResult parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static cloud.stately.db.ListPartialResult parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static cloud.stately.db.ListPartialResult parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static cloud.stately.db.ListPartialResult parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static cloud.stately.db.ListPartialResult parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static cloud.stately.db.ListPartialResult parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static cloud.stately.db.ListPartialResult parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(cloud.stately.db.ListPartialResult prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code stately.db.ListPartialResult}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:stately.db.ListPartialResult)
      cloud.stately.db.ListPartialResultOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return cloud.stately.db.ListProto.internal_static_stately_db_ListPartialResult_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return cloud.stately.db.ListProto.internal_static_stately_db_ListPartialResult_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              cloud.stately.db.ListPartialResult.class, cloud.stately.db.ListPartialResult.Builder.class);
    }

    // Construct using cloud.stately.db.ListPartialResult.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      if (itemsBuilder_ == null) {
        items_ = java.util.Collections.emptyList();
      } else {
        items_ = null;
        itemsBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000001);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return cloud.stately.db.ListProto.internal_static_stately_db_ListPartialResult_descriptor;
    }

    @java.lang.Override
    public cloud.stately.db.ListPartialResult getDefaultInstanceForType() {
      return cloud.stately.db.ListPartialResult.getDefaultInstance();
    }

    @java.lang.Override
    public cloud.stately.db.ListPartialResult build() {
      cloud.stately.db.ListPartialResult result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public cloud.stately.db.ListPartialResult buildPartial() {
      cloud.stately.db.ListPartialResult result = new cloud.stately.db.ListPartialResult(this);
      buildPartialRepeatedFields(result);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartialRepeatedFields(cloud.stately.db.ListPartialResult result) {
      if (itemsBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          items_ = java.util.Collections.unmodifiableList(items_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.items_ = items_;
      } else {
        result.items_ = itemsBuilder_.build();
      }
    }

    private void buildPartial0(cloud.stately.db.ListPartialResult result) {
      int from_bitField0_ = bitField0_;
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof cloud.stately.db.ListPartialResult) {
        return mergeFrom((cloud.stately.db.ListPartialResult)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(cloud.stately.db.ListPartialResult other) {
      if (other == cloud.stately.db.ListPartialResult.getDefaultInstance()) return this;
      if (itemsBuilder_ == null) {
        if (!other.items_.isEmpty()) {
          if (items_.isEmpty()) {
            items_ = other.items_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureItemsIsMutable();
            items_.addAll(other.items_);
          }
          onChanged();
        }
      } else {
        if (!other.items_.isEmpty()) {
          if (itemsBuilder_.isEmpty()) {
            itemsBuilder_.dispose();
            itemsBuilder_ = null;
            items_ = other.items_;
            bitField0_ = (bitField0_ & ~0x00000001);
            itemsBuilder_ = 
              com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                 internalGetItemsFieldBuilder() : null;
          } else {
            itemsBuilder_.addAllMessages(other.items_);
          }
        }
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              cloud.stately.db.Item m =
                  input.readMessage(
                      cloud.stately.db.Item.parser(),
                      extensionRegistry);
              if (itemsBuilder_ == null) {
                ensureItemsIsMutable();
                items_.add(m);
              } else {
                itemsBuilder_.addMessage(m);
              }
              break;
            } // case 10
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.util.List<cloud.stately.db.Item> items_ =
      java.util.Collections.emptyList();
    private void ensureItemsIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        items_ = new java.util.ArrayList<cloud.stately.db.Item>(items_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilder<
        cloud.stately.db.Item, cloud.stately.db.Item.Builder, cloud.stately.db.ItemOrBuilder> itemsBuilder_;

    /**
     * <pre>
     * results is a list that contains one entry for each Item that was found.
     * </pre>
     *
     * <code>repeated .stately.db.Item items = 1 [json_name = "items"];</code>
     */
    public java.util.List<cloud.stately.db.Item> getItemsList() {
      if (itemsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(items_);
      } else {
        return itemsBuilder_.getMessageList();
      }
    }
    /**
     * <pre>
     * results is a list that contains one entry for each Item that was found.
     * </pre>
     *
     * <code>repeated .stately.db.Item items = 1 [json_name = "items"];</code>
     */
    public int getItemsCount() {
      if (itemsBuilder_ == null) {
        return items_.size();
      } else {
        return itemsBuilder_.getCount();
      }
    }
    /**
     * <pre>
     * results is a list that contains one entry for each Item that was found.
     * </pre>
     *
     * <code>repeated .stately.db.Item items = 1 [json_name = "items"];</code>
     */
    public cloud.stately.db.Item getItems(int index) {
      if (itemsBuilder_ == null) {
        return items_.get(index);
      } else {
        return itemsBuilder_.getMessage(index);
      }
    }
    /**
     * <pre>
     * results is a list that contains one entry for each Item that was found.
     * </pre>
     *
     * <code>repeated .stately.db.Item items = 1 [json_name = "items"];</code>
     */
    public Builder setItems(
        int index, cloud.stately.db.Item value) {
      if (itemsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureItemsIsMutable();
        items_.set(index, value);
        onChanged();
      } else {
        itemsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     * results is a list that contains one entry for each Item that was found.
     * </pre>
     *
     * <code>repeated .stately.db.Item items = 1 [json_name = "items"];</code>
     */
    public Builder setItems(
        int index, cloud.stately.db.Item.Builder builderForValue) {
      if (itemsBuilder_ == null) {
        ensureItemsIsMutable();
        items_.set(index, builderForValue.build());
        onChanged();
      } else {
        itemsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * results is a list that contains one entry for each Item that was found.
     * </pre>
     *
     * <code>repeated .stately.db.Item items = 1 [json_name = "items"];</code>
     */
    public Builder addItems(cloud.stately.db.Item value) {
      if (itemsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureItemsIsMutable();
        items_.add(value);
        onChanged();
      } else {
        itemsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <pre>
     * results is a list that contains one entry for each Item that was found.
     * </pre>
     *
     * <code>repeated .stately.db.Item items = 1 [json_name = "items"];</code>
     */
    public Builder addItems(
        int index, cloud.stately.db.Item value) {
      if (itemsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureItemsIsMutable();
        items_.add(index, value);
        onChanged();
      } else {
        itemsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     * results is a list that contains one entry for each Item that was found.
     * </pre>
     *
     * <code>repeated .stately.db.Item items = 1 [json_name = "items"];</code>
     */
    public Builder addItems(
        cloud.stately.db.Item.Builder builderForValue) {
      if (itemsBuilder_ == null) {
        ensureItemsIsMutable();
        items_.add(builderForValue.build());
        onChanged();
      } else {
        itemsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * results is a list that contains one entry for each Item that was found.
     * </pre>
     *
     * <code>repeated .stately.db.Item items = 1 [json_name = "items"];</code>
     */
    public Builder addItems(
        int index, cloud.stately.db.Item.Builder builderForValue) {
      if (itemsBuilder_ == null) {
        ensureItemsIsMutable();
        items_.add(index, builderForValue.build());
        onChanged();
      } else {
        itemsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * results is a list that contains one entry for each Item that was found.
     * </pre>
     *
     * <code>repeated .stately.db.Item items = 1 [json_name = "items"];</code>
     */
    public Builder addAllItems(
        java.lang.Iterable<? extends cloud.stately.db.Item> values) {
      if (itemsBuilder_ == null) {
        ensureItemsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, items_);
        onChanged();
      } else {
        itemsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <pre>
     * results is a list that contains one entry for each Item that was found.
     * </pre>
     *
     * <code>repeated .stately.db.Item items = 1 [json_name = "items"];</code>
     */
    public Builder clearItems() {
      if (itemsBuilder_ == null) {
        items_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        itemsBuilder_.clear();
      }
      return this;
    }
    /**
     * <pre>
     * results is a list that contains one entry for each Item that was found.
     * </pre>
     *
     * <code>repeated .stately.db.Item items = 1 [json_name = "items"];</code>
     */
    public Builder removeItems(int index) {
      if (itemsBuilder_ == null) {
        ensureItemsIsMutable();
        items_.remove(index);
        onChanged();
      } else {
        itemsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <pre>
     * results is a list that contains one entry for each Item that was found.
     * </pre>
     *
     * <code>repeated .stately.db.Item items = 1 [json_name = "items"];</code>
     */
    public cloud.stately.db.Item.Builder getItemsBuilder(
        int index) {
      return internalGetItemsFieldBuilder().getBuilder(index);
    }
    /**
     * <pre>
     * results is a list that contains one entry for each Item that was found.
     * </pre>
     *
     * <code>repeated .stately.db.Item items = 1 [json_name = "items"];</code>
     */
    public cloud.stately.db.ItemOrBuilder getItemsOrBuilder(
        int index) {
      if (itemsBuilder_ == null) {
        return items_.get(index);  } else {
        return itemsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <pre>
     * results is a list that contains one entry for each Item that was found.
     * </pre>
     *
     * <code>repeated .stately.db.Item items = 1 [json_name = "items"];</code>
     */
    public java.util.List<? extends cloud.stately.db.ItemOrBuilder> 
         getItemsOrBuilderList() {
      if (itemsBuilder_ != null) {
        return itemsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(items_);
      }
    }
    /**
     * <pre>
     * results is a list that contains one entry for each Item that was found.
     * </pre>
     *
     * <code>repeated .stately.db.Item items = 1 [json_name = "items"];</code>
     */
    public cloud.stately.db.Item.Builder addItemsBuilder() {
      return internalGetItemsFieldBuilder().addBuilder(
          cloud.stately.db.Item.getDefaultInstance());
    }
    /**
     * <pre>
     * results is a list that contains one entry for each Item that was found.
     * </pre>
     *
     * <code>repeated .stately.db.Item items = 1 [json_name = "items"];</code>
     */
    public cloud.stately.db.Item.Builder addItemsBuilder(
        int index) {
      return internalGetItemsFieldBuilder().addBuilder(
          index, cloud.stately.db.Item.getDefaultInstance());
    }
    /**
     * <pre>
     * results is a list that contains one entry for each Item that was found.
     * </pre>
     *
     * <code>repeated .stately.db.Item items = 1 [json_name = "items"];</code>
     */
    public java.util.List<cloud.stately.db.Item.Builder> 
         getItemsBuilderList() {
      return internalGetItemsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilder<
        cloud.stately.db.Item, cloud.stately.db.Item.Builder, cloud.stately.db.ItemOrBuilder> 
        internalGetItemsFieldBuilder() {
      if (itemsBuilder_ == null) {
        itemsBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
            cloud.stately.db.Item, cloud.stately.db.Item.Builder, cloud.stately.db.ItemOrBuilder>(
                items_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        items_ = null;
      }
      return itemsBuilder_;
    }

    // @@protoc_insertion_point(builder_scope:stately.db.ListPartialResult)
  }

  // @@protoc_insertion_point(class_scope:stately.db.ListPartialResult)
  private static final cloud.stately.db.ListPartialResult DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new cloud.stately.db.ListPartialResult();
  }

  public static cloud.stately.db.ListPartialResult getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ListPartialResult>
      PARSER = new com.google.protobuf.AbstractParser<ListPartialResult>() {
    @java.lang.Override
    public ListPartialResult parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<ListPartialResult> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ListPartialResult> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public cloud.stately.db.ListPartialResult getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

