// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: db/list_filters.proto
// Protobuf Java Version: 4.32.0

package cloud.stately.db;

@com.google.protobuf.Generated
public final class ListFiltersProto {
  private ListFiltersProto() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 32,
      /* patch= */ 0,
      /* suffix= */ "",
      ListFiltersProto.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_stately_db_FilterCondition_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_stately_db_FilterCondition_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_stately_db_CelExpression_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_stately_db_CelExpression_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\025db/list_filters.proto\022\nstately.db\"}\n\017F" +
      "ilterCondition\022\035\n\titem_type\030\001 \001(\tH\000R\010ite" +
      "mType\022B\n\016cel_expression\030\002 \001(\0132\031.stately." +
      "db.CelExpressionH\000R\rcelExpressionB\007\n\005val" +
      "ue\"L\n\rCelExpression\022\033\n\titem_type\030\001 \001(\tR\010" +
      "itemType\022\036\n\nexpression\030\002 \001(\tR\nexpression" +
      "Bm\n\020cloud.stately.dbB\020ListFiltersProtoP\001" +
      "\242\002\003SDX\252\002\nStately.Db\312\002\nStately\\Db\342\002\026State" +
      "ly\\Db\\GPBMetadata\352\002\013Stately::Dbb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_stately_db_FilterCondition_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_stately_db_FilterCondition_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_stately_db_FilterCondition_descriptor,
        new java.lang.String[] { "ItemType", "CelExpression", "Value", });
    internal_static_stately_db_CelExpression_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_stately_db_CelExpression_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_stately_db_CelExpression_descriptor,
        new java.lang.String[] { "ItemType", "Expression", });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
