// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: db/list.proto
// Protobuf Java Version: 4.32.0

package cloud.stately.db;

/**
 * Protobuf enum {@code stately.db.Operator}
 */
@com.google.protobuf.Generated
public enum Operator
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <pre>
   * This is the default
   * </pre>
   *
   * <code>OPERATOR_UNSPECIFIED = 0;</code>
   */
  OPERATOR_UNSPECIFIED(0),
  /**
   * <pre>
   * The key must be greater than the specified value based on lexicographic ordering.
   * </pre>
   *
   * <code>OPERATOR_GREATER_THAN = 4;</code>
   */
  OPERATOR_GREATER_THAN(4),
  /**
   * <pre>
   * The key must be greater than or equal to the specified value based on lexicographic ordering.
   * </pre>
   *
   * <code>OPERATOR_GREATER_THAN_OR_EQUAL = 5;</code>
   */
  OPERATOR_GREATER_THAN_OR_EQUAL(5),
  /**
   * <pre>
   * The key must be less than the specified value based on lexicographic ordering.
   * </pre>
   *
   * <code>OPERATOR_LESS_THAN = 6;</code>
   */
  OPERATOR_LESS_THAN(6),
  /**
   * <pre>
   * The key must be less than or equal to the specified value based on lexicographic ordering.
   * </pre>
   *
   * <code>OPERATOR_LESS_THAN_OR_EQUAL = 7;</code>
   */
  OPERATOR_LESS_THAN_OR_EQUAL(7),
  UNRECOGNIZED(-1),
  ;

  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 32,
      /* patch= */ 0,
      /* suffix= */ "",
      Operator.class.getName());
  }
  /**
   * <pre>
   * This is the default
   * </pre>
   *
   * <code>OPERATOR_UNSPECIFIED = 0;</code>
   */
  public static final int OPERATOR_UNSPECIFIED_VALUE = 0;
  /**
   * <pre>
   * The key must be greater than the specified value based on lexicographic ordering.
   * </pre>
   *
   * <code>OPERATOR_GREATER_THAN = 4;</code>
   */
  public static final int OPERATOR_GREATER_THAN_VALUE = 4;
  /**
   * <pre>
   * The key must be greater than or equal to the specified value based on lexicographic ordering.
   * </pre>
   *
   * <code>OPERATOR_GREATER_THAN_OR_EQUAL = 5;</code>
   */
  public static final int OPERATOR_GREATER_THAN_OR_EQUAL_VALUE = 5;
  /**
   * <pre>
   * The key must be less than the specified value based on lexicographic ordering.
   * </pre>
   *
   * <code>OPERATOR_LESS_THAN = 6;</code>
   */
  public static final int OPERATOR_LESS_THAN_VALUE = 6;
  /**
   * <pre>
   * The key must be less than or equal to the specified value based on lexicographic ordering.
   * </pre>
   *
   * <code>OPERATOR_LESS_THAN_OR_EQUAL = 7;</code>
   */
  public static final int OPERATOR_LESS_THAN_OR_EQUAL_VALUE = 7;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static Operator valueOf(int value) {
    return forNumber(value);
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   */
  public static Operator forNumber(int value) {
    switch (value) {
      case 0: return OPERATOR_UNSPECIFIED;
      case 4: return OPERATOR_GREATER_THAN;
      case 5: return OPERATOR_GREATER_THAN_OR_EQUAL;
      case 6: return OPERATOR_LESS_THAN;
      case 7: return OPERATOR_LESS_THAN_OR_EQUAL;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<Operator>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      Operator> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<Operator>() {
          public Operator findValueByNumber(int number) {
            return Operator.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalStateException(
          "Can't get the descriptor of an unrecognized enum value.");
    }
    return getDescriptor().getValues().get(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return cloud.stately.db.ListProto.getDescriptor().getEnumTypes().get(1);
  }

  private static final Operator[] VALUES = values();

  public static Operator valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private Operator(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:stately.db.Operator)
}

