// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: db/put.proto
// Protobuf Java Version: 4.32.0

package cloud.stately.db;

@com.google.protobuf.Generated
public final class PutProto {
  private PutProto() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 32,
      /* patch= */ 0,
      /* suffix= */ "",
      PutProto.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_stately_db_PutRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_stately_db_PutRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_stately_db_PutItem_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_stately_db_PutItem_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_stately_db_PutResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_stately_db_PutResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014db/put.proto\022\nstately.db\032\rdb/item.prot" +
      "o\"\231\001\n\nPutRequest\022\031\n\010store_id\030\001 \001(\004R\007stor" +
      "eId\022\'\n\004puts\030\002 \003(\0132\023.stately.db.PutItemR\004" +
      "puts\022*\n\021schema_version_id\030\003 \001(\rR\017schemaV" +
      "ersionId\022\033\n\tschema_id\030\004 \001(\004R\010schemaId\"\231\001" +
      "\n\007PutItem\022$\n\004item\030\001 \001(\0132\020.stately.db.Ite" +
      "mR\004item\022B\n\035overwrite_metadata_timestamps" +
      "\030\002 \001(\010R\033overwriteMetadataTimestamps\022$\n\016m" +
      "ust_not_exist\030\003 \001(\010R\014mustNotExist\"5\n\013Put" +
      "Response\022&\n\005items\030\001 \003(\0132\020.stately.db.Ite" +
      "mR\005itemsBe\n\020cloud.stately.dbB\010PutProtoP\001" +
      "\242\002\003SDX\252\002\nStately.Db\312\002\nStately\\Db\342\002\026State" +
      "ly\\Db\\GPBMetadata\352\002\013Stately::Dbb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          cloud.stately.db.ItemProto.getDescriptor(),
        });
    internal_static_stately_db_PutRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_stately_db_PutRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_stately_db_PutRequest_descriptor,
        new java.lang.String[] { "StoreId", "Puts", "SchemaVersionId", "SchemaId", });
    internal_static_stately_db_PutItem_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_stately_db_PutItem_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_stately_db_PutItem_descriptor,
        new java.lang.String[] { "Item", "OverwriteMetadataTimestamps", "MustNotExist", });
    internal_static_stately_db_PutResponse_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_stately_db_PutResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_stately_db_PutResponse_descriptor,
        new java.lang.String[] { "Items", });
    descriptor.resolveAllFeaturesImmutable();
    cloud.stately.db.ItemProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
