// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: db/put.proto
// Protobuf Java Version: 4.32.0

package cloud.stately.db;

/**
 * Protobuf type {@code stately.db.PutRequest}
 */
@com.google.protobuf.Generated
public final class PutRequest extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:stately.db.PutRequest)
    PutRequestOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 32,
      /* patch= */ 0,
      /* suffix= */ "",
      PutRequest.class.getName());
  }
  // Use PutRequest.newBuilder() to construct.
  private PutRequest(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private PutRequest() {
    puts_ = java.util.Collections.emptyList();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return cloud.stately.db.PutProto.internal_static_stately_db_PutRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return cloud.stately.db.PutProto.internal_static_stately_db_PutRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            cloud.stately.db.PutRequest.class, cloud.stately.db.PutRequest.Builder.class);
  }

  public static final int STORE_ID_FIELD_NUMBER = 1;
  private long storeId_ = 0L;
  /**
   * <pre>
   * store_id is a globally unique Store ID, which can be looked up from the
   * console or CLI.
   * </pre>
   *
   * <code>uint64 store_id = 1 [json_name = "storeId"];</code>
   * @return The storeId.
   */
  @java.lang.Override
  public long getStoreId() {
    return storeId_;
  }

  public static final int PUTS_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private java.util.List<cloud.stately.db.PutItem> puts_;
  /**
   * <pre>
   * items to put into the store.
   * </pre>
   *
   * <code>repeated .stately.db.PutItem puts = 2 [json_name = "puts"];</code>
   */
  @java.lang.Override
  public java.util.List<cloud.stately.db.PutItem> getPutsList() {
    return puts_;
  }
  /**
   * <pre>
   * items to put into the store.
   * </pre>
   *
   * <code>repeated .stately.db.PutItem puts = 2 [json_name = "puts"];</code>
   */
  @java.lang.Override
  public java.util.List<? extends cloud.stately.db.PutItemOrBuilder> 
      getPutsOrBuilderList() {
    return puts_;
  }
  /**
   * <pre>
   * items to put into the store.
   * </pre>
   *
   * <code>repeated .stately.db.PutItem puts = 2 [json_name = "puts"];</code>
   */
  @java.lang.Override
  public int getPutsCount() {
    return puts_.size();
  }
  /**
   * <pre>
   * items to put into the store.
   * </pre>
   *
   * <code>repeated .stately.db.PutItem puts = 2 [json_name = "puts"];</code>
   */
  @java.lang.Override
  public cloud.stately.db.PutItem getPuts(int index) {
    return puts_.get(index);
  }
  /**
   * <pre>
   * items to put into the store.
   * </pre>
   *
   * <code>repeated .stately.db.PutItem puts = 2 [json_name = "puts"];</code>
   */
  @java.lang.Override
  public cloud.stately.db.PutItemOrBuilder getPutsOrBuilder(
      int index) {
    return puts_.get(index);
  }

  public static final int SCHEMA_VERSION_ID_FIELD_NUMBER = 3;
  private int schemaVersionId_ = 0;
  /**
   * <pre>
   * schema_version_id is the version of the store's schema to use to interpret
   * items. If there is no version with this ID, the operation will error with
   * SchemaVersionNotFound error. You should not have to set this manually as
   * your generated SDK should know its schema version and wire this in for you.
   * </pre>
   *
   * <code>uint32 schema_version_id = 3 [json_name = "schemaVersionId"];</code>
   * @return The schemaVersionId.
   */
  @java.lang.Override
  public int getSchemaVersionId() {
    return schemaVersionId_;
  }

  public static final int SCHEMA_ID_FIELD_NUMBER = 4;
  private long schemaId_ = 0L;
  /**
   * <pre>
   * schema_id refers to the schema to use for this operation.
   * If the store_id does not have a schema with this ID, the operation will
   * error with SchemaNotFound error. You should not have to set this manually
   * as your generated SDK should know its schema and wire this in for you.
   * </pre>
   *
   * <code>uint64 schema_id = 4 [json_name = "schemaId"];</code>
   * @return The schemaId.
   */
  @java.lang.Override
  public long getSchemaId() {
    return schemaId_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (storeId_ != 0L) {
      output.writeUInt64(1, storeId_);
    }
    for (int i = 0; i < puts_.size(); i++) {
      output.writeMessage(2, puts_.get(i));
    }
    if (schemaVersionId_ != 0) {
      output.writeUInt32(3, schemaVersionId_);
    }
    if (schemaId_ != 0L) {
      output.writeUInt64(4, schemaId_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (storeId_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt64Size(1, storeId_);
    }
    for (int i = 0; i < puts_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, puts_.get(i));
    }
    if (schemaVersionId_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt32Size(3, schemaVersionId_);
    }
    if (schemaId_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt64Size(4, schemaId_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof cloud.stately.db.PutRequest)) {
      return super.equals(obj);
    }
    cloud.stately.db.PutRequest other = (cloud.stately.db.PutRequest) obj;

    if (getStoreId()
        != other.getStoreId()) return false;
    if (!getPutsList()
        .equals(other.getPutsList())) return false;
    if (getSchemaVersionId()
        != other.getSchemaVersionId()) return false;
    if (getSchemaId()
        != other.getSchemaId()) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + STORE_ID_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getStoreId());
    if (getPutsCount() > 0) {
      hash = (37 * hash) + PUTS_FIELD_NUMBER;
      hash = (53 * hash) + getPutsList().hashCode();
    }
    hash = (37 * hash) + SCHEMA_VERSION_ID_FIELD_NUMBER;
    hash = (53 * hash) + getSchemaVersionId();
    hash = (37 * hash) + SCHEMA_ID_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getSchemaId());
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static cloud.stately.db.PutRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static cloud.stately.db.PutRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static cloud.stately.db.PutRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static cloud.stately.db.PutRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static cloud.stately.db.PutRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static cloud.stately.db.PutRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static cloud.stately.db.PutRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static cloud.stately.db.PutRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static cloud.stately.db.PutRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static cloud.stately.db.PutRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static cloud.stately.db.PutRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static cloud.stately.db.PutRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(cloud.stately.db.PutRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code stately.db.PutRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:stately.db.PutRequest)
      cloud.stately.db.PutRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return cloud.stately.db.PutProto.internal_static_stately_db_PutRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return cloud.stately.db.PutProto.internal_static_stately_db_PutRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              cloud.stately.db.PutRequest.class, cloud.stately.db.PutRequest.Builder.class);
    }

    // Construct using cloud.stately.db.PutRequest.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      storeId_ = 0L;
      if (putsBuilder_ == null) {
        puts_ = java.util.Collections.emptyList();
      } else {
        puts_ = null;
        putsBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000002);
      schemaVersionId_ = 0;
      schemaId_ = 0L;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return cloud.stately.db.PutProto.internal_static_stately_db_PutRequest_descriptor;
    }

    @java.lang.Override
    public cloud.stately.db.PutRequest getDefaultInstanceForType() {
      return cloud.stately.db.PutRequest.getDefaultInstance();
    }

    @java.lang.Override
    public cloud.stately.db.PutRequest build() {
      cloud.stately.db.PutRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public cloud.stately.db.PutRequest buildPartial() {
      cloud.stately.db.PutRequest result = new cloud.stately.db.PutRequest(this);
      buildPartialRepeatedFields(result);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartialRepeatedFields(cloud.stately.db.PutRequest result) {
      if (putsBuilder_ == null) {
        if (((bitField0_ & 0x00000002) != 0)) {
          puts_ = java.util.Collections.unmodifiableList(puts_);
          bitField0_ = (bitField0_ & ~0x00000002);
        }
        result.puts_ = puts_;
      } else {
        result.puts_ = putsBuilder_.build();
      }
    }

    private void buildPartial0(cloud.stately.db.PutRequest result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.storeId_ = storeId_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.schemaVersionId_ = schemaVersionId_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.schemaId_ = schemaId_;
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof cloud.stately.db.PutRequest) {
        return mergeFrom((cloud.stately.db.PutRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(cloud.stately.db.PutRequest other) {
      if (other == cloud.stately.db.PutRequest.getDefaultInstance()) return this;
      if (other.getStoreId() != 0L) {
        setStoreId(other.getStoreId());
      }
      if (putsBuilder_ == null) {
        if (!other.puts_.isEmpty()) {
          if (puts_.isEmpty()) {
            puts_ = other.puts_;
            bitField0_ = (bitField0_ & ~0x00000002);
          } else {
            ensurePutsIsMutable();
            puts_.addAll(other.puts_);
          }
          onChanged();
        }
      } else {
        if (!other.puts_.isEmpty()) {
          if (putsBuilder_.isEmpty()) {
            putsBuilder_.dispose();
            putsBuilder_ = null;
            puts_ = other.puts_;
            bitField0_ = (bitField0_ & ~0x00000002);
            putsBuilder_ = 
              com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                 internalGetPutsFieldBuilder() : null;
          } else {
            putsBuilder_.addAllMessages(other.puts_);
          }
        }
      }
      if (other.getSchemaVersionId() != 0) {
        setSchemaVersionId(other.getSchemaVersionId());
      }
      if (other.getSchemaId() != 0L) {
        setSchemaId(other.getSchemaId());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              storeId_ = input.readUInt64();
              bitField0_ |= 0x00000001;
              break;
            } // case 8
            case 18: {
              cloud.stately.db.PutItem m =
                  input.readMessage(
                      cloud.stately.db.PutItem.parser(),
                      extensionRegistry);
              if (putsBuilder_ == null) {
                ensurePutsIsMutable();
                puts_.add(m);
              } else {
                putsBuilder_.addMessage(m);
              }
              break;
            } // case 18
            case 24: {
              schemaVersionId_ = input.readUInt32();
              bitField0_ |= 0x00000004;
              break;
            } // case 24
            case 32: {
              schemaId_ = input.readUInt64();
              bitField0_ |= 0x00000008;
              break;
            } // case 32
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private long storeId_ ;
    /**
     * <pre>
     * store_id is a globally unique Store ID, which can be looked up from the
     * console or CLI.
     * </pre>
     *
     * <code>uint64 store_id = 1 [json_name = "storeId"];</code>
     * @return The storeId.
     */
    @java.lang.Override
    public long getStoreId() {
      return storeId_;
    }
    /**
     * <pre>
     * store_id is a globally unique Store ID, which can be looked up from the
     * console or CLI.
     * </pre>
     *
     * <code>uint64 store_id = 1 [json_name = "storeId"];</code>
     * @param value The storeId to set.
     * @return This builder for chaining.
     */
    public Builder setStoreId(long value) {

      storeId_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * store_id is a globally unique Store ID, which can be looked up from the
     * console or CLI.
     * </pre>
     *
     * <code>uint64 store_id = 1 [json_name = "storeId"];</code>
     * @return This builder for chaining.
     */
    public Builder clearStoreId() {
      bitField0_ = (bitField0_ & ~0x00000001);
      storeId_ = 0L;
      onChanged();
      return this;
    }

    private java.util.List<cloud.stately.db.PutItem> puts_ =
      java.util.Collections.emptyList();
    private void ensurePutsIsMutable() {
      if (!((bitField0_ & 0x00000002) != 0)) {
        puts_ = new java.util.ArrayList<cloud.stately.db.PutItem>(puts_);
        bitField0_ |= 0x00000002;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilder<
        cloud.stately.db.PutItem, cloud.stately.db.PutItem.Builder, cloud.stately.db.PutItemOrBuilder> putsBuilder_;

    /**
     * <pre>
     * items to put into the store.
     * </pre>
     *
     * <code>repeated .stately.db.PutItem puts = 2 [json_name = "puts"];</code>
     */
    public java.util.List<cloud.stately.db.PutItem> getPutsList() {
      if (putsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(puts_);
      } else {
        return putsBuilder_.getMessageList();
      }
    }
    /**
     * <pre>
     * items to put into the store.
     * </pre>
     *
     * <code>repeated .stately.db.PutItem puts = 2 [json_name = "puts"];</code>
     */
    public int getPutsCount() {
      if (putsBuilder_ == null) {
        return puts_.size();
      } else {
        return putsBuilder_.getCount();
      }
    }
    /**
     * <pre>
     * items to put into the store.
     * </pre>
     *
     * <code>repeated .stately.db.PutItem puts = 2 [json_name = "puts"];</code>
     */
    public cloud.stately.db.PutItem getPuts(int index) {
      if (putsBuilder_ == null) {
        return puts_.get(index);
      } else {
        return putsBuilder_.getMessage(index);
      }
    }
    /**
     * <pre>
     * items to put into the store.
     * </pre>
     *
     * <code>repeated .stately.db.PutItem puts = 2 [json_name = "puts"];</code>
     */
    public Builder setPuts(
        int index, cloud.stately.db.PutItem value) {
      if (putsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensurePutsIsMutable();
        puts_.set(index, value);
        onChanged();
      } else {
        putsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     * items to put into the store.
     * </pre>
     *
     * <code>repeated .stately.db.PutItem puts = 2 [json_name = "puts"];</code>
     */
    public Builder setPuts(
        int index, cloud.stately.db.PutItem.Builder builderForValue) {
      if (putsBuilder_ == null) {
        ensurePutsIsMutable();
        puts_.set(index, builderForValue.build());
        onChanged();
      } else {
        putsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * items to put into the store.
     * </pre>
     *
     * <code>repeated .stately.db.PutItem puts = 2 [json_name = "puts"];</code>
     */
    public Builder addPuts(cloud.stately.db.PutItem value) {
      if (putsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensurePutsIsMutable();
        puts_.add(value);
        onChanged();
      } else {
        putsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <pre>
     * items to put into the store.
     * </pre>
     *
     * <code>repeated .stately.db.PutItem puts = 2 [json_name = "puts"];</code>
     */
    public Builder addPuts(
        int index, cloud.stately.db.PutItem value) {
      if (putsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensurePutsIsMutable();
        puts_.add(index, value);
        onChanged();
      } else {
        putsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     * items to put into the store.
     * </pre>
     *
     * <code>repeated .stately.db.PutItem puts = 2 [json_name = "puts"];</code>
     */
    public Builder addPuts(
        cloud.stately.db.PutItem.Builder builderForValue) {
      if (putsBuilder_ == null) {
        ensurePutsIsMutable();
        puts_.add(builderForValue.build());
        onChanged();
      } else {
        putsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * items to put into the store.
     * </pre>
     *
     * <code>repeated .stately.db.PutItem puts = 2 [json_name = "puts"];</code>
     */
    public Builder addPuts(
        int index, cloud.stately.db.PutItem.Builder builderForValue) {
      if (putsBuilder_ == null) {
        ensurePutsIsMutable();
        puts_.add(index, builderForValue.build());
        onChanged();
      } else {
        putsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * items to put into the store.
     * </pre>
     *
     * <code>repeated .stately.db.PutItem puts = 2 [json_name = "puts"];</code>
     */
    public Builder addAllPuts(
        java.lang.Iterable<? extends cloud.stately.db.PutItem> values) {
      if (putsBuilder_ == null) {
        ensurePutsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, puts_);
        onChanged();
      } else {
        putsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <pre>
     * items to put into the store.
     * </pre>
     *
     * <code>repeated .stately.db.PutItem puts = 2 [json_name = "puts"];</code>
     */
    public Builder clearPuts() {
      if (putsBuilder_ == null) {
        puts_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
      } else {
        putsBuilder_.clear();
      }
      return this;
    }
    /**
     * <pre>
     * items to put into the store.
     * </pre>
     *
     * <code>repeated .stately.db.PutItem puts = 2 [json_name = "puts"];</code>
     */
    public Builder removePuts(int index) {
      if (putsBuilder_ == null) {
        ensurePutsIsMutable();
        puts_.remove(index);
        onChanged();
      } else {
        putsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <pre>
     * items to put into the store.
     * </pre>
     *
     * <code>repeated .stately.db.PutItem puts = 2 [json_name = "puts"];</code>
     */
    public cloud.stately.db.PutItem.Builder getPutsBuilder(
        int index) {
      return internalGetPutsFieldBuilder().getBuilder(index);
    }
    /**
     * <pre>
     * items to put into the store.
     * </pre>
     *
     * <code>repeated .stately.db.PutItem puts = 2 [json_name = "puts"];</code>
     */
    public cloud.stately.db.PutItemOrBuilder getPutsOrBuilder(
        int index) {
      if (putsBuilder_ == null) {
        return puts_.get(index);  } else {
        return putsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <pre>
     * items to put into the store.
     * </pre>
     *
     * <code>repeated .stately.db.PutItem puts = 2 [json_name = "puts"];</code>
     */
    public java.util.List<? extends cloud.stately.db.PutItemOrBuilder> 
         getPutsOrBuilderList() {
      if (putsBuilder_ != null) {
        return putsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(puts_);
      }
    }
    /**
     * <pre>
     * items to put into the store.
     * </pre>
     *
     * <code>repeated .stately.db.PutItem puts = 2 [json_name = "puts"];</code>
     */
    public cloud.stately.db.PutItem.Builder addPutsBuilder() {
      return internalGetPutsFieldBuilder().addBuilder(
          cloud.stately.db.PutItem.getDefaultInstance());
    }
    /**
     * <pre>
     * items to put into the store.
     * </pre>
     *
     * <code>repeated .stately.db.PutItem puts = 2 [json_name = "puts"];</code>
     */
    public cloud.stately.db.PutItem.Builder addPutsBuilder(
        int index) {
      return internalGetPutsFieldBuilder().addBuilder(
          index, cloud.stately.db.PutItem.getDefaultInstance());
    }
    /**
     * <pre>
     * items to put into the store.
     * </pre>
     *
     * <code>repeated .stately.db.PutItem puts = 2 [json_name = "puts"];</code>
     */
    public java.util.List<cloud.stately.db.PutItem.Builder> 
         getPutsBuilderList() {
      return internalGetPutsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilder<
        cloud.stately.db.PutItem, cloud.stately.db.PutItem.Builder, cloud.stately.db.PutItemOrBuilder> 
        internalGetPutsFieldBuilder() {
      if (putsBuilder_ == null) {
        putsBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
            cloud.stately.db.PutItem, cloud.stately.db.PutItem.Builder, cloud.stately.db.PutItemOrBuilder>(
                puts_,
                ((bitField0_ & 0x00000002) != 0),
                getParentForChildren(),
                isClean());
        puts_ = null;
      }
      return putsBuilder_;
    }

    private int schemaVersionId_ ;
    /**
     * <pre>
     * schema_version_id is the version of the store's schema to use to interpret
     * items. If there is no version with this ID, the operation will error with
     * SchemaVersionNotFound error. You should not have to set this manually as
     * your generated SDK should know its schema version and wire this in for you.
     * </pre>
     *
     * <code>uint32 schema_version_id = 3 [json_name = "schemaVersionId"];</code>
     * @return The schemaVersionId.
     */
    @java.lang.Override
    public int getSchemaVersionId() {
      return schemaVersionId_;
    }
    /**
     * <pre>
     * schema_version_id is the version of the store's schema to use to interpret
     * items. If there is no version with this ID, the operation will error with
     * SchemaVersionNotFound error. You should not have to set this manually as
     * your generated SDK should know its schema version and wire this in for you.
     * </pre>
     *
     * <code>uint32 schema_version_id = 3 [json_name = "schemaVersionId"];</code>
     * @param value The schemaVersionId to set.
     * @return This builder for chaining.
     */
    public Builder setSchemaVersionId(int value) {

      schemaVersionId_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * schema_version_id is the version of the store's schema to use to interpret
     * items. If there is no version with this ID, the operation will error with
     * SchemaVersionNotFound error. You should not have to set this manually as
     * your generated SDK should know its schema version and wire this in for you.
     * </pre>
     *
     * <code>uint32 schema_version_id = 3 [json_name = "schemaVersionId"];</code>
     * @return This builder for chaining.
     */
    public Builder clearSchemaVersionId() {
      bitField0_ = (bitField0_ & ~0x00000004);
      schemaVersionId_ = 0;
      onChanged();
      return this;
    }

    private long schemaId_ ;
    /**
     * <pre>
     * schema_id refers to the schema to use for this operation.
     * If the store_id does not have a schema with this ID, the operation will
     * error with SchemaNotFound error. You should not have to set this manually
     * as your generated SDK should know its schema and wire this in for you.
     * </pre>
     *
     * <code>uint64 schema_id = 4 [json_name = "schemaId"];</code>
     * @return The schemaId.
     */
    @java.lang.Override
    public long getSchemaId() {
      return schemaId_;
    }
    /**
     * <pre>
     * schema_id refers to the schema to use for this operation.
     * If the store_id does not have a schema with this ID, the operation will
     * error with SchemaNotFound error. You should not have to set this manually
     * as your generated SDK should know its schema and wire this in for you.
     * </pre>
     *
     * <code>uint64 schema_id = 4 [json_name = "schemaId"];</code>
     * @param value The schemaId to set.
     * @return This builder for chaining.
     */
    public Builder setSchemaId(long value) {

      schemaId_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * schema_id refers to the schema to use for this operation.
     * If the store_id does not have a schema with this ID, the operation will
     * error with SchemaNotFound error. You should not have to set this manually
     * as your generated SDK should know its schema and wire this in for you.
     * </pre>
     *
     * <code>uint64 schema_id = 4 [json_name = "schemaId"];</code>
     * @return This builder for chaining.
     */
    public Builder clearSchemaId() {
      bitField0_ = (bitField0_ & ~0x00000008);
      schemaId_ = 0L;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:stately.db.PutRequest)
  }

  // @@protoc_insertion_point(class_scope:stately.db.PutRequest)
  private static final cloud.stately.db.PutRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new cloud.stately.db.PutRequest();
  }

  public static cloud.stately.db.PutRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<PutRequest>
      PARSER = new com.google.protobuf.AbstractParser<PutRequest>() {
    @java.lang.Override
    public PutRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<PutRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<PutRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public cloud.stately.db.PutRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

