// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: db/scan.proto
// Protobuf Java Version: 4.32.0

package cloud.stately.db;

@com.google.protobuf.Generated
public final class ScanProto {
  private ScanProto() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 32,
      /* patch= */ 0,
      /* suffix= */ "",
      ScanProto.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_stately_db_BeginScanRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_stately_db_BeginScanRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_stately_db_SegmentationParams_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_stately_db_SegmentationParams_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rdb/scan.proto\022\nstately.db\032\025db/list_fil" +
      "ters.proto\"\247\002\n\020BeginScanRequest\022\031\n\010store" +
      "_id\030\001 \001(\004R\007storeId\022H\n\021filter_conditions\030" +
      "\002 \003(\0132\033.stately.db.FilterConditionR\020filt" +
      "erConditions\022\024\n\005limit\030\003 \001(\rR\005limit\022O\n\023se" +
      "gmentation_params\030\004 \001(\0132\036.stately.db.Seg" +
      "mentationParamsR\022segmentationParams\022*\n\021s" +
      "chema_version_id\030\005 \001(\rR\017schemaVersionId\022" +
      "\033\n\tschema_id\030\006 \001(\004R\010schemaId\"`\n\022Segmenta" +
      "tionParams\022%\n\016total_segments\030\005 \001(\rR\rtota" +
      "lSegments\022#\n\rsegment_index\030\006 \001(\rR\014segmen" +
      "tIndexBf\n\020cloud.stately.dbB\tScanProtoP\001\242" +
      "\002\003SDX\252\002\nStately.Db\312\002\nStately\\Db\342\002\026Statel" +
      "y\\Db\\GPBMetadata\352\002\013Stately::Dbb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          cloud.stately.db.ListFiltersProto.getDescriptor(),
        });
    internal_static_stately_db_BeginScanRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_stately_db_BeginScanRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_stately_db_BeginScanRequest_descriptor,
        new java.lang.String[] { "StoreId", "FilterConditions", "Limit", "SegmentationParams", "SchemaVersionId", "SchemaId", });
    internal_static_stately_db_SegmentationParams_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_stately_db_SegmentationParams_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_stately_db_SegmentationParams_descriptor,
        new java.lang.String[] { "TotalSegments", "SegmentIndex", });
    descriptor.resolveAllFeaturesImmutable();
    cloud.stately.db.ListFiltersProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
