// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: db/scan.proto
// Protobuf Java Version: 4.32.0

package cloud.stately.db;

/**
 * Protobuf type {@code stately.db.SegmentationParams}
 */
@com.google.protobuf.Generated
public final class SegmentationParams extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:stately.db.SegmentationParams)
    SegmentationParamsOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 32,
      /* patch= */ 0,
      /* suffix= */ "",
      SegmentationParams.class.getName());
  }
  // Use SegmentationParams.newBuilder() to construct.
  private SegmentationParams(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private SegmentationParams() {
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return cloud.stately.db.ScanProto.internal_static_stately_db_SegmentationParams_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return cloud.stately.db.ScanProto.internal_static_stately_db_SegmentationParams_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            cloud.stately.db.SegmentationParams.class, cloud.stately.db.SegmentationParams.Builder.class);
  }

  public static final int TOTAL_SEGMENTS_FIELD_NUMBER = 5;
  private int totalSegments_ = 0;
  /**
   * <pre>
   * total_segments is used to determine the number of segments the store will be split into.
   * The segment_index field will then be used to determine which segment to process.
   * For example, if total_segments is set to 5 then the store will be split into 5 segments
   * and by setting segment_index to 0, 1, 2, 3, or 4 the request will process the corresponding
   * segment.
   * </pre>
   *
   * <code>uint32 total_segments = 5 [json_name = "totalSegments"];</code>
   * @return The totalSegments.
   */
  @java.lang.Override
  public int getTotalSegments() {
    return totalSegments_;
  }

  public static final int SEGMENT_INDEX_FIELD_NUMBER = 6;
  private int segmentIndex_ = 0;
  /**
   * <pre>
   * segment_index is used to determine which segment of the store to process
   * with this request.
   * Segments are zero-indexed so the value of segment_index must be less than total_segments.
   * </pre>
   *
   * <code>uint32 segment_index = 6 [json_name = "segmentIndex"];</code>
   * @return The segmentIndex.
   */
  @java.lang.Override
  public int getSegmentIndex() {
    return segmentIndex_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (totalSegments_ != 0) {
      output.writeUInt32(5, totalSegments_);
    }
    if (segmentIndex_ != 0) {
      output.writeUInt32(6, segmentIndex_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (totalSegments_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt32Size(5, totalSegments_);
    }
    if (segmentIndex_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt32Size(6, segmentIndex_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof cloud.stately.db.SegmentationParams)) {
      return super.equals(obj);
    }
    cloud.stately.db.SegmentationParams other = (cloud.stately.db.SegmentationParams) obj;

    if (getTotalSegments()
        != other.getTotalSegments()) return false;
    if (getSegmentIndex()
        != other.getSegmentIndex()) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + TOTAL_SEGMENTS_FIELD_NUMBER;
    hash = (53 * hash) + getTotalSegments();
    hash = (37 * hash) + SEGMENT_INDEX_FIELD_NUMBER;
    hash = (53 * hash) + getSegmentIndex();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static cloud.stately.db.SegmentationParams parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static cloud.stately.db.SegmentationParams parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static cloud.stately.db.SegmentationParams parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static cloud.stately.db.SegmentationParams parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static cloud.stately.db.SegmentationParams parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static cloud.stately.db.SegmentationParams parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static cloud.stately.db.SegmentationParams parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static cloud.stately.db.SegmentationParams parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static cloud.stately.db.SegmentationParams parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static cloud.stately.db.SegmentationParams parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static cloud.stately.db.SegmentationParams parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static cloud.stately.db.SegmentationParams parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(cloud.stately.db.SegmentationParams prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code stately.db.SegmentationParams}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:stately.db.SegmentationParams)
      cloud.stately.db.SegmentationParamsOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return cloud.stately.db.ScanProto.internal_static_stately_db_SegmentationParams_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return cloud.stately.db.ScanProto.internal_static_stately_db_SegmentationParams_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              cloud.stately.db.SegmentationParams.class, cloud.stately.db.SegmentationParams.Builder.class);
    }

    // Construct using cloud.stately.db.SegmentationParams.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      totalSegments_ = 0;
      segmentIndex_ = 0;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return cloud.stately.db.ScanProto.internal_static_stately_db_SegmentationParams_descriptor;
    }

    @java.lang.Override
    public cloud.stately.db.SegmentationParams getDefaultInstanceForType() {
      return cloud.stately.db.SegmentationParams.getDefaultInstance();
    }

    @java.lang.Override
    public cloud.stately.db.SegmentationParams build() {
      cloud.stately.db.SegmentationParams result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public cloud.stately.db.SegmentationParams buildPartial() {
      cloud.stately.db.SegmentationParams result = new cloud.stately.db.SegmentationParams(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(cloud.stately.db.SegmentationParams result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.totalSegments_ = totalSegments_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.segmentIndex_ = segmentIndex_;
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof cloud.stately.db.SegmentationParams) {
        return mergeFrom((cloud.stately.db.SegmentationParams)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(cloud.stately.db.SegmentationParams other) {
      if (other == cloud.stately.db.SegmentationParams.getDefaultInstance()) return this;
      if (other.getTotalSegments() != 0) {
        setTotalSegments(other.getTotalSegments());
      }
      if (other.getSegmentIndex() != 0) {
        setSegmentIndex(other.getSegmentIndex());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 40: {
              totalSegments_ = input.readUInt32();
              bitField0_ |= 0x00000001;
              break;
            } // case 40
            case 48: {
              segmentIndex_ = input.readUInt32();
              bitField0_ |= 0x00000002;
              break;
            } // case 48
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private int totalSegments_ ;
    /**
     * <pre>
     * total_segments is used to determine the number of segments the store will be split into.
     * The segment_index field will then be used to determine which segment to process.
     * For example, if total_segments is set to 5 then the store will be split into 5 segments
     * and by setting segment_index to 0, 1, 2, 3, or 4 the request will process the corresponding
     * segment.
     * </pre>
     *
     * <code>uint32 total_segments = 5 [json_name = "totalSegments"];</code>
     * @return The totalSegments.
     */
    @java.lang.Override
    public int getTotalSegments() {
      return totalSegments_;
    }
    /**
     * <pre>
     * total_segments is used to determine the number of segments the store will be split into.
     * The segment_index field will then be used to determine which segment to process.
     * For example, if total_segments is set to 5 then the store will be split into 5 segments
     * and by setting segment_index to 0, 1, 2, 3, or 4 the request will process the corresponding
     * segment.
     * </pre>
     *
     * <code>uint32 total_segments = 5 [json_name = "totalSegments"];</code>
     * @param value The totalSegments to set.
     * @return This builder for chaining.
     */
    public Builder setTotalSegments(int value) {

      totalSegments_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * total_segments is used to determine the number of segments the store will be split into.
     * The segment_index field will then be used to determine which segment to process.
     * For example, if total_segments is set to 5 then the store will be split into 5 segments
     * and by setting segment_index to 0, 1, 2, 3, or 4 the request will process the corresponding
     * segment.
     * </pre>
     *
     * <code>uint32 total_segments = 5 [json_name = "totalSegments"];</code>
     * @return This builder for chaining.
     */
    public Builder clearTotalSegments() {
      bitField0_ = (bitField0_ & ~0x00000001);
      totalSegments_ = 0;
      onChanged();
      return this;
    }

    private int segmentIndex_ ;
    /**
     * <pre>
     * segment_index is used to determine which segment of the store to process
     * with this request.
     * Segments are zero-indexed so the value of segment_index must be less than total_segments.
     * </pre>
     *
     * <code>uint32 segment_index = 6 [json_name = "segmentIndex"];</code>
     * @return The segmentIndex.
     */
    @java.lang.Override
    public int getSegmentIndex() {
      return segmentIndex_;
    }
    /**
     * <pre>
     * segment_index is used to determine which segment of the store to process
     * with this request.
     * Segments are zero-indexed so the value of segment_index must be less than total_segments.
     * </pre>
     *
     * <code>uint32 segment_index = 6 [json_name = "segmentIndex"];</code>
     * @param value The segmentIndex to set.
     * @return This builder for chaining.
     */
    public Builder setSegmentIndex(int value) {

      segmentIndex_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * segment_index is used to determine which segment of the store to process
     * with this request.
     * Segments are zero-indexed so the value of segment_index must be less than total_segments.
     * </pre>
     *
     * <code>uint32 segment_index = 6 [json_name = "segmentIndex"];</code>
     * @return This builder for chaining.
     */
    public Builder clearSegmentIndex() {
      bitField0_ = (bitField0_ & ~0x00000002);
      segmentIndex_ = 0;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:stately.db.SegmentationParams)
  }

  // @@protoc_insertion_point(class_scope:stately.db.SegmentationParams)
  private static final cloud.stately.db.SegmentationParams DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new cloud.stately.db.SegmentationParams();
  }

  public static cloud.stately.db.SegmentationParams getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<SegmentationParams>
      PARSER = new com.google.protobuf.AbstractParser<SegmentationParams>() {
    @java.lang.Override
    public SegmentationParams parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<SegmentationParams> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<SegmentationParams> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public cloud.stately.db.SegmentationParams getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

