// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: db/service.proto
// Protobuf Java Version: 4.32.0

package cloud.stately.db;

@com.google.protobuf.Generated
public final class ServiceProto {
  private ServiceProto() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 32,
      /* patch= */ 0,
      /* suffix= */ "",
      ServiceProto.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\020db/service.proto\022\nstately.db\032\026db/conti" +
      "nue_list.proto\032\026db/continue_scan.proto\032\017" +
      "db/delete.proto\032\014db/get.proto\032\rdb/list.p" +
      "roto\032\014db/put.proto\032\rdb/scan.proto\032\022db/sy" +
      "nc_list.proto\032\024db/transaction.proto2\257\005\n\017" +
      "DatabaseService\022;\n\003Put\022\026.stately.db.PutR" +
      "equest\032\027.stately.db.PutResponse\"\003\220\002\002\022;\n\003" +
      "Get\022\026.stately.db.GetRequest\032\027.stately.db" +
      ".GetResponse\"\003\220\002\001\022D\n\006Delete\022\031.stately.db" +
      ".DeleteRequest\032\032.stately.db.DeleteRespon" +
      "se\"\003\220\002\002\022J\n\tBeginList\022\034.stately.db.BeginL" +
      "istRequest\032\030.stately.db.ListResponse\"\003\220\002" +
      "\0010\001\022P\n\014ContinueList\022\037.stately.db.Continu" +
      "eListRequest\032\030.stately.db.ListResponse\"\003" +
      "\220\002\0010\001\022J\n\tBeginScan\022\034.stately.db.BeginSca" +
      "nRequest\032\030.stately.db.ListResponse\"\003\220\002\0010" +
      "\001\022P\n\014ContinueScan\022\037.stately.db.ContinueS" +
      "canRequest\032\030.stately.db.ListResponse\"\003\220\002" +
      "\0010\001\022L\n\010SyncList\022\033.stately.db.SyncListReq" +
      "uest\032\034.stately.db.SyncListResponse\"\003\220\002\0010" +
      "\001\022R\n\013Transaction\022\036.stately.db.Transactio" +
      "nRequest\032\037.stately.db.TransactionRespons" +
      "e(\0010\001Bi\n\020cloud.stately.dbB\014ServiceProtoP" +
      "\001\242\002\003SDX\252\002\nStately.Db\312\002\nStately\\Db\342\002\026Stat" +
      "ely\\Db\\GPBMetadata\352\002\013Stately::Dbb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          cloud.stately.db.ContinueListProto.getDescriptor(),
          cloud.stately.db.ContinueScanProto.getDescriptor(),
          cloud.stately.db.DeleteProto.getDescriptor(),
          cloud.stately.db.GetProto.getDescriptor(),
          cloud.stately.db.ListProto.getDescriptor(),
          cloud.stately.db.PutProto.getDescriptor(),
          cloud.stately.db.ScanProto.getDescriptor(),
          cloud.stately.db.SyncListProto.getDescriptor(),
          cloud.stately.db.TransactionProto.getDescriptor(),
        });
    descriptor.resolveAllFeaturesImmutable();
    cloud.stately.db.ContinueListProto.getDescriptor();
    cloud.stately.db.ContinueScanProto.getDescriptor();
    cloud.stately.db.DeleteProto.getDescriptor();
    cloud.stately.db.GetProto.getDescriptor();
    cloud.stately.db.ListProto.getDescriptor();
    cloud.stately.db.PutProto.getDescriptor();
    cloud.stately.db.ScanProto.getDescriptor();
    cloud.stately.db.SyncListProto.getDescriptor();
    cloud.stately.db.TransactionProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
