// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: db/sync_list.proto
// Protobuf Java Version: 4.32.0

package cloud.stately.db;

@com.google.protobuf.Generated
public final class SyncListProto {
  private SyncListProto() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 32,
      /* patch= */ 0,
      /* suffix= */ "",
      SyncListProto.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_stately_db_SyncListRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_stately_db_SyncListRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_stately_db_SyncListResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_stately_db_SyncListResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_stately_db_SyncListReset_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_stately_db_SyncListReset_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_stately_db_SyncListPartialResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_stately_db_SyncListPartialResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_stately_db_DeletedItem_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_stately_db_DeletedItem_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\022db/sync_list.proto\022\nstately.db\032\rdb/ite" +
      "m.proto\032\rdb/list.proto\"y\n\017SyncListReques" +
      "t\022\035\n\ntoken_data\030\001 \001(\014R\ttokenData\022*\n\021sche" +
      "ma_version_id\030\005 \001(\rR\017schemaVersionId\022\033\n\t" +
      "schema_id\030\006 \001(\004R\010schemaId\"\310\001\n\020SyncListRe" +
      "sponse\0221\n\005reset\030\001 \001(\0132\031.stately.db.SyncL" +
      "istResetH\000R\005reset\022=\n\006result\030\002 \001(\0132#.stat" +
      "ely.db.SyncListPartialResponseH\000R\006result" +
      "\0226\n\010finished\030\003 \001(\0132\030.stately.db.ListFini" +
      "shedH\000R\010finishedB\n\n\010response\"\017\n\rSyncList" +
      "Reset\"\337\001\n\027SyncListPartialResponse\0225\n\rcha" +
      "nged_items\030\001 \003(\0132\020.stately.db.ItemR\014chan" +
      "gedItems\022<\n\rdeleted_items\030\002 \003(\0132\027.statel" +
      "y.db.DeletedItemR\014deletedItems\022O\n%update" +
      "d_item_keys_outside_list_window\030\003 \003(\tR u" +
      "pdatedItemKeysOutsideListWindow\"(\n\013Delet" +
      "edItem\022\031\n\010key_path\030\001 \001(\tR\007keyPathBj\n\020clo" +
      "ud.stately.dbB\rSyncListProtoP\001\242\002\003SDX\252\002\nS" +
      "tately.Db\312\002\nStately\\Db\342\002\026Stately\\Db\\GPBM" +
      "etadata\352\002\013Stately::Dbb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          cloud.stately.db.ItemProto.getDescriptor(),
          cloud.stately.db.ListProto.getDescriptor(),
        });
    internal_static_stately_db_SyncListRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_stately_db_SyncListRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_stately_db_SyncListRequest_descriptor,
        new java.lang.String[] { "TokenData", "SchemaVersionId", "SchemaId", });
    internal_static_stately_db_SyncListResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_stately_db_SyncListResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_stately_db_SyncListResponse_descriptor,
        new java.lang.String[] { "Reset", "Result", "Finished", "Response", });
    internal_static_stately_db_SyncListReset_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_stately_db_SyncListReset_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_stately_db_SyncListReset_descriptor,
        new java.lang.String[] { });
    internal_static_stately_db_SyncListPartialResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_stately_db_SyncListPartialResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_stately_db_SyncListPartialResponse_descriptor,
        new java.lang.String[] { "ChangedItems", "DeletedItems", "UpdatedItemKeysOutsideListWindow", });
    internal_static_stately_db_DeletedItem_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_stately_db_DeletedItem_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_stately_db_DeletedItem_descriptor,
        new java.lang.String[] { "KeyPath", });
    descriptor.resolveAllFeaturesImmutable();
    cloud.stately.db.ItemProto.getDescriptor();
    cloud.stately.db.ListProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
