// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: db/sync_list.proto
// Protobuf Java Version: 4.32.0

package cloud.stately.db;

@com.google.protobuf.Generated
public interface SyncListPartialResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:stately.db.SyncListPartialResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Items in the token window that were added or updated since the last
   * sync/list.
   * </pre>
   *
   * <code>repeated .stately.db.Item changed_items = 1 [json_name = "changedItems"];</code>
   */
  java.util.List<cloud.stately.db.Item> 
      getChangedItemsList();
  /**
   * <pre>
   * Items in the token window that were added or updated since the last
   * sync/list.
   * </pre>
   *
   * <code>repeated .stately.db.Item changed_items = 1 [json_name = "changedItems"];</code>
   */
  cloud.stately.db.Item getChangedItems(int index);
  /**
   * <pre>
   * Items in the token window that were added or updated since the last
   * sync/list.
   * </pre>
   *
   * <code>repeated .stately.db.Item changed_items = 1 [json_name = "changedItems"];</code>
   */
  int getChangedItemsCount();
  /**
   * <pre>
   * Items in the token window that were added or updated since the last
   * sync/list.
   * </pre>
   *
   * <code>repeated .stately.db.Item changed_items = 1 [json_name = "changedItems"];</code>
   */
  java.util.List<? extends cloud.stately.db.ItemOrBuilder> 
      getChangedItemsOrBuilderList();
  /**
   * <pre>
   * Items in the token window that were added or updated since the last
   * sync/list.
   * </pre>
   *
   * <code>repeated .stately.db.Item changed_items = 1 [json_name = "changedItems"];</code>
   */
  cloud.stately.db.ItemOrBuilder getChangedItemsOrBuilder(
      int index);

  /**
   * <pre>
   * Items in the token window that were deleted since the last sync/list.
   * </pre>
   *
   * <code>repeated .stately.db.DeletedItem deleted_items = 2 [json_name = "deletedItems"];</code>
   */
  java.util.List<cloud.stately.db.DeletedItem> 
      getDeletedItemsList();
  /**
   * <pre>
   * Items in the token window that were deleted since the last sync/list.
   * </pre>
   *
   * <code>repeated .stately.db.DeletedItem deleted_items = 2 [json_name = "deletedItems"];</code>
   */
  cloud.stately.db.DeletedItem getDeletedItems(int index);
  /**
   * <pre>
   * Items in the token window that were deleted since the last sync/list.
   * </pre>
   *
   * <code>repeated .stately.db.DeletedItem deleted_items = 2 [json_name = "deletedItems"];</code>
   */
  int getDeletedItemsCount();
  /**
   * <pre>
   * Items in the token window that were deleted since the last sync/list.
   * </pre>
   *
   * <code>repeated .stately.db.DeletedItem deleted_items = 2 [json_name = "deletedItems"];</code>
   */
  java.util.List<? extends cloud.stately.db.DeletedItemOrBuilder> 
      getDeletedItemsOrBuilderList();
  /**
   * <pre>
   * Items in the token window that were deleted since the last sync/list.
   * </pre>
   *
   * <code>repeated .stately.db.DeletedItem deleted_items = 2 [json_name = "deletedItems"];</code>
   */
  cloud.stately.db.DeletedItemOrBuilder getDeletedItemsOrBuilder(
      int index);

  /**
   * <pre>
   * Keys of items that were updated but Stately cannot tell if they were in the
   * sync window. Treat these as deleted in most cases. For more information
   * see: https://docs.stately.cloud/api/sync
   * </pre>
   *
   * <code>repeated string updated_item_keys_outside_list_window = 3 [json_name = "updatedItemKeysOutsideListWindow"];</code>
   * @return A list containing the updatedItemKeysOutsideListWindow.
   */
  java.util.List<java.lang.String>
      getUpdatedItemKeysOutsideListWindowList();
  /**
   * <pre>
   * Keys of items that were updated but Stately cannot tell if they were in the
   * sync window. Treat these as deleted in most cases. For more information
   * see: https://docs.stately.cloud/api/sync
   * </pre>
   *
   * <code>repeated string updated_item_keys_outside_list_window = 3 [json_name = "updatedItemKeysOutsideListWindow"];</code>
   * @return The count of updatedItemKeysOutsideListWindow.
   */
  int getUpdatedItemKeysOutsideListWindowCount();
  /**
   * <pre>
   * Keys of items that were updated but Stately cannot tell if they were in the
   * sync window. Treat these as deleted in most cases. For more information
   * see: https://docs.stately.cloud/api/sync
   * </pre>
   *
   * <code>repeated string updated_item_keys_outside_list_window = 3 [json_name = "updatedItemKeysOutsideListWindow"];</code>
   * @param index The index of the element to return.
   * @return The updatedItemKeysOutsideListWindow at the given index.
   */
  java.lang.String getUpdatedItemKeysOutsideListWindow(int index);
  /**
   * <pre>
   * Keys of items that were updated but Stately cannot tell if they were in the
   * sync window. Treat these as deleted in most cases. For more information
   * see: https://docs.stately.cloud/api/sync
   * </pre>
   *
   * <code>repeated string updated_item_keys_outside_list_window = 3 [json_name = "updatedItemKeysOutsideListWindow"];</code>
   * @param index The index of the value to return.
   * @return The bytes of the updatedItemKeysOutsideListWindow at the given index.
   */
  com.google.protobuf.ByteString
      getUpdatedItemKeysOutsideListWindowBytes(int index);
}
