// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: db/sync_list.proto
// Protobuf Java Version: 4.32.0

package cloud.stately.db;

@com.google.protobuf.Generated
public interface SyncListResetOrBuilder extends
    // @@protoc_insertion_point(interface_extends:stately.db.SyncListReset)
    com.google.protobuf.MessageOrBuilder {
}
