// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: db/sync_list.proto
// Protobuf Java Version: 4.32.0

package cloud.stately.db;

@com.google.protobuf.Generated
public interface SyncListRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:stately.db.SyncListRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * token_data is an opaque list continuation token returned by a previous call to
   * List, ContinueList, or SyncList.
   * </pre>
   *
   * <code>bytes token_data = 1 [json_name = "tokenData"];</code>
   * @return The tokenData.
   */
  com.google.protobuf.ByteString getTokenData();

  /**
   * <pre>
   * schema_version_id is the schema version id the client is using. This is
   * used to ensure a consistent schema version is used for all items in the result set.
   * If the version the token was created with is different from the client's
   * current version, the response will contain a SyncListReset response followed by
   * items in the client's current schema version. The returned list token can then
   * be used for further SyncList and ContinueList calls with the current schema
   * version, without having to start a new BeginList call.
   * </pre>
   *
   * <code>uint32 schema_version_id = 5 [json_name = "schemaVersionId"];</code>
   * @return The schemaVersionId.
   */
  int getSchemaVersionId();

  /**
   * <pre>
   * schema_id refers to the schema to use for this operation.
   * If the store_id does not have a schema with this ID, the operation will
   * error with SchemaNotFound error. You should not have to set this manually
   * as your generated SDK should know its schema and wire this in for you.
   * </pre>
   *
   * <code>uint64 schema_id = 6 [json_name = "schemaId"];</code>
   * @return The schemaId.
   */
  long getSchemaId();
}
