// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: db/transaction.proto
// Protobuf Java Version: 4.32.0

package cloud.stately.db;

/**
 * <pre>
 * TransactionListResponse is a subset of the ListResponse message, for
 * returning results during the execution of a transaction.
 * </pre>
 *
 * Protobuf type {@code stately.db.TransactionListResponse}
 */
@com.google.protobuf.Generated
public final class TransactionListResponse extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:stately.db.TransactionListResponse)
    TransactionListResponseOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 32,
      /* patch= */ 0,
      /* suffix= */ "",
      TransactionListResponse.class.getName());
  }
  // Use TransactionListResponse.newBuilder() to construct.
  private TransactionListResponse(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private TransactionListResponse() {
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return cloud.stately.db.TransactionProto.internal_static_stately_db_TransactionListResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return cloud.stately.db.TransactionProto.internal_static_stately_db_TransactionListResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            cloud.stately.db.TransactionListResponse.class, cloud.stately.db.TransactionListResponse.Builder.class);
  }

  private int responseCase_ = 0;
  @SuppressWarnings("serial")
  private java.lang.Object response_;
  public enum ResponseCase
      implements com.google.protobuf.Internal.EnumLite,
          com.google.protobuf.AbstractMessage.InternalOneOfEnum {
    RESULT(1),
    FINISHED(2),
    RESPONSE_NOT_SET(0);
    private final int value;
    private ResponseCase(int value) {
      this.value = value;
    }
    /**
     * @param value The number of the enum to look for.
     * @return The enum associated with the given number.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static ResponseCase valueOf(int value) {
      return forNumber(value);
    }

    public static ResponseCase forNumber(int value) {
      switch (value) {
        case 1: return RESULT;
        case 2: return FINISHED;
        case 0: return RESPONSE_NOT_SET;
        default: return null;
      }
    }
    public int getNumber() {
      return this.value;
    }
  };

  public ResponseCase
  getResponseCase() {
    return ResponseCase.forNumber(
        responseCase_);
  }

  public static final int RESULT_FIELD_NUMBER = 1;
  /**
   * <pre>
   * Result is a segment of the result set - multiple of these may be returned
   * in a stream before the final "finished" message.
   * </pre>
   *
   * <code>.stately.db.ListPartialResult result = 1 [json_name = "result"];</code>
   * @return Whether the result field is set.
   */
  @java.lang.Override
  public boolean hasResult() {
    return responseCase_ == 1;
  }
  /**
   * <pre>
   * Result is a segment of the result set - multiple of these may be returned
   * in a stream before the final "finished" message.
   * </pre>
   *
   * <code>.stately.db.ListPartialResult result = 1 [json_name = "result"];</code>
   * @return The result.
   */
  @java.lang.Override
  public cloud.stately.db.ListPartialResult getResult() {
    if (responseCase_ == 1) {
       return (cloud.stately.db.ListPartialResult) response_;
    }
    return cloud.stately.db.ListPartialResult.getDefaultInstance();
  }
  /**
   * <pre>
   * Result is a segment of the result set - multiple of these may be returned
   * in a stream before the final "finished" message.
   * </pre>
   *
   * <code>.stately.db.ListPartialResult result = 1 [json_name = "result"];</code>
   */
  @java.lang.Override
  public cloud.stately.db.ListPartialResultOrBuilder getResultOrBuilder() {
    if (responseCase_ == 1) {
       return (cloud.stately.db.ListPartialResult) response_;
    }
    return cloud.stately.db.ListPartialResult.getDefaultInstance();
  }

  public static final int FINISHED_FIELD_NUMBER = 2;
  /**
   * <pre>
   * Finished is sent when there are no more results in this operation, and
   * there will only be one.
   * </pre>
   *
   * <code>.stately.db.ListFinished finished = 2 [json_name = "finished"];</code>
   * @return Whether the finished field is set.
   */
  @java.lang.Override
  public boolean hasFinished() {
    return responseCase_ == 2;
  }
  /**
   * <pre>
   * Finished is sent when there are no more results in this operation, and
   * there will only be one.
   * </pre>
   *
   * <code>.stately.db.ListFinished finished = 2 [json_name = "finished"];</code>
   * @return The finished.
   */
  @java.lang.Override
  public cloud.stately.db.ListFinished getFinished() {
    if (responseCase_ == 2) {
       return (cloud.stately.db.ListFinished) response_;
    }
    return cloud.stately.db.ListFinished.getDefaultInstance();
  }
  /**
   * <pre>
   * Finished is sent when there are no more results in this operation, and
   * there will only be one.
   * </pre>
   *
   * <code>.stately.db.ListFinished finished = 2 [json_name = "finished"];</code>
   */
  @java.lang.Override
  public cloud.stately.db.ListFinishedOrBuilder getFinishedOrBuilder() {
    if (responseCase_ == 2) {
       return (cloud.stately.db.ListFinished) response_;
    }
    return cloud.stately.db.ListFinished.getDefaultInstance();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (responseCase_ == 1) {
      output.writeMessage(1, (cloud.stately.db.ListPartialResult) response_);
    }
    if (responseCase_ == 2) {
      output.writeMessage(2, (cloud.stately.db.ListFinished) response_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (responseCase_ == 1) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, (cloud.stately.db.ListPartialResult) response_);
    }
    if (responseCase_ == 2) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, (cloud.stately.db.ListFinished) response_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof cloud.stately.db.TransactionListResponse)) {
      return super.equals(obj);
    }
    cloud.stately.db.TransactionListResponse other = (cloud.stately.db.TransactionListResponse) obj;

    if (!getResponseCase().equals(other.getResponseCase())) return false;
    switch (responseCase_) {
      case 1:
        if (!getResult()
            .equals(other.getResult())) return false;
        break;
      case 2:
        if (!getFinished()
            .equals(other.getFinished())) return false;
        break;
      case 0:
      default:
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    switch (responseCase_) {
      case 1:
        hash = (37 * hash) + RESULT_FIELD_NUMBER;
        hash = (53 * hash) + getResult().hashCode();
        break;
      case 2:
        hash = (37 * hash) + FINISHED_FIELD_NUMBER;
        hash = (53 * hash) + getFinished().hashCode();
        break;
      case 0:
      default:
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static cloud.stately.db.TransactionListResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static cloud.stately.db.TransactionListResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static cloud.stately.db.TransactionListResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static cloud.stately.db.TransactionListResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static cloud.stately.db.TransactionListResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static cloud.stately.db.TransactionListResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static cloud.stately.db.TransactionListResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static cloud.stately.db.TransactionListResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static cloud.stately.db.TransactionListResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static cloud.stately.db.TransactionListResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static cloud.stately.db.TransactionListResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static cloud.stately.db.TransactionListResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(cloud.stately.db.TransactionListResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * TransactionListResponse is a subset of the ListResponse message, for
   * returning results during the execution of a transaction.
   * </pre>
   *
   * Protobuf type {@code stately.db.TransactionListResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:stately.db.TransactionListResponse)
      cloud.stately.db.TransactionListResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return cloud.stately.db.TransactionProto.internal_static_stately_db_TransactionListResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return cloud.stately.db.TransactionProto.internal_static_stately_db_TransactionListResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              cloud.stately.db.TransactionListResponse.class, cloud.stately.db.TransactionListResponse.Builder.class);
    }

    // Construct using cloud.stately.db.TransactionListResponse.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      if (resultBuilder_ != null) {
        resultBuilder_.clear();
      }
      if (finishedBuilder_ != null) {
        finishedBuilder_.clear();
      }
      responseCase_ = 0;
      response_ = null;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return cloud.stately.db.TransactionProto.internal_static_stately_db_TransactionListResponse_descriptor;
    }

    @java.lang.Override
    public cloud.stately.db.TransactionListResponse getDefaultInstanceForType() {
      return cloud.stately.db.TransactionListResponse.getDefaultInstance();
    }

    @java.lang.Override
    public cloud.stately.db.TransactionListResponse build() {
      cloud.stately.db.TransactionListResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public cloud.stately.db.TransactionListResponse buildPartial() {
      cloud.stately.db.TransactionListResponse result = new cloud.stately.db.TransactionListResponse(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      buildPartialOneofs(result);
      onBuilt();
      return result;
    }

    private void buildPartial0(cloud.stately.db.TransactionListResponse result) {
      int from_bitField0_ = bitField0_;
    }

    private void buildPartialOneofs(cloud.stately.db.TransactionListResponse result) {
      result.responseCase_ = responseCase_;
      result.response_ = this.response_;
      if (responseCase_ == 1 &&
          resultBuilder_ != null) {
        result.response_ = resultBuilder_.build();
      }
      if (responseCase_ == 2 &&
          finishedBuilder_ != null) {
        result.response_ = finishedBuilder_.build();
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof cloud.stately.db.TransactionListResponse) {
        return mergeFrom((cloud.stately.db.TransactionListResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(cloud.stately.db.TransactionListResponse other) {
      if (other == cloud.stately.db.TransactionListResponse.getDefaultInstance()) return this;
      switch (other.getResponseCase()) {
        case RESULT: {
          mergeResult(other.getResult());
          break;
        }
        case FINISHED: {
          mergeFinished(other.getFinished());
          break;
        }
        case RESPONSE_NOT_SET: {
          break;
        }
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              input.readMessage(
                  internalGetResultFieldBuilder().getBuilder(),
                  extensionRegistry);
              responseCase_ = 1;
              break;
            } // case 10
            case 18: {
              input.readMessage(
                  internalGetFinishedFieldBuilder().getBuilder(),
                  extensionRegistry);
              responseCase_ = 2;
              break;
            } // case 18
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int responseCase_ = 0;
    private java.lang.Object response_;
    public ResponseCase
        getResponseCase() {
      return ResponseCase.forNumber(
          responseCase_);
    }

    public Builder clearResponse() {
      responseCase_ = 0;
      response_ = null;
      onChanged();
      return this;
    }

    private int bitField0_;

    private com.google.protobuf.SingleFieldBuilder<
        cloud.stately.db.ListPartialResult, cloud.stately.db.ListPartialResult.Builder, cloud.stately.db.ListPartialResultOrBuilder> resultBuilder_;
    /**
     * <pre>
     * Result is a segment of the result set - multiple of these may be returned
     * in a stream before the final "finished" message.
     * </pre>
     *
     * <code>.stately.db.ListPartialResult result = 1 [json_name = "result"];</code>
     * @return Whether the result field is set.
     */
    @java.lang.Override
    public boolean hasResult() {
      return responseCase_ == 1;
    }
    /**
     * <pre>
     * Result is a segment of the result set - multiple of these may be returned
     * in a stream before the final "finished" message.
     * </pre>
     *
     * <code>.stately.db.ListPartialResult result = 1 [json_name = "result"];</code>
     * @return The result.
     */
    @java.lang.Override
    public cloud.stately.db.ListPartialResult getResult() {
      if (resultBuilder_ == null) {
        if (responseCase_ == 1) {
          return (cloud.stately.db.ListPartialResult) response_;
        }
        return cloud.stately.db.ListPartialResult.getDefaultInstance();
      } else {
        if (responseCase_ == 1) {
          return resultBuilder_.getMessage();
        }
        return cloud.stately.db.ListPartialResult.getDefaultInstance();
      }
    }
    /**
     * <pre>
     * Result is a segment of the result set - multiple of these may be returned
     * in a stream before the final "finished" message.
     * </pre>
     *
     * <code>.stately.db.ListPartialResult result = 1 [json_name = "result"];</code>
     */
    public Builder setResult(cloud.stately.db.ListPartialResult value) {
      if (resultBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        response_ = value;
        onChanged();
      } else {
        resultBuilder_.setMessage(value);
      }
      responseCase_ = 1;
      return this;
    }
    /**
     * <pre>
     * Result is a segment of the result set - multiple of these may be returned
     * in a stream before the final "finished" message.
     * </pre>
     *
     * <code>.stately.db.ListPartialResult result = 1 [json_name = "result"];</code>
     */
    public Builder setResult(
        cloud.stately.db.ListPartialResult.Builder builderForValue) {
      if (resultBuilder_ == null) {
        response_ = builderForValue.build();
        onChanged();
      } else {
        resultBuilder_.setMessage(builderForValue.build());
      }
      responseCase_ = 1;
      return this;
    }
    /**
     * <pre>
     * Result is a segment of the result set - multiple of these may be returned
     * in a stream before the final "finished" message.
     * </pre>
     *
     * <code>.stately.db.ListPartialResult result = 1 [json_name = "result"];</code>
     */
    public Builder mergeResult(cloud.stately.db.ListPartialResult value) {
      if (resultBuilder_ == null) {
        if (responseCase_ == 1 &&
            response_ != cloud.stately.db.ListPartialResult.getDefaultInstance()) {
          response_ = cloud.stately.db.ListPartialResult.newBuilder((cloud.stately.db.ListPartialResult) response_)
              .mergeFrom(value).buildPartial();
        } else {
          response_ = value;
        }
        onChanged();
      } else {
        if (responseCase_ == 1) {
          resultBuilder_.mergeFrom(value);
        } else {
          resultBuilder_.setMessage(value);
        }
      }
      responseCase_ = 1;
      return this;
    }
    /**
     * <pre>
     * Result is a segment of the result set - multiple of these may be returned
     * in a stream before the final "finished" message.
     * </pre>
     *
     * <code>.stately.db.ListPartialResult result = 1 [json_name = "result"];</code>
     */
    public Builder clearResult() {
      if (resultBuilder_ == null) {
        if (responseCase_ == 1) {
          responseCase_ = 0;
          response_ = null;
          onChanged();
        }
      } else {
        if (responseCase_ == 1) {
          responseCase_ = 0;
          response_ = null;
        }
        resultBuilder_.clear();
      }
      return this;
    }
    /**
     * <pre>
     * Result is a segment of the result set - multiple of these may be returned
     * in a stream before the final "finished" message.
     * </pre>
     *
     * <code>.stately.db.ListPartialResult result = 1 [json_name = "result"];</code>
     */
    public cloud.stately.db.ListPartialResult.Builder getResultBuilder() {
      return internalGetResultFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * Result is a segment of the result set - multiple of these may be returned
     * in a stream before the final "finished" message.
     * </pre>
     *
     * <code>.stately.db.ListPartialResult result = 1 [json_name = "result"];</code>
     */
    @java.lang.Override
    public cloud.stately.db.ListPartialResultOrBuilder getResultOrBuilder() {
      if ((responseCase_ == 1) && (resultBuilder_ != null)) {
        return resultBuilder_.getMessageOrBuilder();
      } else {
        if (responseCase_ == 1) {
          return (cloud.stately.db.ListPartialResult) response_;
        }
        return cloud.stately.db.ListPartialResult.getDefaultInstance();
      }
    }
    /**
     * <pre>
     * Result is a segment of the result set - multiple of these may be returned
     * in a stream before the final "finished" message.
     * </pre>
     *
     * <code>.stately.db.ListPartialResult result = 1 [json_name = "result"];</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        cloud.stately.db.ListPartialResult, cloud.stately.db.ListPartialResult.Builder, cloud.stately.db.ListPartialResultOrBuilder> 
        internalGetResultFieldBuilder() {
      if (resultBuilder_ == null) {
        if (!(responseCase_ == 1)) {
          response_ = cloud.stately.db.ListPartialResult.getDefaultInstance();
        }
        resultBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            cloud.stately.db.ListPartialResult, cloud.stately.db.ListPartialResult.Builder, cloud.stately.db.ListPartialResultOrBuilder>(
                (cloud.stately.db.ListPartialResult) response_,
                getParentForChildren(),
                isClean());
        response_ = null;
      }
      responseCase_ = 1;
      onChanged();
      return resultBuilder_;
    }

    private com.google.protobuf.SingleFieldBuilder<
        cloud.stately.db.ListFinished, cloud.stately.db.ListFinished.Builder, cloud.stately.db.ListFinishedOrBuilder> finishedBuilder_;
    /**
     * <pre>
     * Finished is sent when there are no more results in this operation, and
     * there will only be one.
     * </pre>
     *
     * <code>.stately.db.ListFinished finished = 2 [json_name = "finished"];</code>
     * @return Whether the finished field is set.
     */
    @java.lang.Override
    public boolean hasFinished() {
      return responseCase_ == 2;
    }
    /**
     * <pre>
     * Finished is sent when there are no more results in this operation, and
     * there will only be one.
     * </pre>
     *
     * <code>.stately.db.ListFinished finished = 2 [json_name = "finished"];</code>
     * @return The finished.
     */
    @java.lang.Override
    public cloud.stately.db.ListFinished getFinished() {
      if (finishedBuilder_ == null) {
        if (responseCase_ == 2) {
          return (cloud.stately.db.ListFinished) response_;
        }
        return cloud.stately.db.ListFinished.getDefaultInstance();
      } else {
        if (responseCase_ == 2) {
          return finishedBuilder_.getMessage();
        }
        return cloud.stately.db.ListFinished.getDefaultInstance();
      }
    }
    /**
     * <pre>
     * Finished is sent when there are no more results in this operation, and
     * there will only be one.
     * </pre>
     *
     * <code>.stately.db.ListFinished finished = 2 [json_name = "finished"];</code>
     */
    public Builder setFinished(cloud.stately.db.ListFinished value) {
      if (finishedBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        response_ = value;
        onChanged();
      } else {
        finishedBuilder_.setMessage(value);
      }
      responseCase_ = 2;
      return this;
    }
    /**
     * <pre>
     * Finished is sent when there are no more results in this operation, and
     * there will only be one.
     * </pre>
     *
     * <code>.stately.db.ListFinished finished = 2 [json_name = "finished"];</code>
     */
    public Builder setFinished(
        cloud.stately.db.ListFinished.Builder builderForValue) {
      if (finishedBuilder_ == null) {
        response_ = builderForValue.build();
        onChanged();
      } else {
        finishedBuilder_.setMessage(builderForValue.build());
      }
      responseCase_ = 2;
      return this;
    }
    /**
     * <pre>
     * Finished is sent when there are no more results in this operation, and
     * there will only be one.
     * </pre>
     *
     * <code>.stately.db.ListFinished finished = 2 [json_name = "finished"];</code>
     */
    public Builder mergeFinished(cloud.stately.db.ListFinished value) {
      if (finishedBuilder_ == null) {
        if (responseCase_ == 2 &&
            response_ != cloud.stately.db.ListFinished.getDefaultInstance()) {
          response_ = cloud.stately.db.ListFinished.newBuilder((cloud.stately.db.ListFinished) response_)
              .mergeFrom(value).buildPartial();
        } else {
          response_ = value;
        }
        onChanged();
      } else {
        if (responseCase_ == 2) {
          finishedBuilder_.mergeFrom(value);
        } else {
          finishedBuilder_.setMessage(value);
        }
      }
      responseCase_ = 2;
      return this;
    }
    /**
     * <pre>
     * Finished is sent when there are no more results in this operation, and
     * there will only be one.
     * </pre>
     *
     * <code>.stately.db.ListFinished finished = 2 [json_name = "finished"];</code>
     */
    public Builder clearFinished() {
      if (finishedBuilder_ == null) {
        if (responseCase_ == 2) {
          responseCase_ = 0;
          response_ = null;
          onChanged();
        }
      } else {
        if (responseCase_ == 2) {
          responseCase_ = 0;
          response_ = null;
        }
        finishedBuilder_.clear();
      }
      return this;
    }
    /**
     * <pre>
     * Finished is sent when there are no more results in this operation, and
     * there will only be one.
     * </pre>
     *
     * <code>.stately.db.ListFinished finished = 2 [json_name = "finished"];</code>
     */
    public cloud.stately.db.ListFinished.Builder getFinishedBuilder() {
      return internalGetFinishedFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * Finished is sent when there are no more results in this operation, and
     * there will only be one.
     * </pre>
     *
     * <code>.stately.db.ListFinished finished = 2 [json_name = "finished"];</code>
     */
    @java.lang.Override
    public cloud.stately.db.ListFinishedOrBuilder getFinishedOrBuilder() {
      if ((responseCase_ == 2) && (finishedBuilder_ != null)) {
        return finishedBuilder_.getMessageOrBuilder();
      } else {
        if (responseCase_ == 2) {
          return (cloud.stately.db.ListFinished) response_;
        }
        return cloud.stately.db.ListFinished.getDefaultInstance();
      }
    }
    /**
     * <pre>
     * Finished is sent when there are no more results in this operation, and
     * there will only be one.
     * </pre>
     *
     * <code>.stately.db.ListFinished finished = 2 [json_name = "finished"];</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        cloud.stately.db.ListFinished, cloud.stately.db.ListFinished.Builder, cloud.stately.db.ListFinishedOrBuilder> 
        internalGetFinishedFieldBuilder() {
      if (finishedBuilder_ == null) {
        if (!(responseCase_ == 2)) {
          response_ = cloud.stately.db.ListFinished.getDefaultInstance();
        }
        finishedBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            cloud.stately.db.ListFinished, cloud.stately.db.ListFinished.Builder, cloud.stately.db.ListFinishedOrBuilder>(
                (cloud.stately.db.ListFinished) response_,
                getParentForChildren(),
                isClean());
        response_ = null;
      }
      responseCase_ = 2;
      onChanged();
      return finishedBuilder_;
    }

    // @@protoc_insertion_point(builder_scope:stately.db.TransactionListResponse)
  }

  // @@protoc_insertion_point(class_scope:stately.db.TransactionListResponse)
  private static final cloud.stately.db.TransactionListResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new cloud.stately.db.TransactionListResponse();
  }

  public static cloud.stately.db.TransactionListResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<TransactionListResponse>
      PARSER = new com.google.protobuf.AbstractParser<TransactionListResponse>() {
    @java.lang.Override
    public TransactionListResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<TransactionListResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<TransactionListResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public cloud.stately.db.TransactionListResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

