// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: db/transaction.proto
// Protobuf Java Version: 4.32.0

package cloud.stately.db;

@com.google.protobuf.Generated
public interface TransactionContinueListOrBuilder extends
    // @@protoc_insertion_point(interface_extends:stately.db.TransactionContinueList)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * token is an opaque list continuation token returned by a previous call to
   * TransactionBeginList or TransactionContinueList.
   * </pre>
   *
   * <code>bytes token_data = 1 [json_name = "tokenData"];</code>
   * @return The tokenData.
   */
  com.google.protobuf.ByteString getTokenData();

  /**
   * <pre>
   * direction indicates whether we are expanding the result set (paginating)
   * forward (in the direction of the original List operation) or backward (in
   * the opposite direction). The default is to expand forward.
   * </pre>
   *
   * <code>.stately.db.ContinueListDirection direction = 4 [json_name = "direction"];</code>
   * @return The enum numeric value on the wire for direction.
   */
  int getDirectionValue();
  /**
   * <pre>
   * direction indicates whether we are expanding the result set (paginating)
   * forward (in the direction of the original List operation) or backward (in
   * the opposite direction). The default is to expand forward.
   * </pre>
   *
   * <code>.stately.db.ContinueListDirection direction = 4 [json_name = "direction"];</code>
   * @return The direction.
   */
  cloud.stately.db.ContinueListDirection getDirection();
}
