// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: db/transaction.proto
// Protobuf Java Version: 4.32.0

package cloud.stately.db;

/**
 * Protobuf type {@code stately.db.TransactionFinished}
 */
@com.google.protobuf.Generated
public final class TransactionFinished extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:stately.db.TransactionFinished)
    TransactionFinishedOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 32,
      /* patch= */ 0,
      /* suffix= */ "",
      TransactionFinished.class.getName());
  }
  // Use TransactionFinished.newBuilder() to construct.
  private TransactionFinished(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private TransactionFinished() {
    putResults_ = java.util.Collections.emptyList();
    deleteResults_ = java.util.Collections.emptyList();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return cloud.stately.db.TransactionProto.internal_static_stately_db_TransactionFinished_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return cloud.stately.db.TransactionProto.internal_static_stately_db_TransactionFinished_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            cloud.stately.db.TransactionFinished.class, cloud.stately.db.TransactionFinished.Builder.class);
  }

  public static final int COMMITTED_FIELD_NUMBER = 1;
  private boolean committed_ = false;
  /**
   * <pre>
   * Did the commit finish (the alternative is that it was aborted/rolled back)
   * </pre>
   *
   * <code>bool committed = 1 [json_name = "committed"];</code>
   * @return The committed.
   */
  @java.lang.Override
  public boolean getCommitted() {
    return committed_;
  }

  public static final int PUT_RESULTS_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private java.util.List<cloud.stately.db.Item> putResults_;
  /**
   * <pre>
   * put_results contains the full result of each Put operation. This only comes
   * back with the TransactionFinished message because full metadata isn't
   * available until then.
   * </pre>
   *
   * <code>repeated .stately.db.Item put_results = 2 [json_name = "putResults"];</code>
   */
  @java.lang.Override
  public java.util.List<cloud.stately.db.Item> getPutResultsList() {
    return putResults_;
  }
  /**
   * <pre>
   * put_results contains the full result of each Put operation. This only comes
   * back with the TransactionFinished message because full metadata isn't
   * available until then.
   * </pre>
   *
   * <code>repeated .stately.db.Item put_results = 2 [json_name = "putResults"];</code>
   */
  @java.lang.Override
  public java.util.List<? extends cloud.stately.db.ItemOrBuilder> 
      getPutResultsOrBuilderList() {
    return putResults_;
  }
  /**
   * <pre>
   * put_results contains the full result of each Put operation. This only comes
   * back with the TransactionFinished message because full metadata isn't
   * available until then.
   * </pre>
   *
   * <code>repeated .stately.db.Item put_results = 2 [json_name = "putResults"];</code>
   */
  @java.lang.Override
  public int getPutResultsCount() {
    return putResults_.size();
  }
  /**
   * <pre>
   * put_results contains the full result of each Put operation. This only comes
   * back with the TransactionFinished message because full metadata isn't
   * available until then.
   * </pre>
   *
   * <code>repeated .stately.db.Item put_results = 2 [json_name = "putResults"];</code>
   */
  @java.lang.Override
  public cloud.stately.db.Item getPutResults(int index) {
    return putResults_.get(index);
  }
  /**
   * <pre>
   * put_results contains the full result of each Put operation. This only comes
   * back with the TransactionFinished message because full metadata isn't
   * available until then.
   * </pre>
   *
   * <code>repeated .stately.db.Item put_results = 2 [json_name = "putResults"];</code>
   */
  @java.lang.Override
  public cloud.stately.db.ItemOrBuilder getPutResultsOrBuilder(
      int index) {
    return putResults_.get(index);
  }

  public static final int DELETE_RESULTS_FIELD_NUMBER = 3;
  @SuppressWarnings("serial")
  private java.util.List<cloud.stately.db.DeleteResult> deleteResults_;
  /**
   * <pre>
   * delete_results contains the full result of each Delete operation. This only
   * comes back with the TransactionFinished message because full metadata isn't
   * available until then.
   * </pre>
   *
   * <code>repeated .stately.db.DeleteResult delete_results = 3 [json_name = "deleteResults"];</code>
   */
  @java.lang.Override
  public java.util.List<cloud.stately.db.DeleteResult> getDeleteResultsList() {
    return deleteResults_;
  }
  /**
   * <pre>
   * delete_results contains the full result of each Delete operation. This only
   * comes back with the TransactionFinished message because full metadata isn't
   * available until then.
   * </pre>
   *
   * <code>repeated .stately.db.DeleteResult delete_results = 3 [json_name = "deleteResults"];</code>
   */
  @java.lang.Override
  public java.util.List<? extends cloud.stately.db.DeleteResultOrBuilder> 
      getDeleteResultsOrBuilderList() {
    return deleteResults_;
  }
  /**
   * <pre>
   * delete_results contains the full result of each Delete operation. This only
   * comes back with the TransactionFinished message because full metadata isn't
   * available until then.
   * </pre>
   *
   * <code>repeated .stately.db.DeleteResult delete_results = 3 [json_name = "deleteResults"];</code>
   */
  @java.lang.Override
  public int getDeleteResultsCount() {
    return deleteResults_.size();
  }
  /**
   * <pre>
   * delete_results contains the full result of each Delete operation. This only
   * comes back with the TransactionFinished message because full metadata isn't
   * available until then.
   * </pre>
   *
   * <code>repeated .stately.db.DeleteResult delete_results = 3 [json_name = "deleteResults"];</code>
   */
  @java.lang.Override
  public cloud.stately.db.DeleteResult getDeleteResults(int index) {
    return deleteResults_.get(index);
  }
  /**
   * <pre>
   * delete_results contains the full result of each Delete operation. This only
   * comes back with the TransactionFinished message because full metadata isn't
   * available until then.
   * </pre>
   *
   * <code>repeated .stately.db.DeleteResult delete_results = 3 [json_name = "deleteResults"];</code>
   */
  @java.lang.Override
  public cloud.stately.db.DeleteResultOrBuilder getDeleteResultsOrBuilder(
      int index) {
    return deleteResults_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (committed_ != false) {
      output.writeBool(1, committed_);
    }
    for (int i = 0; i < putResults_.size(); i++) {
      output.writeMessage(2, putResults_.get(i));
    }
    for (int i = 0; i < deleteResults_.size(); i++) {
      output.writeMessage(3, deleteResults_.get(i));
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (committed_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(1, committed_);
    }
    for (int i = 0; i < putResults_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, putResults_.get(i));
    }
    for (int i = 0; i < deleteResults_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, deleteResults_.get(i));
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof cloud.stately.db.TransactionFinished)) {
      return super.equals(obj);
    }
    cloud.stately.db.TransactionFinished other = (cloud.stately.db.TransactionFinished) obj;

    if (getCommitted()
        != other.getCommitted()) return false;
    if (!getPutResultsList()
        .equals(other.getPutResultsList())) return false;
    if (!getDeleteResultsList()
        .equals(other.getDeleteResultsList())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + COMMITTED_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getCommitted());
    if (getPutResultsCount() > 0) {
      hash = (37 * hash) + PUT_RESULTS_FIELD_NUMBER;
      hash = (53 * hash) + getPutResultsList().hashCode();
    }
    if (getDeleteResultsCount() > 0) {
      hash = (37 * hash) + DELETE_RESULTS_FIELD_NUMBER;
      hash = (53 * hash) + getDeleteResultsList().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static cloud.stately.db.TransactionFinished parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static cloud.stately.db.TransactionFinished parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static cloud.stately.db.TransactionFinished parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static cloud.stately.db.TransactionFinished parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static cloud.stately.db.TransactionFinished parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static cloud.stately.db.TransactionFinished parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static cloud.stately.db.TransactionFinished parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static cloud.stately.db.TransactionFinished parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static cloud.stately.db.TransactionFinished parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static cloud.stately.db.TransactionFinished parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static cloud.stately.db.TransactionFinished parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static cloud.stately.db.TransactionFinished parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(cloud.stately.db.TransactionFinished prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code stately.db.TransactionFinished}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:stately.db.TransactionFinished)
      cloud.stately.db.TransactionFinishedOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return cloud.stately.db.TransactionProto.internal_static_stately_db_TransactionFinished_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return cloud.stately.db.TransactionProto.internal_static_stately_db_TransactionFinished_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              cloud.stately.db.TransactionFinished.class, cloud.stately.db.TransactionFinished.Builder.class);
    }

    // Construct using cloud.stately.db.TransactionFinished.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      committed_ = false;
      if (putResultsBuilder_ == null) {
        putResults_ = java.util.Collections.emptyList();
      } else {
        putResults_ = null;
        putResultsBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000002);
      if (deleteResultsBuilder_ == null) {
        deleteResults_ = java.util.Collections.emptyList();
      } else {
        deleteResults_ = null;
        deleteResultsBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000004);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return cloud.stately.db.TransactionProto.internal_static_stately_db_TransactionFinished_descriptor;
    }

    @java.lang.Override
    public cloud.stately.db.TransactionFinished getDefaultInstanceForType() {
      return cloud.stately.db.TransactionFinished.getDefaultInstance();
    }

    @java.lang.Override
    public cloud.stately.db.TransactionFinished build() {
      cloud.stately.db.TransactionFinished result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public cloud.stately.db.TransactionFinished buildPartial() {
      cloud.stately.db.TransactionFinished result = new cloud.stately.db.TransactionFinished(this);
      buildPartialRepeatedFields(result);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartialRepeatedFields(cloud.stately.db.TransactionFinished result) {
      if (putResultsBuilder_ == null) {
        if (((bitField0_ & 0x00000002) != 0)) {
          putResults_ = java.util.Collections.unmodifiableList(putResults_);
          bitField0_ = (bitField0_ & ~0x00000002);
        }
        result.putResults_ = putResults_;
      } else {
        result.putResults_ = putResultsBuilder_.build();
      }
      if (deleteResultsBuilder_ == null) {
        if (((bitField0_ & 0x00000004) != 0)) {
          deleteResults_ = java.util.Collections.unmodifiableList(deleteResults_);
          bitField0_ = (bitField0_ & ~0x00000004);
        }
        result.deleteResults_ = deleteResults_;
      } else {
        result.deleteResults_ = deleteResultsBuilder_.build();
      }
    }

    private void buildPartial0(cloud.stately.db.TransactionFinished result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.committed_ = committed_;
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof cloud.stately.db.TransactionFinished) {
        return mergeFrom((cloud.stately.db.TransactionFinished)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(cloud.stately.db.TransactionFinished other) {
      if (other == cloud.stately.db.TransactionFinished.getDefaultInstance()) return this;
      if (other.getCommitted() != false) {
        setCommitted(other.getCommitted());
      }
      if (putResultsBuilder_ == null) {
        if (!other.putResults_.isEmpty()) {
          if (putResults_.isEmpty()) {
            putResults_ = other.putResults_;
            bitField0_ = (bitField0_ & ~0x00000002);
          } else {
            ensurePutResultsIsMutable();
            putResults_.addAll(other.putResults_);
          }
          onChanged();
        }
      } else {
        if (!other.putResults_.isEmpty()) {
          if (putResultsBuilder_.isEmpty()) {
            putResultsBuilder_.dispose();
            putResultsBuilder_ = null;
            putResults_ = other.putResults_;
            bitField0_ = (bitField0_ & ~0x00000002);
            putResultsBuilder_ = 
              com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                 internalGetPutResultsFieldBuilder() : null;
          } else {
            putResultsBuilder_.addAllMessages(other.putResults_);
          }
        }
      }
      if (deleteResultsBuilder_ == null) {
        if (!other.deleteResults_.isEmpty()) {
          if (deleteResults_.isEmpty()) {
            deleteResults_ = other.deleteResults_;
            bitField0_ = (bitField0_ & ~0x00000004);
          } else {
            ensureDeleteResultsIsMutable();
            deleteResults_.addAll(other.deleteResults_);
          }
          onChanged();
        }
      } else {
        if (!other.deleteResults_.isEmpty()) {
          if (deleteResultsBuilder_.isEmpty()) {
            deleteResultsBuilder_.dispose();
            deleteResultsBuilder_ = null;
            deleteResults_ = other.deleteResults_;
            bitField0_ = (bitField0_ & ~0x00000004);
            deleteResultsBuilder_ = 
              com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                 internalGetDeleteResultsFieldBuilder() : null;
          } else {
            deleteResultsBuilder_.addAllMessages(other.deleteResults_);
          }
        }
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              committed_ = input.readBool();
              bitField0_ |= 0x00000001;
              break;
            } // case 8
            case 18: {
              cloud.stately.db.Item m =
                  input.readMessage(
                      cloud.stately.db.Item.parser(),
                      extensionRegistry);
              if (putResultsBuilder_ == null) {
                ensurePutResultsIsMutable();
                putResults_.add(m);
              } else {
                putResultsBuilder_.addMessage(m);
              }
              break;
            } // case 18
            case 26: {
              cloud.stately.db.DeleteResult m =
                  input.readMessage(
                      cloud.stately.db.DeleteResult.parser(),
                      extensionRegistry);
              if (deleteResultsBuilder_ == null) {
                ensureDeleteResultsIsMutable();
                deleteResults_.add(m);
              } else {
                deleteResultsBuilder_.addMessage(m);
              }
              break;
            } // case 26
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private boolean committed_ ;
    /**
     * <pre>
     * Did the commit finish (the alternative is that it was aborted/rolled back)
     * </pre>
     *
     * <code>bool committed = 1 [json_name = "committed"];</code>
     * @return The committed.
     */
    @java.lang.Override
    public boolean getCommitted() {
      return committed_;
    }
    /**
     * <pre>
     * Did the commit finish (the alternative is that it was aborted/rolled back)
     * </pre>
     *
     * <code>bool committed = 1 [json_name = "committed"];</code>
     * @param value The committed to set.
     * @return This builder for chaining.
     */
    public Builder setCommitted(boolean value) {

      committed_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Did the commit finish (the alternative is that it was aborted/rolled back)
     * </pre>
     *
     * <code>bool committed = 1 [json_name = "committed"];</code>
     * @return This builder for chaining.
     */
    public Builder clearCommitted() {
      bitField0_ = (bitField0_ & ~0x00000001);
      committed_ = false;
      onChanged();
      return this;
    }

    private java.util.List<cloud.stately.db.Item> putResults_ =
      java.util.Collections.emptyList();
    private void ensurePutResultsIsMutable() {
      if (!((bitField0_ & 0x00000002) != 0)) {
        putResults_ = new java.util.ArrayList<cloud.stately.db.Item>(putResults_);
        bitField0_ |= 0x00000002;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilder<
        cloud.stately.db.Item, cloud.stately.db.Item.Builder, cloud.stately.db.ItemOrBuilder> putResultsBuilder_;

    /**
     * <pre>
     * put_results contains the full result of each Put operation. This only comes
     * back with the TransactionFinished message because full metadata isn't
     * available until then.
     * </pre>
     *
     * <code>repeated .stately.db.Item put_results = 2 [json_name = "putResults"];</code>
     */
    public java.util.List<cloud.stately.db.Item> getPutResultsList() {
      if (putResultsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(putResults_);
      } else {
        return putResultsBuilder_.getMessageList();
      }
    }
    /**
     * <pre>
     * put_results contains the full result of each Put operation. This only comes
     * back with the TransactionFinished message because full metadata isn't
     * available until then.
     * </pre>
     *
     * <code>repeated .stately.db.Item put_results = 2 [json_name = "putResults"];</code>
     */
    public int getPutResultsCount() {
      if (putResultsBuilder_ == null) {
        return putResults_.size();
      } else {
        return putResultsBuilder_.getCount();
      }
    }
    /**
     * <pre>
     * put_results contains the full result of each Put operation. This only comes
     * back with the TransactionFinished message because full metadata isn't
     * available until then.
     * </pre>
     *
     * <code>repeated .stately.db.Item put_results = 2 [json_name = "putResults"];</code>
     */
    public cloud.stately.db.Item getPutResults(int index) {
      if (putResultsBuilder_ == null) {
        return putResults_.get(index);
      } else {
        return putResultsBuilder_.getMessage(index);
      }
    }
    /**
     * <pre>
     * put_results contains the full result of each Put operation. This only comes
     * back with the TransactionFinished message because full metadata isn't
     * available until then.
     * </pre>
     *
     * <code>repeated .stately.db.Item put_results = 2 [json_name = "putResults"];</code>
     */
    public Builder setPutResults(
        int index, cloud.stately.db.Item value) {
      if (putResultsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensurePutResultsIsMutable();
        putResults_.set(index, value);
        onChanged();
      } else {
        putResultsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     * put_results contains the full result of each Put operation. This only comes
     * back with the TransactionFinished message because full metadata isn't
     * available until then.
     * </pre>
     *
     * <code>repeated .stately.db.Item put_results = 2 [json_name = "putResults"];</code>
     */
    public Builder setPutResults(
        int index, cloud.stately.db.Item.Builder builderForValue) {
      if (putResultsBuilder_ == null) {
        ensurePutResultsIsMutable();
        putResults_.set(index, builderForValue.build());
        onChanged();
      } else {
        putResultsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * put_results contains the full result of each Put operation. This only comes
     * back with the TransactionFinished message because full metadata isn't
     * available until then.
     * </pre>
     *
     * <code>repeated .stately.db.Item put_results = 2 [json_name = "putResults"];</code>
     */
    public Builder addPutResults(cloud.stately.db.Item value) {
      if (putResultsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensurePutResultsIsMutable();
        putResults_.add(value);
        onChanged();
      } else {
        putResultsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <pre>
     * put_results contains the full result of each Put operation. This only comes
     * back with the TransactionFinished message because full metadata isn't
     * available until then.
     * </pre>
     *
     * <code>repeated .stately.db.Item put_results = 2 [json_name = "putResults"];</code>
     */
    public Builder addPutResults(
        int index, cloud.stately.db.Item value) {
      if (putResultsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensurePutResultsIsMutable();
        putResults_.add(index, value);
        onChanged();
      } else {
        putResultsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     * put_results contains the full result of each Put operation. This only comes
     * back with the TransactionFinished message because full metadata isn't
     * available until then.
     * </pre>
     *
     * <code>repeated .stately.db.Item put_results = 2 [json_name = "putResults"];</code>
     */
    public Builder addPutResults(
        cloud.stately.db.Item.Builder builderForValue) {
      if (putResultsBuilder_ == null) {
        ensurePutResultsIsMutable();
        putResults_.add(builderForValue.build());
        onChanged();
      } else {
        putResultsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * put_results contains the full result of each Put operation. This only comes
     * back with the TransactionFinished message because full metadata isn't
     * available until then.
     * </pre>
     *
     * <code>repeated .stately.db.Item put_results = 2 [json_name = "putResults"];</code>
     */
    public Builder addPutResults(
        int index, cloud.stately.db.Item.Builder builderForValue) {
      if (putResultsBuilder_ == null) {
        ensurePutResultsIsMutable();
        putResults_.add(index, builderForValue.build());
        onChanged();
      } else {
        putResultsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * put_results contains the full result of each Put operation. This only comes
     * back with the TransactionFinished message because full metadata isn't
     * available until then.
     * </pre>
     *
     * <code>repeated .stately.db.Item put_results = 2 [json_name = "putResults"];</code>
     */
    public Builder addAllPutResults(
        java.lang.Iterable<? extends cloud.stately.db.Item> values) {
      if (putResultsBuilder_ == null) {
        ensurePutResultsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, putResults_);
        onChanged();
      } else {
        putResultsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <pre>
     * put_results contains the full result of each Put operation. This only comes
     * back with the TransactionFinished message because full metadata isn't
     * available until then.
     * </pre>
     *
     * <code>repeated .stately.db.Item put_results = 2 [json_name = "putResults"];</code>
     */
    public Builder clearPutResults() {
      if (putResultsBuilder_ == null) {
        putResults_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
      } else {
        putResultsBuilder_.clear();
      }
      return this;
    }
    /**
     * <pre>
     * put_results contains the full result of each Put operation. This only comes
     * back with the TransactionFinished message because full metadata isn't
     * available until then.
     * </pre>
     *
     * <code>repeated .stately.db.Item put_results = 2 [json_name = "putResults"];</code>
     */
    public Builder removePutResults(int index) {
      if (putResultsBuilder_ == null) {
        ensurePutResultsIsMutable();
        putResults_.remove(index);
        onChanged();
      } else {
        putResultsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <pre>
     * put_results contains the full result of each Put operation. This only comes
     * back with the TransactionFinished message because full metadata isn't
     * available until then.
     * </pre>
     *
     * <code>repeated .stately.db.Item put_results = 2 [json_name = "putResults"];</code>
     */
    public cloud.stately.db.Item.Builder getPutResultsBuilder(
        int index) {
      return internalGetPutResultsFieldBuilder().getBuilder(index);
    }
    /**
     * <pre>
     * put_results contains the full result of each Put operation. This only comes
     * back with the TransactionFinished message because full metadata isn't
     * available until then.
     * </pre>
     *
     * <code>repeated .stately.db.Item put_results = 2 [json_name = "putResults"];</code>
     */
    public cloud.stately.db.ItemOrBuilder getPutResultsOrBuilder(
        int index) {
      if (putResultsBuilder_ == null) {
        return putResults_.get(index);  } else {
        return putResultsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <pre>
     * put_results contains the full result of each Put operation. This only comes
     * back with the TransactionFinished message because full metadata isn't
     * available until then.
     * </pre>
     *
     * <code>repeated .stately.db.Item put_results = 2 [json_name = "putResults"];</code>
     */
    public java.util.List<? extends cloud.stately.db.ItemOrBuilder> 
         getPutResultsOrBuilderList() {
      if (putResultsBuilder_ != null) {
        return putResultsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(putResults_);
      }
    }
    /**
     * <pre>
     * put_results contains the full result of each Put operation. This only comes
     * back with the TransactionFinished message because full metadata isn't
     * available until then.
     * </pre>
     *
     * <code>repeated .stately.db.Item put_results = 2 [json_name = "putResults"];</code>
     */
    public cloud.stately.db.Item.Builder addPutResultsBuilder() {
      return internalGetPutResultsFieldBuilder().addBuilder(
          cloud.stately.db.Item.getDefaultInstance());
    }
    /**
     * <pre>
     * put_results contains the full result of each Put operation. This only comes
     * back with the TransactionFinished message because full metadata isn't
     * available until then.
     * </pre>
     *
     * <code>repeated .stately.db.Item put_results = 2 [json_name = "putResults"];</code>
     */
    public cloud.stately.db.Item.Builder addPutResultsBuilder(
        int index) {
      return internalGetPutResultsFieldBuilder().addBuilder(
          index, cloud.stately.db.Item.getDefaultInstance());
    }
    /**
     * <pre>
     * put_results contains the full result of each Put operation. This only comes
     * back with the TransactionFinished message because full metadata isn't
     * available until then.
     * </pre>
     *
     * <code>repeated .stately.db.Item put_results = 2 [json_name = "putResults"];</code>
     */
    public java.util.List<cloud.stately.db.Item.Builder> 
         getPutResultsBuilderList() {
      return internalGetPutResultsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilder<
        cloud.stately.db.Item, cloud.stately.db.Item.Builder, cloud.stately.db.ItemOrBuilder> 
        internalGetPutResultsFieldBuilder() {
      if (putResultsBuilder_ == null) {
        putResultsBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
            cloud.stately.db.Item, cloud.stately.db.Item.Builder, cloud.stately.db.ItemOrBuilder>(
                putResults_,
                ((bitField0_ & 0x00000002) != 0),
                getParentForChildren(),
                isClean());
        putResults_ = null;
      }
      return putResultsBuilder_;
    }

    private java.util.List<cloud.stately.db.DeleteResult> deleteResults_ =
      java.util.Collections.emptyList();
    private void ensureDeleteResultsIsMutable() {
      if (!((bitField0_ & 0x00000004) != 0)) {
        deleteResults_ = new java.util.ArrayList<cloud.stately.db.DeleteResult>(deleteResults_);
        bitField0_ |= 0x00000004;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilder<
        cloud.stately.db.DeleteResult, cloud.stately.db.DeleteResult.Builder, cloud.stately.db.DeleteResultOrBuilder> deleteResultsBuilder_;

    /**
     * <pre>
     * delete_results contains the full result of each Delete operation. This only
     * comes back with the TransactionFinished message because full metadata isn't
     * available until then.
     * </pre>
     *
     * <code>repeated .stately.db.DeleteResult delete_results = 3 [json_name = "deleteResults"];</code>
     */
    public java.util.List<cloud.stately.db.DeleteResult> getDeleteResultsList() {
      if (deleteResultsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(deleteResults_);
      } else {
        return deleteResultsBuilder_.getMessageList();
      }
    }
    /**
     * <pre>
     * delete_results contains the full result of each Delete operation. This only
     * comes back with the TransactionFinished message because full metadata isn't
     * available until then.
     * </pre>
     *
     * <code>repeated .stately.db.DeleteResult delete_results = 3 [json_name = "deleteResults"];</code>
     */
    public int getDeleteResultsCount() {
      if (deleteResultsBuilder_ == null) {
        return deleteResults_.size();
      } else {
        return deleteResultsBuilder_.getCount();
      }
    }
    /**
     * <pre>
     * delete_results contains the full result of each Delete operation. This only
     * comes back with the TransactionFinished message because full metadata isn't
     * available until then.
     * </pre>
     *
     * <code>repeated .stately.db.DeleteResult delete_results = 3 [json_name = "deleteResults"];</code>
     */
    public cloud.stately.db.DeleteResult getDeleteResults(int index) {
      if (deleteResultsBuilder_ == null) {
        return deleteResults_.get(index);
      } else {
        return deleteResultsBuilder_.getMessage(index);
      }
    }
    /**
     * <pre>
     * delete_results contains the full result of each Delete operation. This only
     * comes back with the TransactionFinished message because full metadata isn't
     * available until then.
     * </pre>
     *
     * <code>repeated .stately.db.DeleteResult delete_results = 3 [json_name = "deleteResults"];</code>
     */
    public Builder setDeleteResults(
        int index, cloud.stately.db.DeleteResult value) {
      if (deleteResultsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureDeleteResultsIsMutable();
        deleteResults_.set(index, value);
        onChanged();
      } else {
        deleteResultsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     * delete_results contains the full result of each Delete operation. This only
     * comes back with the TransactionFinished message because full metadata isn't
     * available until then.
     * </pre>
     *
     * <code>repeated .stately.db.DeleteResult delete_results = 3 [json_name = "deleteResults"];</code>
     */
    public Builder setDeleteResults(
        int index, cloud.stately.db.DeleteResult.Builder builderForValue) {
      if (deleteResultsBuilder_ == null) {
        ensureDeleteResultsIsMutable();
        deleteResults_.set(index, builderForValue.build());
        onChanged();
      } else {
        deleteResultsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * delete_results contains the full result of each Delete operation. This only
     * comes back with the TransactionFinished message because full metadata isn't
     * available until then.
     * </pre>
     *
     * <code>repeated .stately.db.DeleteResult delete_results = 3 [json_name = "deleteResults"];</code>
     */
    public Builder addDeleteResults(cloud.stately.db.DeleteResult value) {
      if (deleteResultsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureDeleteResultsIsMutable();
        deleteResults_.add(value);
        onChanged();
      } else {
        deleteResultsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <pre>
     * delete_results contains the full result of each Delete operation. This only
     * comes back with the TransactionFinished message because full metadata isn't
     * available until then.
     * </pre>
     *
     * <code>repeated .stately.db.DeleteResult delete_results = 3 [json_name = "deleteResults"];</code>
     */
    public Builder addDeleteResults(
        int index, cloud.stately.db.DeleteResult value) {
      if (deleteResultsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureDeleteResultsIsMutable();
        deleteResults_.add(index, value);
        onChanged();
      } else {
        deleteResultsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     * delete_results contains the full result of each Delete operation. This only
     * comes back with the TransactionFinished message because full metadata isn't
     * available until then.
     * </pre>
     *
     * <code>repeated .stately.db.DeleteResult delete_results = 3 [json_name = "deleteResults"];</code>
     */
    public Builder addDeleteResults(
        cloud.stately.db.DeleteResult.Builder builderForValue) {
      if (deleteResultsBuilder_ == null) {
        ensureDeleteResultsIsMutable();
        deleteResults_.add(builderForValue.build());
        onChanged();
      } else {
        deleteResultsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * delete_results contains the full result of each Delete operation. This only
     * comes back with the TransactionFinished message because full metadata isn't
     * available until then.
     * </pre>
     *
     * <code>repeated .stately.db.DeleteResult delete_results = 3 [json_name = "deleteResults"];</code>
     */
    public Builder addDeleteResults(
        int index, cloud.stately.db.DeleteResult.Builder builderForValue) {
      if (deleteResultsBuilder_ == null) {
        ensureDeleteResultsIsMutable();
        deleteResults_.add(index, builderForValue.build());
        onChanged();
      } else {
        deleteResultsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * delete_results contains the full result of each Delete operation. This only
     * comes back with the TransactionFinished message because full metadata isn't
     * available until then.
     * </pre>
     *
     * <code>repeated .stately.db.DeleteResult delete_results = 3 [json_name = "deleteResults"];</code>
     */
    public Builder addAllDeleteResults(
        java.lang.Iterable<? extends cloud.stately.db.DeleteResult> values) {
      if (deleteResultsBuilder_ == null) {
        ensureDeleteResultsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, deleteResults_);
        onChanged();
      } else {
        deleteResultsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <pre>
     * delete_results contains the full result of each Delete operation. This only
     * comes back with the TransactionFinished message because full metadata isn't
     * available until then.
     * </pre>
     *
     * <code>repeated .stately.db.DeleteResult delete_results = 3 [json_name = "deleteResults"];</code>
     */
    public Builder clearDeleteResults() {
      if (deleteResultsBuilder_ == null) {
        deleteResults_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
      } else {
        deleteResultsBuilder_.clear();
      }
      return this;
    }
    /**
     * <pre>
     * delete_results contains the full result of each Delete operation. This only
     * comes back with the TransactionFinished message because full metadata isn't
     * available until then.
     * </pre>
     *
     * <code>repeated .stately.db.DeleteResult delete_results = 3 [json_name = "deleteResults"];</code>
     */
    public Builder removeDeleteResults(int index) {
      if (deleteResultsBuilder_ == null) {
        ensureDeleteResultsIsMutable();
        deleteResults_.remove(index);
        onChanged();
      } else {
        deleteResultsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <pre>
     * delete_results contains the full result of each Delete operation. This only
     * comes back with the TransactionFinished message because full metadata isn't
     * available until then.
     * </pre>
     *
     * <code>repeated .stately.db.DeleteResult delete_results = 3 [json_name = "deleteResults"];</code>
     */
    public cloud.stately.db.DeleteResult.Builder getDeleteResultsBuilder(
        int index) {
      return internalGetDeleteResultsFieldBuilder().getBuilder(index);
    }
    /**
     * <pre>
     * delete_results contains the full result of each Delete operation. This only
     * comes back with the TransactionFinished message because full metadata isn't
     * available until then.
     * </pre>
     *
     * <code>repeated .stately.db.DeleteResult delete_results = 3 [json_name = "deleteResults"];</code>
     */
    public cloud.stately.db.DeleteResultOrBuilder getDeleteResultsOrBuilder(
        int index) {
      if (deleteResultsBuilder_ == null) {
        return deleteResults_.get(index);  } else {
        return deleteResultsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <pre>
     * delete_results contains the full result of each Delete operation. This only
     * comes back with the TransactionFinished message because full metadata isn't
     * available until then.
     * </pre>
     *
     * <code>repeated .stately.db.DeleteResult delete_results = 3 [json_name = "deleteResults"];</code>
     */
    public java.util.List<? extends cloud.stately.db.DeleteResultOrBuilder> 
         getDeleteResultsOrBuilderList() {
      if (deleteResultsBuilder_ != null) {
        return deleteResultsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(deleteResults_);
      }
    }
    /**
     * <pre>
     * delete_results contains the full result of each Delete operation. This only
     * comes back with the TransactionFinished message because full metadata isn't
     * available until then.
     * </pre>
     *
     * <code>repeated .stately.db.DeleteResult delete_results = 3 [json_name = "deleteResults"];</code>
     */
    public cloud.stately.db.DeleteResult.Builder addDeleteResultsBuilder() {
      return internalGetDeleteResultsFieldBuilder().addBuilder(
          cloud.stately.db.DeleteResult.getDefaultInstance());
    }
    /**
     * <pre>
     * delete_results contains the full result of each Delete operation. This only
     * comes back with the TransactionFinished message because full metadata isn't
     * available until then.
     * </pre>
     *
     * <code>repeated .stately.db.DeleteResult delete_results = 3 [json_name = "deleteResults"];</code>
     */
    public cloud.stately.db.DeleteResult.Builder addDeleteResultsBuilder(
        int index) {
      return internalGetDeleteResultsFieldBuilder().addBuilder(
          index, cloud.stately.db.DeleteResult.getDefaultInstance());
    }
    /**
     * <pre>
     * delete_results contains the full result of each Delete operation. This only
     * comes back with the TransactionFinished message because full metadata isn't
     * available until then.
     * </pre>
     *
     * <code>repeated .stately.db.DeleteResult delete_results = 3 [json_name = "deleteResults"];</code>
     */
    public java.util.List<cloud.stately.db.DeleteResult.Builder> 
         getDeleteResultsBuilderList() {
      return internalGetDeleteResultsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilder<
        cloud.stately.db.DeleteResult, cloud.stately.db.DeleteResult.Builder, cloud.stately.db.DeleteResultOrBuilder> 
        internalGetDeleteResultsFieldBuilder() {
      if (deleteResultsBuilder_ == null) {
        deleteResultsBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
            cloud.stately.db.DeleteResult, cloud.stately.db.DeleteResult.Builder, cloud.stately.db.DeleteResultOrBuilder>(
                deleteResults_,
                ((bitField0_ & 0x00000004) != 0),
                getParentForChildren(),
                isClean());
        deleteResults_ = null;
      }
      return deleteResultsBuilder_;
    }

    // @@protoc_insertion_point(builder_scope:stately.db.TransactionFinished)
  }

  // @@protoc_insertion_point(class_scope:stately.db.TransactionFinished)
  private static final cloud.stately.db.TransactionFinished DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new cloud.stately.db.TransactionFinished();
  }

  public static cloud.stately.db.TransactionFinished getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<TransactionFinished>
      PARSER = new com.google.protobuf.AbstractParser<TransactionFinished>() {
    @java.lang.Override
    public TransactionFinished parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<TransactionFinished> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<TransactionFinished> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public cloud.stately.db.TransactionFinished getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

