// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: db/transaction.proto
// Protobuf Java Version: 4.32.0

package cloud.stately.db;

@com.google.protobuf.Generated
public interface TransactionResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:stately.db.TransactionResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * message_id is the same as the message_id of the request that triggered this
   * response. This makes it easier to distinguish between multiple responses to
   * different requests..
   * </pre>
   *
   * <code>uint32 message_id = 1 [json_name = "messageId"];</code>
   * @return The messageId.
   */
  int getMessageId();

  /**
   * <pre>
   * The server is responding to a GetItem request
   * </pre>
   *
   * <code>.stately.db.TransactionGetResponse get_results = 2 [json_name = "getResults"];</code>
   * @return Whether the getResults field is set.
   */
  boolean hasGetResults();
  /**
   * <pre>
   * The server is responding to a GetItem request
   * </pre>
   *
   * <code>.stately.db.TransactionGetResponse get_results = 2 [json_name = "getResults"];</code>
   * @return The getResults.
   */
  cloud.stately.db.TransactionGetResponse getGetResults();
  /**
   * <pre>
   * The server is responding to a GetItem request
   * </pre>
   *
   * <code>.stately.db.TransactionGetResponse get_results = 2 [json_name = "getResults"];</code>
   */
  cloud.stately.db.TransactionGetResponseOrBuilder getGetResultsOrBuilder();

  /**
   * <pre>
   * put_ack contains provisionally updated items from a put, including
   * tentative IDs (pending transaction commit).
   * </pre>
   *
   * <code>.stately.db.TransactionPutAck put_ack = 3 [json_name = "putAck"];</code>
   * @return Whether the putAck field is set.
   */
  boolean hasPutAck();
  /**
   * <pre>
   * put_ack contains provisionally updated items from a put, including
   * tentative IDs (pending transaction commit).
   * </pre>
   *
   * <code>.stately.db.TransactionPutAck put_ack = 3 [json_name = "putAck"];</code>
   * @return The putAck.
   */
  cloud.stately.db.TransactionPutAck getPutAck();
  /**
   * <pre>
   * put_ack contains provisionally updated items from a put, including
   * tentative IDs (pending transaction commit).
   * </pre>
   *
   * <code>.stately.db.TransactionPutAck put_ack = 3 [json_name = "putAck"];</code>
   */
  cloud.stately.db.TransactionPutAckOrBuilder getPutAckOrBuilder();

  /**
   * <pre>
   * list_results is the result of a list request.
   * </pre>
   *
   * <code>.stately.db.TransactionListResponse list_results = 4 [json_name = "listResults"];</code>
   * @return Whether the listResults field is set.
   */
  boolean hasListResults();
  /**
   * <pre>
   * list_results is the result of a list request.
   * </pre>
   *
   * <code>.stately.db.TransactionListResponse list_results = 4 [json_name = "listResults"];</code>
   * @return The listResults.
   */
  cloud.stately.db.TransactionListResponse getListResults();
  /**
   * <pre>
   * list_results is the result of a list request.
   * </pre>
   *
   * <code>.stately.db.TransactionListResponse list_results = 4 [json_name = "listResults"];</code>
   */
  cloud.stately.db.TransactionListResponseOrBuilder getListResultsOrBuilder();

  /**
   * <pre>
   * Final information about the transaction, regardless of whether it was committed or aborted.
   * </pre>
   *
   * <code>.stately.db.TransactionFinished finished = 5 [json_name = "finished"];</code>
   * @return Whether the finished field is set.
   */
  boolean hasFinished();
  /**
   * <pre>
   * Final information about the transaction, regardless of whether it was committed or aborted.
   * </pre>
   *
   * <code>.stately.db.TransactionFinished finished = 5 [json_name = "finished"];</code>
   * @return The finished.
   */
  cloud.stately.db.TransactionFinished getFinished();
  /**
   * <pre>
   * Final information about the transaction, regardless of whether it was committed or aborted.
   * </pre>
   *
   * <code>.stately.db.TransactionFinished finished = 5 [json_name = "finished"];</code>
   */
  cloud.stately.db.TransactionFinishedOrBuilder getFinishedOrBuilder();

  cloud.stately.db.TransactionResponse.ResultCase getResultCase();
}
