// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: db/transaction.proto
// Protobuf Java Version: 4.32.0

package cloud.stately.db;

/**
 * <pre>
 * TransactionBegin opens a transaction and sets various options that will be
 * used throughout the transaction.
 * </pre>
 *
 * Protobuf type {@code stately.db.TransactionBegin}
 */
@com.google.protobuf.Generated
public final class TransactionBegin extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:stately.db.TransactionBegin)
    TransactionBeginOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 32,
      /* patch= */ 0,
      /* suffix= */ "",
      TransactionBegin.class.getName());
  }
  // Use TransactionBegin.newBuilder() to construct.
  private TransactionBegin(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private TransactionBegin() {
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return cloud.stately.db.TransactionProto.internal_static_stately_db_TransactionBegin_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return cloud.stately.db.TransactionProto.internal_static_stately_db_TransactionBegin_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            cloud.stately.db.TransactionBegin.class, cloud.stately.db.TransactionBegin.Builder.class);
  }

  public static final int STORE_ID_FIELD_NUMBER = 1;
  private long storeId_ = 0L;
  /**
   * <pre>
   * store_id is a globally unique Store ID, which can be looked up from the
   * console or CLI.
   * </pre>
   *
   * <code>uint64 store_id = 1 [json_name = "storeId"];</code>
   * @return The storeId.
   */
  @java.lang.Override
  public long getStoreId() {
    return storeId_;
  }

  public static final int SCHEMA_VERSION_ID_FIELD_NUMBER = 2;
  private int schemaVersionId_ = 0;
  /**
   * <pre>
   * schema_version_id refers to the item version to base this txn from. All items
   * created or modified in this transaction will be based on this schema
   * version.
   *
   * If the store's schema does not have this version, the operation
   * will error with SchemaVersionNotFound error. You should not have to
   * set this manually as your generated SDK should know its schema version
   * and wire this in for you.
   * </pre>
   *
   * <code>uint32 schema_version_id = 2 [json_name = "schemaVersionId"];</code>
   * @return The schemaVersionId.
   */
  @java.lang.Override
  public int getSchemaVersionId() {
    return schemaVersionId_;
  }

  public static final int SCHEMA_ID_FIELD_NUMBER = 3;
  private long schemaId_ = 0L;
  /**
   * <pre>
   * schema_id refers to the schema to use for this operation.
   * If the store_id does not have a schema with this ID, the operation will
   * error with SchemaNotFound error. You should not have to set this manually
   * as your generated SDK should know its schema and wire this in for you.
   * </pre>
   *
   * <code>uint64 schema_id = 3 [json_name = "schemaId"];</code>
   * @return The schemaId.
   */
  @java.lang.Override
  public long getSchemaId() {
    return schemaId_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (storeId_ != 0L) {
      output.writeUInt64(1, storeId_);
    }
    if (schemaVersionId_ != 0) {
      output.writeUInt32(2, schemaVersionId_);
    }
    if (schemaId_ != 0L) {
      output.writeUInt64(3, schemaId_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (storeId_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt64Size(1, storeId_);
    }
    if (schemaVersionId_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt32Size(2, schemaVersionId_);
    }
    if (schemaId_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt64Size(3, schemaId_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof cloud.stately.db.TransactionBegin)) {
      return super.equals(obj);
    }
    cloud.stately.db.TransactionBegin other = (cloud.stately.db.TransactionBegin) obj;

    if (getStoreId()
        != other.getStoreId()) return false;
    if (getSchemaVersionId()
        != other.getSchemaVersionId()) return false;
    if (getSchemaId()
        != other.getSchemaId()) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + STORE_ID_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getStoreId());
    hash = (37 * hash) + SCHEMA_VERSION_ID_FIELD_NUMBER;
    hash = (53 * hash) + getSchemaVersionId();
    hash = (37 * hash) + SCHEMA_ID_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getSchemaId());
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static cloud.stately.db.TransactionBegin parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static cloud.stately.db.TransactionBegin parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static cloud.stately.db.TransactionBegin parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static cloud.stately.db.TransactionBegin parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static cloud.stately.db.TransactionBegin parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static cloud.stately.db.TransactionBegin parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static cloud.stately.db.TransactionBegin parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static cloud.stately.db.TransactionBegin parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static cloud.stately.db.TransactionBegin parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static cloud.stately.db.TransactionBegin parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static cloud.stately.db.TransactionBegin parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static cloud.stately.db.TransactionBegin parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(cloud.stately.db.TransactionBegin prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * TransactionBegin opens a transaction and sets various options that will be
   * used throughout the transaction.
   * </pre>
   *
   * Protobuf type {@code stately.db.TransactionBegin}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:stately.db.TransactionBegin)
      cloud.stately.db.TransactionBeginOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return cloud.stately.db.TransactionProto.internal_static_stately_db_TransactionBegin_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return cloud.stately.db.TransactionProto.internal_static_stately_db_TransactionBegin_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              cloud.stately.db.TransactionBegin.class, cloud.stately.db.TransactionBegin.Builder.class);
    }

    // Construct using cloud.stately.db.TransactionBegin.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      storeId_ = 0L;
      schemaVersionId_ = 0;
      schemaId_ = 0L;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return cloud.stately.db.TransactionProto.internal_static_stately_db_TransactionBegin_descriptor;
    }

    @java.lang.Override
    public cloud.stately.db.TransactionBegin getDefaultInstanceForType() {
      return cloud.stately.db.TransactionBegin.getDefaultInstance();
    }

    @java.lang.Override
    public cloud.stately.db.TransactionBegin build() {
      cloud.stately.db.TransactionBegin result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public cloud.stately.db.TransactionBegin buildPartial() {
      cloud.stately.db.TransactionBegin result = new cloud.stately.db.TransactionBegin(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(cloud.stately.db.TransactionBegin result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.storeId_ = storeId_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.schemaVersionId_ = schemaVersionId_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.schemaId_ = schemaId_;
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof cloud.stately.db.TransactionBegin) {
        return mergeFrom((cloud.stately.db.TransactionBegin)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(cloud.stately.db.TransactionBegin other) {
      if (other == cloud.stately.db.TransactionBegin.getDefaultInstance()) return this;
      if (other.getStoreId() != 0L) {
        setStoreId(other.getStoreId());
      }
      if (other.getSchemaVersionId() != 0) {
        setSchemaVersionId(other.getSchemaVersionId());
      }
      if (other.getSchemaId() != 0L) {
        setSchemaId(other.getSchemaId());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              storeId_ = input.readUInt64();
              bitField0_ |= 0x00000001;
              break;
            } // case 8
            case 16: {
              schemaVersionId_ = input.readUInt32();
              bitField0_ |= 0x00000002;
              break;
            } // case 16
            case 24: {
              schemaId_ = input.readUInt64();
              bitField0_ |= 0x00000004;
              break;
            } // case 24
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private long storeId_ ;
    /**
     * <pre>
     * store_id is a globally unique Store ID, which can be looked up from the
     * console or CLI.
     * </pre>
     *
     * <code>uint64 store_id = 1 [json_name = "storeId"];</code>
     * @return The storeId.
     */
    @java.lang.Override
    public long getStoreId() {
      return storeId_;
    }
    /**
     * <pre>
     * store_id is a globally unique Store ID, which can be looked up from the
     * console or CLI.
     * </pre>
     *
     * <code>uint64 store_id = 1 [json_name = "storeId"];</code>
     * @param value The storeId to set.
     * @return This builder for chaining.
     */
    public Builder setStoreId(long value) {

      storeId_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * store_id is a globally unique Store ID, which can be looked up from the
     * console or CLI.
     * </pre>
     *
     * <code>uint64 store_id = 1 [json_name = "storeId"];</code>
     * @return This builder for chaining.
     */
    public Builder clearStoreId() {
      bitField0_ = (bitField0_ & ~0x00000001);
      storeId_ = 0L;
      onChanged();
      return this;
    }

    private int schemaVersionId_ ;
    /**
     * <pre>
     * schema_version_id refers to the item version to base this txn from. All items
     * created or modified in this transaction will be based on this schema
     * version.
     *
     * If the store's schema does not have this version, the operation
     * will error with SchemaVersionNotFound error. You should not have to
     * set this manually as your generated SDK should know its schema version
     * and wire this in for you.
     * </pre>
     *
     * <code>uint32 schema_version_id = 2 [json_name = "schemaVersionId"];</code>
     * @return The schemaVersionId.
     */
    @java.lang.Override
    public int getSchemaVersionId() {
      return schemaVersionId_;
    }
    /**
     * <pre>
     * schema_version_id refers to the item version to base this txn from. All items
     * created or modified in this transaction will be based on this schema
     * version.
     *
     * If the store's schema does not have this version, the operation
     * will error with SchemaVersionNotFound error. You should not have to
     * set this manually as your generated SDK should know its schema version
     * and wire this in for you.
     * </pre>
     *
     * <code>uint32 schema_version_id = 2 [json_name = "schemaVersionId"];</code>
     * @param value The schemaVersionId to set.
     * @return This builder for chaining.
     */
    public Builder setSchemaVersionId(int value) {

      schemaVersionId_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * schema_version_id refers to the item version to base this txn from. All items
     * created or modified in this transaction will be based on this schema
     * version.
     *
     * If the store's schema does not have this version, the operation
     * will error with SchemaVersionNotFound error. You should not have to
     * set this manually as your generated SDK should know its schema version
     * and wire this in for you.
     * </pre>
     *
     * <code>uint32 schema_version_id = 2 [json_name = "schemaVersionId"];</code>
     * @return This builder for chaining.
     */
    public Builder clearSchemaVersionId() {
      bitField0_ = (bitField0_ & ~0x00000002);
      schemaVersionId_ = 0;
      onChanged();
      return this;
    }

    private long schemaId_ ;
    /**
     * <pre>
     * schema_id refers to the schema to use for this operation.
     * If the store_id does not have a schema with this ID, the operation will
     * error with SchemaNotFound error. You should not have to set this manually
     * as your generated SDK should know its schema and wire this in for you.
     * </pre>
     *
     * <code>uint64 schema_id = 3 [json_name = "schemaId"];</code>
     * @return The schemaId.
     */
    @java.lang.Override
    public long getSchemaId() {
      return schemaId_;
    }
    /**
     * <pre>
     * schema_id refers to the schema to use for this operation.
     * If the store_id does not have a schema with this ID, the operation will
     * error with SchemaNotFound error. You should not have to set this manually
     * as your generated SDK should know its schema and wire this in for you.
     * </pre>
     *
     * <code>uint64 schema_id = 3 [json_name = "schemaId"];</code>
     * @param value The schemaId to set.
     * @return This builder for chaining.
     */
    public Builder setSchemaId(long value) {

      schemaId_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * schema_id refers to the schema to use for this operation.
     * If the store_id does not have a schema with this ID, the operation will
     * error with SchemaNotFound error. You should not have to set this manually
     * as your generated SDK should know its schema and wire this in for you.
     * </pre>
     *
     * <code>uint64 schema_id = 3 [json_name = "schemaId"];</code>
     * @return This builder for chaining.
     */
    public Builder clearSchemaId() {
      bitField0_ = (bitField0_ & ~0x00000004);
      schemaId_ = 0L;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:stately.db.TransactionBegin)
  }

  // @@protoc_insertion_point(class_scope:stately.db.TransactionBegin)
  private static final cloud.stately.db.TransactionBegin DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new cloud.stately.db.TransactionBegin();
  }

  public static cloud.stately.db.TransactionBegin getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<TransactionBegin>
      PARSER = new com.google.protobuf.AbstractParser<TransactionBegin>() {
    @java.lang.Override
    public TransactionBegin parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<TransactionBegin> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<TransactionBegin> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public cloud.stately.db.TransactionBegin getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

