// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: db/transaction.proto
// Protobuf Java Version: 4.32.0

package cloud.stately.db;

/**
 * <pre>
 * This is a streaming response, so the server may send several of them
 * </pre>
 *
 * Protobuf type {@code stately.db.TransactionResponse}
 */
@com.google.protobuf.Generated
public final class TransactionResponse extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:stately.db.TransactionResponse)
    TransactionResponseOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 32,
      /* patch= */ 0,
      /* suffix= */ "",
      TransactionResponse.class.getName());
  }
  // Use TransactionResponse.newBuilder() to construct.
  private TransactionResponse(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private TransactionResponse() {
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return cloud.stately.db.TransactionProto.internal_static_stately_db_TransactionResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return cloud.stately.db.TransactionProto.internal_static_stately_db_TransactionResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            cloud.stately.db.TransactionResponse.class, cloud.stately.db.TransactionResponse.Builder.class);
  }

  private int resultCase_ = 0;
  @SuppressWarnings("serial")
  private java.lang.Object result_;
  public enum ResultCase
      implements com.google.protobuf.Internal.EnumLite,
          com.google.protobuf.AbstractMessage.InternalOneOfEnum {
    GET_RESULTS(2),
    PUT_ACK(3),
    LIST_RESULTS(4),
    FINISHED(5),
    RESULT_NOT_SET(0);
    private final int value;
    private ResultCase(int value) {
      this.value = value;
    }
    /**
     * @param value The number of the enum to look for.
     * @return The enum associated with the given number.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static ResultCase valueOf(int value) {
      return forNumber(value);
    }

    public static ResultCase forNumber(int value) {
      switch (value) {
        case 2: return GET_RESULTS;
        case 3: return PUT_ACK;
        case 4: return LIST_RESULTS;
        case 5: return FINISHED;
        case 0: return RESULT_NOT_SET;
        default: return null;
      }
    }
    public int getNumber() {
      return this.value;
    }
  };

  public ResultCase
  getResultCase() {
    return ResultCase.forNumber(
        resultCase_);
  }

  public static final int MESSAGE_ID_FIELD_NUMBER = 1;
  private int messageId_ = 0;
  /**
   * <pre>
   * message_id is the same as the message_id of the request that triggered this
   * response. This makes it easier to distinguish between multiple responses to
   * different requests..
   * </pre>
   *
   * <code>uint32 message_id = 1 [json_name = "messageId"];</code>
   * @return The messageId.
   */
  @java.lang.Override
  public int getMessageId() {
    return messageId_;
  }

  public static final int GET_RESULTS_FIELD_NUMBER = 2;
  /**
   * <pre>
   * The server is responding to a GetItem request
   * </pre>
   *
   * <code>.stately.db.TransactionGetResponse get_results = 2 [json_name = "getResults"];</code>
   * @return Whether the getResults field is set.
   */
  @java.lang.Override
  public boolean hasGetResults() {
    return resultCase_ == 2;
  }
  /**
   * <pre>
   * The server is responding to a GetItem request
   * </pre>
   *
   * <code>.stately.db.TransactionGetResponse get_results = 2 [json_name = "getResults"];</code>
   * @return The getResults.
   */
  @java.lang.Override
  public cloud.stately.db.TransactionGetResponse getGetResults() {
    if (resultCase_ == 2) {
       return (cloud.stately.db.TransactionGetResponse) result_;
    }
    return cloud.stately.db.TransactionGetResponse.getDefaultInstance();
  }
  /**
   * <pre>
   * The server is responding to a GetItem request
   * </pre>
   *
   * <code>.stately.db.TransactionGetResponse get_results = 2 [json_name = "getResults"];</code>
   */
  @java.lang.Override
  public cloud.stately.db.TransactionGetResponseOrBuilder getGetResultsOrBuilder() {
    if (resultCase_ == 2) {
       return (cloud.stately.db.TransactionGetResponse) result_;
    }
    return cloud.stately.db.TransactionGetResponse.getDefaultInstance();
  }

  public static final int PUT_ACK_FIELD_NUMBER = 3;
  /**
   * <pre>
   * put_ack contains provisionally updated items from a put, including
   * tentative IDs (pending transaction commit).
   * </pre>
   *
   * <code>.stately.db.TransactionPutAck put_ack = 3 [json_name = "putAck"];</code>
   * @return Whether the putAck field is set.
   */
  @java.lang.Override
  public boolean hasPutAck() {
    return resultCase_ == 3;
  }
  /**
   * <pre>
   * put_ack contains provisionally updated items from a put, including
   * tentative IDs (pending transaction commit).
   * </pre>
   *
   * <code>.stately.db.TransactionPutAck put_ack = 3 [json_name = "putAck"];</code>
   * @return The putAck.
   */
  @java.lang.Override
  public cloud.stately.db.TransactionPutAck getPutAck() {
    if (resultCase_ == 3) {
       return (cloud.stately.db.TransactionPutAck) result_;
    }
    return cloud.stately.db.TransactionPutAck.getDefaultInstance();
  }
  /**
   * <pre>
   * put_ack contains provisionally updated items from a put, including
   * tentative IDs (pending transaction commit).
   * </pre>
   *
   * <code>.stately.db.TransactionPutAck put_ack = 3 [json_name = "putAck"];</code>
   */
  @java.lang.Override
  public cloud.stately.db.TransactionPutAckOrBuilder getPutAckOrBuilder() {
    if (resultCase_ == 3) {
       return (cloud.stately.db.TransactionPutAck) result_;
    }
    return cloud.stately.db.TransactionPutAck.getDefaultInstance();
  }

  public static final int LIST_RESULTS_FIELD_NUMBER = 4;
  /**
   * <pre>
   * list_results is the result of a list request.
   * </pre>
   *
   * <code>.stately.db.TransactionListResponse list_results = 4 [json_name = "listResults"];</code>
   * @return Whether the listResults field is set.
   */
  @java.lang.Override
  public boolean hasListResults() {
    return resultCase_ == 4;
  }
  /**
   * <pre>
   * list_results is the result of a list request.
   * </pre>
   *
   * <code>.stately.db.TransactionListResponse list_results = 4 [json_name = "listResults"];</code>
   * @return The listResults.
   */
  @java.lang.Override
  public cloud.stately.db.TransactionListResponse getListResults() {
    if (resultCase_ == 4) {
       return (cloud.stately.db.TransactionListResponse) result_;
    }
    return cloud.stately.db.TransactionListResponse.getDefaultInstance();
  }
  /**
   * <pre>
   * list_results is the result of a list request.
   * </pre>
   *
   * <code>.stately.db.TransactionListResponse list_results = 4 [json_name = "listResults"];</code>
   */
  @java.lang.Override
  public cloud.stately.db.TransactionListResponseOrBuilder getListResultsOrBuilder() {
    if (resultCase_ == 4) {
       return (cloud.stately.db.TransactionListResponse) result_;
    }
    return cloud.stately.db.TransactionListResponse.getDefaultInstance();
  }

  public static final int FINISHED_FIELD_NUMBER = 5;
  /**
   * <pre>
   * Final information about the transaction, regardless of whether it was committed or aborted.
   * </pre>
   *
   * <code>.stately.db.TransactionFinished finished = 5 [json_name = "finished"];</code>
   * @return Whether the finished field is set.
   */
  @java.lang.Override
  public boolean hasFinished() {
    return resultCase_ == 5;
  }
  /**
   * <pre>
   * Final information about the transaction, regardless of whether it was committed or aborted.
   * </pre>
   *
   * <code>.stately.db.TransactionFinished finished = 5 [json_name = "finished"];</code>
   * @return The finished.
   */
  @java.lang.Override
  public cloud.stately.db.TransactionFinished getFinished() {
    if (resultCase_ == 5) {
       return (cloud.stately.db.TransactionFinished) result_;
    }
    return cloud.stately.db.TransactionFinished.getDefaultInstance();
  }
  /**
   * <pre>
   * Final information about the transaction, regardless of whether it was committed or aborted.
   * </pre>
   *
   * <code>.stately.db.TransactionFinished finished = 5 [json_name = "finished"];</code>
   */
  @java.lang.Override
  public cloud.stately.db.TransactionFinishedOrBuilder getFinishedOrBuilder() {
    if (resultCase_ == 5) {
       return (cloud.stately.db.TransactionFinished) result_;
    }
    return cloud.stately.db.TransactionFinished.getDefaultInstance();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (messageId_ != 0) {
      output.writeUInt32(1, messageId_);
    }
    if (resultCase_ == 2) {
      output.writeMessage(2, (cloud.stately.db.TransactionGetResponse) result_);
    }
    if (resultCase_ == 3) {
      output.writeMessage(3, (cloud.stately.db.TransactionPutAck) result_);
    }
    if (resultCase_ == 4) {
      output.writeMessage(4, (cloud.stately.db.TransactionListResponse) result_);
    }
    if (resultCase_ == 5) {
      output.writeMessage(5, (cloud.stately.db.TransactionFinished) result_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (messageId_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt32Size(1, messageId_);
    }
    if (resultCase_ == 2) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, (cloud.stately.db.TransactionGetResponse) result_);
    }
    if (resultCase_ == 3) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, (cloud.stately.db.TransactionPutAck) result_);
    }
    if (resultCase_ == 4) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(4, (cloud.stately.db.TransactionListResponse) result_);
    }
    if (resultCase_ == 5) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(5, (cloud.stately.db.TransactionFinished) result_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof cloud.stately.db.TransactionResponse)) {
      return super.equals(obj);
    }
    cloud.stately.db.TransactionResponse other = (cloud.stately.db.TransactionResponse) obj;

    if (getMessageId()
        != other.getMessageId()) return false;
    if (!getResultCase().equals(other.getResultCase())) return false;
    switch (resultCase_) {
      case 2:
        if (!getGetResults()
            .equals(other.getGetResults())) return false;
        break;
      case 3:
        if (!getPutAck()
            .equals(other.getPutAck())) return false;
        break;
      case 4:
        if (!getListResults()
            .equals(other.getListResults())) return false;
        break;
      case 5:
        if (!getFinished()
            .equals(other.getFinished())) return false;
        break;
      case 0:
      default:
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + MESSAGE_ID_FIELD_NUMBER;
    hash = (53 * hash) + getMessageId();
    switch (resultCase_) {
      case 2:
        hash = (37 * hash) + GET_RESULTS_FIELD_NUMBER;
        hash = (53 * hash) + getGetResults().hashCode();
        break;
      case 3:
        hash = (37 * hash) + PUT_ACK_FIELD_NUMBER;
        hash = (53 * hash) + getPutAck().hashCode();
        break;
      case 4:
        hash = (37 * hash) + LIST_RESULTS_FIELD_NUMBER;
        hash = (53 * hash) + getListResults().hashCode();
        break;
      case 5:
        hash = (37 * hash) + FINISHED_FIELD_NUMBER;
        hash = (53 * hash) + getFinished().hashCode();
        break;
      case 0:
      default:
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static cloud.stately.db.TransactionResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static cloud.stately.db.TransactionResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static cloud.stately.db.TransactionResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static cloud.stately.db.TransactionResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static cloud.stately.db.TransactionResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static cloud.stately.db.TransactionResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static cloud.stately.db.TransactionResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static cloud.stately.db.TransactionResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static cloud.stately.db.TransactionResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static cloud.stately.db.TransactionResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static cloud.stately.db.TransactionResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static cloud.stately.db.TransactionResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(cloud.stately.db.TransactionResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * This is a streaming response, so the server may send several of them
   * </pre>
   *
   * Protobuf type {@code stately.db.TransactionResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:stately.db.TransactionResponse)
      cloud.stately.db.TransactionResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return cloud.stately.db.TransactionProto.internal_static_stately_db_TransactionResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return cloud.stately.db.TransactionProto.internal_static_stately_db_TransactionResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              cloud.stately.db.TransactionResponse.class, cloud.stately.db.TransactionResponse.Builder.class);
    }

    // Construct using cloud.stately.db.TransactionResponse.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      messageId_ = 0;
      if (getResultsBuilder_ != null) {
        getResultsBuilder_.clear();
      }
      if (putAckBuilder_ != null) {
        putAckBuilder_.clear();
      }
      if (listResultsBuilder_ != null) {
        listResultsBuilder_.clear();
      }
      if (finishedBuilder_ != null) {
        finishedBuilder_.clear();
      }
      resultCase_ = 0;
      result_ = null;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return cloud.stately.db.TransactionProto.internal_static_stately_db_TransactionResponse_descriptor;
    }

    @java.lang.Override
    public cloud.stately.db.TransactionResponse getDefaultInstanceForType() {
      return cloud.stately.db.TransactionResponse.getDefaultInstance();
    }

    @java.lang.Override
    public cloud.stately.db.TransactionResponse build() {
      cloud.stately.db.TransactionResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public cloud.stately.db.TransactionResponse buildPartial() {
      cloud.stately.db.TransactionResponse result = new cloud.stately.db.TransactionResponse(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      buildPartialOneofs(result);
      onBuilt();
      return result;
    }

    private void buildPartial0(cloud.stately.db.TransactionResponse result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.messageId_ = messageId_;
      }
    }

    private void buildPartialOneofs(cloud.stately.db.TransactionResponse result) {
      result.resultCase_ = resultCase_;
      result.result_ = this.result_;
      if (resultCase_ == 2 &&
          getResultsBuilder_ != null) {
        result.result_ = getResultsBuilder_.build();
      }
      if (resultCase_ == 3 &&
          putAckBuilder_ != null) {
        result.result_ = putAckBuilder_.build();
      }
      if (resultCase_ == 4 &&
          listResultsBuilder_ != null) {
        result.result_ = listResultsBuilder_.build();
      }
      if (resultCase_ == 5 &&
          finishedBuilder_ != null) {
        result.result_ = finishedBuilder_.build();
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof cloud.stately.db.TransactionResponse) {
        return mergeFrom((cloud.stately.db.TransactionResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(cloud.stately.db.TransactionResponse other) {
      if (other == cloud.stately.db.TransactionResponse.getDefaultInstance()) return this;
      if (other.getMessageId() != 0) {
        setMessageId(other.getMessageId());
      }
      switch (other.getResultCase()) {
        case GET_RESULTS: {
          mergeGetResults(other.getGetResults());
          break;
        }
        case PUT_ACK: {
          mergePutAck(other.getPutAck());
          break;
        }
        case LIST_RESULTS: {
          mergeListResults(other.getListResults());
          break;
        }
        case FINISHED: {
          mergeFinished(other.getFinished());
          break;
        }
        case RESULT_NOT_SET: {
          break;
        }
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              messageId_ = input.readUInt32();
              bitField0_ |= 0x00000001;
              break;
            } // case 8
            case 18: {
              input.readMessage(
                  internalGetGetResultsFieldBuilder().getBuilder(),
                  extensionRegistry);
              resultCase_ = 2;
              break;
            } // case 18
            case 26: {
              input.readMessage(
                  internalGetPutAckFieldBuilder().getBuilder(),
                  extensionRegistry);
              resultCase_ = 3;
              break;
            } // case 26
            case 34: {
              input.readMessage(
                  internalGetListResultsFieldBuilder().getBuilder(),
                  extensionRegistry);
              resultCase_ = 4;
              break;
            } // case 34
            case 42: {
              input.readMessage(
                  internalGetFinishedFieldBuilder().getBuilder(),
                  extensionRegistry);
              resultCase_ = 5;
              break;
            } // case 42
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int resultCase_ = 0;
    private java.lang.Object result_;
    public ResultCase
        getResultCase() {
      return ResultCase.forNumber(
          resultCase_);
    }

    public Builder clearResult() {
      resultCase_ = 0;
      result_ = null;
      onChanged();
      return this;
    }

    private int bitField0_;

    private int messageId_ ;
    /**
     * <pre>
     * message_id is the same as the message_id of the request that triggered this
     * response. This makes it easier to distinguish between multiple responses to
     * different requests..
     * </pre>
     *
     * <code>uint32 message_id = 1 [json_name = "messageId"];</code>
     * @return The messageId.
     */
    @java.lang.Override
    public int getMessageId() {
      return messageId_;
    }
    /**
     * <pre>
     * message_id is the same as the message_id of the request that triggered this
     * response. This makes it easier to distinguish between multiple responses to
     * different requests..
     * </pre>
     *
     * <code>uint32 message_id = 1 [json_name = "messageId"];</code>
     * @param value The messageId to set.
     * @return This builder for chaining.
     */
    public Builder setMessageId(int value) {

      messageId_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * message_id is the same as the message_id of the request that triggered this
     * response. This makes it easier to distinguish between multiple responses to
     * different requests..
     * </pre>
     *
     * <code>uint32 message_id = 1 [json_name = "messageId"];</code>
     * @return This builder for chaining.
     */
    public Builder clearMessageId() {
      bitField0_ = (bitField0_ & ~0x00000001);
      messageId_ = 0;
      onChanged();
      return this;
    }

    private com.google.protobuf.SingleFieldBuilder<
        cloud.stately.db.TransactionGetResponse, cloud.stately.db.TransactionGetResponse.Builder, cloud.stately.db.TransactionGetResponseOrBuilder> getResultsBuilder_;
    /**
     * <pre>
     * The server is responding to a GetItem request
     * </pre>
     *
     * <code>.stately.db.TransactionGetResponse get_results = 2 [json_name = "getResults"];</code>
     * @return Whether the getResults field is set.
     */
    @java.lang.Override
    public boolean hasGetResults() {
      return resultCase_ == 2;
    }
    /**
     * <pre>
     * The server is responding to a GetItem request
     * </pre>
     *
     * <code>.stately.db.TransactionGetResponse get_results = 2 [json_name = "getResults"];</code>
     * @return The getResults.
     */
    @java.lang.Override
    public cloud.stately.db.TransactionGetResponse getGetResults() {
      if (getResultsBuilder_ == null) {
        if (resultCase_ == 2) {
          return (cloud.stately.db.TransactionGetResponse) result_;
        }
        return cloud.stately.db.TransactionGetResponse.getDefaultInstance();
      } else {
        if (resultCase_ == 2) {
          return getResultsBuilder_.getMessage();
        }
        return cloud.stately.db.TransactionGetResponse.getDefaultInstance();
      }
    }
    /**
     * <pre>
     * The server is responding to a GetItem request
     * </pre>
     *
     * <code>.stately.db.TransactionGetResponse get_results = 2 [json_name = "getResults"];</code>
     */
    public Builder setGetResults(cloud.stately.db.TransactionGetResponse value) {
      if (getResultsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        result_ = value;
        onChanged();
      } else {
        getResultsBuilder_.setMessage(value);
      }
      resultCase_ = 2;
      return this;
    }
    /**
     * <pre>
     * The server is responding to a GetItem request
     * </pre>
     *
     * <code>.stately.db.TransactionGetResponse get_results = 2 [json_name = "getResults"];</code>
     */
    public Builder setGetResults(
        cloud.stately.db.TransactionGetResponse.Builder builderForValue) {
      if (getResultsBuilder_ == null) {
        result_ = builderForValue.build();
        onChanged();
      } else {
        getResultsBuilder_.setMessage(builderForValue.build());
      }
      resultCase_ = 2;
      return this;
    }
    /**
     * <pre>
     * The server is responding to a GetItem request
     * </pre>
     *
     * <code>.stately.db.TransactionGetResponse get_results = 2 [json_name = "getResults"];</code>
     */
    public Builder mergeGetResults(cloud.stately.db.TransactionGetResponse value) {
      if (getResultsBuilder_ == null) {
        if (resultCase_ == 2 &&
            result_ != cloud.stately.db.TransactionGetResponse.getDefaultInstance()) {
          result_ = cloud.stately.db.TransactionGetResponse.newBuilder((cloud.stately.db.TransactionGetResponse) result_)
              .mergeFrom(value).buildPartial();
        } else {
          result_ = value;
        }
        onChanged();
      } else {
        if (resultCase_ == 2) {
          getResultsBuilder_.mergeFrom(value);
        } else {
          getResultsBuilder_.setMessage(value);
        }
      }
      resultCase_ = 2;
      return this;
    }
    /**
     * <pre>
     * The server is responding to a GetItem request
     * </pre>
     *
     * <code>.stately.db.TransactionGetResponse get_results = 2 [json_name = "getResults"];</code>
     */
    public Builder clearGetResults() {
      if (getResultsBuilder_ == null) {
        if (resultCase_ == 2) {
          resultCase_ = 0;
          result_ = null;
          onChanged();
        }
      } else {
        if (resultCase_ == 2) {
          resultCase_ = 0;
          result_ = null;
        }
        getResultsBuilder_.clear();
      }
      return this;
    }
    /**
     * <pre>
     * The server is responding to a GetItem request
     * </pre>
     *
     * <code>.stately.db.TransactionGetResponse get_results = 2 [json_name = "getResults"];</code>
     */
    public cloud.stately.db.TransactionGetResponse.Builder getGetResultsBuilder() {
      return internalGetGetResultsFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * The server is responding to a GetItem request
     * </pre>
     *
     * <code>.stately.db.TransactionGetResponse get_results = 2 [json_name = "getResults"];</code>
     */
    @java.lang.Override
    public cloud.stately.db.TransactionGetResponseOrBuilder getGetResultsOrBuilder() {
      if ((resultCase_ == 2) && (getResultsBuilder_ != null)) {
        return getResultsBuilder_.getMessageOrBuilder();
      } else {
        if (resultCase_ == 2) {
          return (cloud.stately.db.TransactionGetResponse) result_;
        }
        return cloud.stately.db.TransactionGetResponse.getDefaultInstance();
      }
    }
    /**
     * <pre>
     * The server is responding to a GetItem request
     * </pre>
     *
     * <code>.stately.db.TransactionGetResponse get_results = 2 [json_name = "getResults"];</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        cloud.stately.db.TransactionGetResponse, cloud.stately.db.TransactionGetResponse.Builder, cloud.stately.db.TransactionGetResponseOrBuilder> 
        internalGetGetResultsFieldBuilder() {
      if (getResultsBuilder_ == null) {
        if (!(resultCase_ == 2)) {
          result_ = cloud.stately.db.TransactionGetResponse.getDefaultInstance();
        }
        getResultsBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            cloud.stately.db.TransactionGetResponse, cloud.stately.db.TransactionGetResponse.Builder, cloud.stately.db.TransactionGetResponseOrBuilder>(
                (cloud.stately.db.TransactionGetResponse) result_,
                getParentForChildren(),
                isClean());
        result_ = null;
      }
      resultCase_ = 2;
      onChanged();
      return getResultsBuilder_;
    }

    private com.google.protobuf.SingleFieldBuilder<
        cloud.stately.db.TransactionPutAck, cloud.stately.db.TransactionPutAck.Builder, cloud.stately.db.TransactionPutAckOrBuilder> putAckBuilder_;
    /**
     * <pre>
     * put_ack contains provisionally updated items from a put, including
     * tentative IDs (pending transaction commit).
     * </pre>
     *
     * <code>.stately.db.TransactionPutAck put_ack = 3 [json_name = "putAck"];</code>
     * @return Whether the putAck field is set.
     */
    @java.lang.Override
    public boolean hasPutAck() {
      return resultCase_ == 3;
    }
    /**
     * <pre>
     * put_ack contains provisionally updated items from a put, including
     * tentative IDs (pending transaction commit).
     * </pre>
     *
     * <code>.stately.db.TransactionPutAck put_ack = 3 [json_name = "putAck"];</code>
     * @return The putAck.
     */
    @java.lang.Override
    public cloud.stately.db.TransactionPutAck getPutAck() {
      if (putAckBuilder_ == null) {
        if (resultCase_ == 3) {
          return (cloud.stately.db.TransactionPutAck) result_;
        }
        return cloud.stately.db.TransactionPutAck.getDefaultInstance();
      } else {
        if (resultCase_ == 3) {
          return putAckBuilder_.getMessage();
        }
        return cloud.stately.db.TransactionPutAck.getDefaultInstance();
      }
    }
    /**
     * <pre>
     * put_ack contains provisionally updated items from a put, including
     * tentative IDs (pending transaction commit).
     * </pre>
     *
     * <code>.stately.db.TransactionPutAck put_ack = 3 [json_name = "putAck"];</code>
     */
    public Builder setPutAck(cloud.stately.db.TransactionPutAck value) {
      if (putAckBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        result_ = value;
        onChanged();
      } else {
        putAckBuilder_.setMessage(value);
      }
      resultCase_ = 3;
      return this;
    }
    /**
     * <pre>
     * put_ack contains provisionally updated items from a put, including
     * tentative IDs (pending transaction commit).
     * </pre>
     *
     * <code>.stately.db.TransactionPutAck put_ack = 3 [json_name = "putAck"];</code>
     */
    public Builder setPutAck(
        cloud.stately.db.TransactionPutAck.Builder builderForValue) {
      if (putAckBuilder_ == null) {
        result_ = builderForValue.build();
        onChanged();
      } else {
        putAckBuilder_.setMessage(builderForValue.build());
      }
      resultCase_ = 3;
      return this;
    }
    /**
     * <pre>
     * put_ack contains provisionally updated items from a put, including
     * tentative IDs (pending transaction commit).
     * </pre>
     *
     * <code>.stately.db.TransactionPutAck put_ack = 3 [json_name = "putAck"];</code>
     */
    public Builder mergePutAck(cloud.stately.db.TransactionPutAck value) {
      if (putAckBuilder_ == null) {
        if (resultCase_ == 3 &&
            result_ != cloud.stately.db.TransactionPutAck.getDefaultInstance()) {
          result_ = cloud.stately.db.TransactionPutAck.newBuilder((cloud.stately.db.TransactionPutAck) result_)
              .mergeFrom(value).buildPartial();
        } else {
          result_ = value;
        }
        onChanged();
      } else {
        if (resultCase_ == 3) {
          putAckBuilder_.mergeFrom(value);
        } else {
          putAckBuilder_.setMessage(value);
        }
      }
      resultCase_ = 3;
      return this;
    }
    /**
     * <pre>
     * put_ack contains provisionally updated items from a put, including
     * tentative IDs (pending transaction commit).
     * </pre>
     *
     * <code>.stately.db.TransactionPutAck put_ack = 3 [json_name = "putAck"];</code>
     */
    public Builder clearPutAck() {
      if (putAckBuilder_ == null) {
        if (resultCase_ == 3) {
          resultCase_ = 0;
          result_ = null;
          onChanged();
        }
      } else {
        if (resultCase_ == 3) {
          resultCase_ = 0;
          result_ = null;
        }
        putAckBuilder_.clear();
      }
      return this;
    }
    /**
     * <pre>
     * put_ack contains provisionally updated items from a put, including
     * tentative IDs (pending transaction commit).
     * </pre>
     *
     * <code>.stately.db.TransactionPutAck put_ack = 3 [json_name = "putAck"];</code>
     */
    public cloud.stately.db.TransactionPutAck.Builder getPutAckBuilder() {
      return internalGetPutAckFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * put_ack contains provisionally updated items from a put, including
     * tentative IDs (pending transaction commit).
     * </pre>
     *
     * <code>.stately.db.TransactionPutAck put_ack = 3 [json_name = "putAck"];</code>
     */
    @java.lang.Override
    public cloud.stately.db.TransactionPutAckOrBuilder getPutAckOrBuilder() {
      if ((resultCase_ == 3) && (putAckBuilder_ != null)) {
        return putAckBuilder_.getMessageOrBuilder();
      } else {
        if (resultCase_ == 3) {
          return (cloud.stately.db.TransactionPutAck) result_;
        }
        return cloud.stately.db.TransactionPutAck.getDefaultInstance();
      }
    }
    /**
     * <pre>
     * put_ack contains provisionally updated items from a put, including
     * tentative IDs (pending transaction commit).
     * </pre>
     *
     * <code>.stately.db.TransactionPutAck put_ack = 3 [json_name = "putAck"];</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        cloud.stately.db.TransactionPutAck, cloud.stately.db.TransactionPutAck.Builder, cloud.stately.db.TransactionPutAckOrBuilder> 
        internalGetPutAckFieldBuilder() {
      if (putAckBuilder_ == null) {
        if (!(resultCase_ == 3)) {
          result_ = cloud.stately.db.TransactionPutAck.getDefaultInstance();
        }
        putAckBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            cloud.stately.db.TransactionPutAck, cloud.stately.db.TransactionPutAck.Builder, cloud.stately.db.TransactionPutAckOrBuilder>(
                (cloud.stately.db.TransactionPutAck) result_,
                getParentForChildren(),
                isClean());
        result_ = null;
      }
      resultCase_ = 3;
      onChanged();
      return putAckBuilder_;
    }

    private com.google.protobuf.SingleFieldBuilder<
        cloud.stately.db.TransactionListResponse, cloud.stately.db.TransactionListResponse.Builder, cloud.stately.db.TransactionListResponseOrBuilder> listResultsBuilder_;
    /**
     * <pre>
     * list_results is the result of a list request.
     * </pre>
     *
     * <code>.stately.db.TransactionListResponse list_results = 4 [json_name = "listResults"];</code>
     * @return Whether the listResults field is set.
     */
    @java.lang.Override
    public boolean hasListResults() {
      return resultCase_ == 4;
    }
    /**
     * <pre>
     * list_results is the result of a list request.
     * </pre>
     *
     * <code>.stately.db.TransactionListResponse list_results = 4 [json_name = "listResults"];</code>
     * @return The listResults.
     */
    @java.lang.Override
    public cloud.stately.db.TransactionListResponse getListResults() {
      if (listResultsBuilder_ == null) {
        if (resultCase_ == 4) {
          return (cloud.stately.db.TransactionListResponse) result_;
        }
        return cloud.stately.db.TransactionListResponse.getDefaultInstance();
      } else {
        if (resultCase_ == 4) {
          return listResultsBuilder_.getMessage();
        }
        return cloud.stately.db.TransactionListResponse.getDefaultInstance();
      }
    }
    /**
     * <pre>
     * list_results is the result of a list request.
     * </pre>
     *
     * <code>.stately.db.TransactionListResponse list_results = 4 [json_name = "listResults"];</code>
     */
    public Builder setListResults(cloud.stately.db.TransactionListResponse value) {
      if (listResultsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        result_ = value;
        onChanged();
      } else {
        listResultsBuilder_.setMessage(value);
      }
      resultCase_ = 4;
      return this;
    }
    /**
     * <pre>
     * list_results is the result of a list request.
     * </pre>
     *
     * <code>.stately.db.TransactionListResponse list_results = 4 [json_name = "listResults"];</code>
     */
    public Builder setListResults(
        cloud.stately.db.TransactionListResponse.Builder builderForValue) {
      if (listResultsBuilder_ == null) {
        result_ = builderForValue.build();
        onChanged();
      } else {
        listResultsBuilder_.setMessage(builderForValue.build());
      }
      resultCase_ = 4;
      return this;
    }
    /**
     * <pre>
     * list_results is the result of a list request.
     * </pre>
     *
     * <code>.stately.db.TransactionListResponse list_results = 4 [json_name = "listResults"];</code>
     */
    public Builder mergeListResults(cloud.stately.db.TransactionListResponse value) {
      if (listResultsBuilder_ == null) {
        if (resultCase_ == 4 &&
            result_ != cloud.stately.db.TransactionListResponse.getDefaultInstance()) {
          result_ = cloud.stately.db.TransactionListResponse.newBuilder((cloud.stately.db.TransactionListResponse) result_)
              .mergeFrom(value).buildPartial();
        } else {
          result_ = value;
        }
        onChanged();
      } else {
        if (resultCase_ == 4) {
          listResultsBuilder_.mergeFrom(value);
        } else {
          listResultsBuilder_.setMessage(value);
        }
      }
      resultCase_ = 4;
      return this;
    }
    /**
     * <pre>
     * list_results is the result of a list request.
     * </pre>
     *
     * <code>.stately.db.TransactionListResponse list_results = 4 [json_name = "listResults"];</code>
     */
    public Builder clearListResults() {
      if (listResultsBuilder_ == null) {
        if (resultCase_ == 4) {
          resultCase_ = 0;
          result_ = null;
          onChanged();
        }
      } else {
        if (resultCase_ == 4) {
          resultCase_ = 0;
          result_ = null;
        }
        listResultsBuilder_.clear();
      }
      return this;
    }
    /**
     * <pre>
     * list_results is the result of a list request.
     * </pre>
     *
     * <code>.stately.db.TransactionListResponse list_results = 4 [json_name = "listResults"];</code>
     */
    public cloud.stately.db.TransactionListResponse.Builder getListResultsBuilder() {
      return internalGetListResultsFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * list_results is the result of a list request.
     * </pre>
     *
     * <code>.stately.db.TransactionListResponse list_results = 4 [json_name = "listResults"];</code>
     */
    @java.lang.Override
    public cloud.stately.db.TransactionListResponseOrBuilder getListResultsOrBuilder() {
      if ((resultCase_ == 4) && (listResultsBuilder_ != null)) {
        return listResultsBuilder_.getMessageOrBuilder();
      } else {
        if (resultCase_ == 4) {
          return (cloud.stately.db.TransactionListResponse) result_;
        }
        return cloud.stately.db.TransactionListResponse.getDefaultInstance();
      }
    }
    /**
     * <pre>
     * list_results is the result of a list request.
     * </pre>
     *
     * <code>.stately.db.TransactionListResponse list_results = 4 [json_name = "listResults"];</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        cloud.stately.db.TransactionListResponse, cloud.stately.db.TransactionListResponse.Builder, cloud.stately.db.TransactionListResponseOrBuilder> 
        internalGetListResultsFieldBuilder() {
      if (listResultsBuilder_ == null) {
        if (!(resultCase_ == 4)) {
          result_ = cloud.stately.db.TransactionListResponse.getDefaultInstance();
        }
        listResultsBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            cloud.stately.db.TransactionListResponse, cloud.stately.db.TransactionListResponse.Builder, cloud.stately.db.TransactionListResponseOrBuilder>(
                (cloud.stately.db.TransactionListResponse) result_,
                getParentForChildren(),
                isClean());
        result_ = null;
      }
      resultCase_ = 4;
      onChanged();
      return listResultsBuilder_;
    }

    private com.google.protobuf.SingleFieldBuilder<
        cloud.stately.db.TransactionFinished, cloud.stately.db.TransactionFinished.Builder, cloud.stately.db.TransactionFinishedOrBuilder> finishedBuilder_;
    /**
     * <pre>
     * Final information about the transaction, regardless of whether it was committed or aborted.
     * </pre>
     *
     * <code>.stately.db.TransactionFinished finished = 5 [json_name = "finished"];</code>
     * @return Whether the finished field is set.
     */
    @java.lang.Override
    public boolean hasFinished() {
      return resultCase_ == 5;
    }
    /**
     * <pre>
     * Final information about the transaction, regardless of whether it was committed or aborted.
     * </pre>
     *
     * <code>.stately.db.TransactionFinished finished = 5 [json_name = "finished"];</code>
     * @return The finished.
     */
    @java.lang.Override
    public cloud.stately.db.TransactionFinished getFinished() {
      if (finishedBuilder_ == null) {
        if (resultCase_ == 5) {
          return (cloud.stately.db.TransactionFinished) result_;
        }
        return cloud.stately.db.TransactionFinished.getDefaultInstance();
      } else {
        if (resultCase_ == 5) {
          return finishedBuilder_.getMessage();
        }
        return cloud.stately.db.TransactionFinished.getDefaultInstance();
      }
    }
    /**
     * <pre>
     * Final information about the transaction, regardless of whether it was committed or aborted.
     * </pre>
     *
     * <code>.stately.db.TransactionFinished finished = 5 [json_name = "finished"];</code>
     */
    public Builder setFinished(cloud.stately.db.TransactionFinished value) {
      if (finishedBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        result_ = value;
        onChanged();
      } else {
        finishedBuilder_.setMessage(value);
      }
      resultCase_ = 5;
      return this;
    }
    /**
     * <pre>
     * Final information about the transaction, regardless of whether it was committed or aborted.
     * </pre>
     *
     * <code>.stately.db.TransactionFinished finished = 5 [json_name = "finished"];</code>
     */
    public Builder setFinished(
        cloud.stately.db.TransactionFinished.Builder builderForValue) {
      if (finishedBuilder_ == null) {
        result_ = builderForValue.build();
        onChanged();
      } else {
        finishedBuilder_.setMessage(builderForValue.build());
      }
      resultCase_ = 5;
      return this;
    }
    /**
     * <pre>
     * Final information about the transaction, regardless of whether it was committed or aborted.
     * </pre>
     *
     * <code>.stately.db.TransactionFinished finished = 5 [json_name = "finished"];</code>
     */
    public Builder mergeFinished(cloud.stately.db.TransactionFinished value) {
      if (finishedBuilder_ == null) {
        if (resultCase_ == 5 &&
            result_ != cloud.stately.db.TransactionFinished.getDefaultInstance()) {
          result_ = cloud.stately.db.TransactionFinished.newBuilder((cloud.stately.db.TransactionFinished) result_)
              .mergeFrom(value).buildPartial();
        } else {
          result_ = value;
        }
        onChanged();
      } else {
        if (resultCase_ == 5) {
          finishedBuilder_.mergeFrom(value);
        } else {
          finishedBuilder_.setMessage(value);
        }
      }
      resultCase_ = 5;
      return this;
    }
    /**
     * <pre>
     * Final information about the transaction, regardless of whether it was committed or aborted.
     * </pre>
     *
     * <code>.stately.db.TransactionFinished finished = 5 [json_name = "finished"];</code>
     */
    public Builder clearFinished() {
      if (finishedBuilder_ == null) {
        if (resultCase_ == 5) {
          resultCase_ = 0;
          result_ = null;
          onChanged();
        }
      } else {
        if (resultCase_ == 5) {
          resultCase_ = 0;
          result_ = null;
        }
        finishedBuilder_.clear();
      }
      return this;
    }
    /**
     * <pre>
     * Final information about the transaction, regardless of whether it was committed or aborted.
     * </pre>
     *
     * <code>.stately.db.TransactionFinished finished = 5 [json_name = "finished"];</code>
     */
    public cloud.stately.db.TransactionFinished.Builder getFinishedBuilder() {
      return internalGetFinishedFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * Final information about the transaction, regardless of whether it was committed or aborted.
     * </pre>
     *
     * <code>.stately.db.TransactionFinished finished = 5 [json_name = "finished"];</code>
     */
    @java.lang.Override
    public cloud.stately.db.TransactionFinishedOrBuilder getFinishedOrBuilder() {
      if ((resultCase_ == 5) && (finishedBuilder_ != null)) {
        return finishedBuilder_.getMessageOrBuilder();
      } else {
        if (resultCase_ == 5) {
          return (cloud.stately.db.TransactionFinished) result_;
        }
        return cloud.stately.db.TransactionFinished.getDefaultInstance();
      }
    }
    /**
     * <pre>
     * Final information about the transaction, regardless of whether it was committed or aborted.
     * </pre>
     *
     * <code>.stately.db.TransactionFinished finished = 5 [json_name = "finished"];</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        cloud.stately.db.TransactionFinished, cloud.stately.db.TransactionFinished.Builder, cloud.stately.db.TransactionFinishedOrBuilder> 
        internalGetFinishedFieldBuilder() {
      if (finishedBuilder_ == null) {
        if (!(resultCase_ == 5)) {
          result_ = cloud.stately.db.TransactionFinished.getDefaultInstance();
        }
        finishedBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            cloud.stately.db.TransactionFinished, cloud.stately.db.TransactionFinished.Builder, cloud.stately.db.TransactionFinishedOrBuilder>(
                (cloud.stately.db.TransactionFinished) result_,
                getParentForChildren(),
                isClean());
        result_ = null;
      }
      resultCase_ = 5;
      onChanged();
      return finishedBuilder_;
    }

    // @@protoc_insertion_point(builder_scope:stately.db.TransactionResponse)
  }

  // @@protoc_insertion_point(class_scope:stately.db.TransactionResponse)
  private static final cloud.stately.db.TransactionResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new cloud.stately.db.TransactionResponse();
  }

  public static cloud.stately.db.TransactionResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<TransactionResponse>
      PARSER = new com.google.protobuf.AbstractParser<TransactionResponse>() {
    @java.lang.Override
    public TransactionResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<TransactionResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<TransactionResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public cloud.stately.db.TransactionResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

