// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: auth/get_auth_token.proto
// Protobuf Java Version: 4.32.0

package cloud.stately.auth;

@com.google.protobuf.Generated
public final class GetAuthTokenProto {
  private GetAuthTokenProto() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 32,
      /* patch= */ 0,
      /* suffix= */ "",
      GetAuthTokenProto.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_stately_auth_GetAuthTokenRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_stately_auth_GetAuthTokenRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_stately_auth_GetAuthTokenResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_stately_auth_GetAuthTokenResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\031auth/get_auth_token.proto\022\014stately.aut" +
      "h\"B\n\023GetAuthTokenRequest\022\037\n\naccess_key\030\001" +
      " \001(\tH\000R\taccessKeyB\n\n\010identity\"W\n\024GetAuth" +
      "TokenResponse\022\035\n\nauth_token\030\001 \001(\tR\tauthT" +
      "oken\022 \n\014expires_in_s\030\002 \001(\004R\nexpiresInSBx" +
      "\n\022cloud.stately.authB\021GetAuthTokenProtoP" +
      "\001\242\002\003SAX\252\002\014Stately.Auth\312\002\014Stately\\Auth\342\002\030" +
      "Stately\\Auth\\GPBMetadata\352\002\rStately::Auth" +
      "b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_stately_auth_GetAuthTokenRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_stately_auth_GetAuthTokenRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_stately_auth_GetAuthTokenRequest_descriptor,
        new java.lang.String[] { "AccessKey", "Identity", });
    internal_static_stately_auth_GetAuthTokenResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_stately_auth_GetAuthTokenResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_stately_auth_GetAuthTokenResponse_descriptor,
        new java.lang.String[] { "AuthToken", "ExpiresInS", });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
