// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: auth/get_auth_token.proto
// Protobuf Java Version: 4.32.0

package cloud.stately.auth;

@com.google.protobuf.Generated
public interface GetAuthTokenResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:stately.auth.GetAuthTokenResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * auth_token is the token that can be used to authenticate requests to the
   * StatelyDB API.
   * </pre>
   *
   * <code>string auth_token = 1 [json_name = "authToken"];</code>
   * @return The authToken.
   */
  java.lang.String getAuthToken();
  /**
   * <pre>
   * auth_token is the token that can be used to authenticate requests to the
   * StatelyDB API.
   * </pre>
   *
   * <code>string auth_token = 1 [json_name = "authToken"];</code>
   * @return The bytes for authToken.
   */
  com.google.protobuf.ByteString
      getAuthTokenBytes();

  /**
   * <pre>
   * expires_in_s is the duration in seconds that this access token is
   * valid. After this time has passed, the access token will be rejected - you
   * should refresh the token via another call to GetAuthToken before this
   * happens.
   * </pre>
   *
   * <code>uint64 expires_in_s = 2 [json_name = "expiresInS"];</code>
   * @return The expiresInS.
   */
  long getExpiresInS();
}
