// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: errors/error_details.proto
// Protobuf Java Version: 4.32.0

package cloud.stately.errors;

/**
 * <pre>
 * StatelyErrorDetails is a message containing detailed error information.
 * This is returned from the Stately API via Connect error details:
 * https://connectrpc.com/docs/go/errors#error-details
 * Note: As a customer, you should not need to handle this message directly unless writing
 * a custom low-level SDK. Instead, language-specific SDKs will provide a more user-friendly
 * error object that wraps this message.
 * </pre>
 *
 * Protobuf type {@code stately.errors.StatelyErrorDetails}
 */
@com.google.protobuf.Generated
public final class StatelyErrorDetails extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:stately.errors.StatelyErrorDetails)
    StatelyErrorDetailsOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 32,
      /* patch= */ 0,
      /* suffix= */ "",
      StatelyErrorDetails.class.getName());
  }
  // Use StatelyErrorDetails.newBuilder() to construct.
  private StatelyErrorDetails(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private StatelyErrorDetails() {
    statelyCode_ = "";
    message_ = "";
    upstreamCause_ = "";
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return cloud.stately.errors.ErrorDetailsProto.internal_static_stately_errors_StatelyErrorDetails_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return cloud.stately.errors.ErrorDetailsProto.internal_static_stately_errors_StatelyErrorDetails_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            cloud.stately.errors.StatelyErrorDetails.class, cloud.stately.errors.StatelyErrorDetails.Builder.class);
  }

  public static final int STATELY_CODE_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object statelyCode_ = "";
  /**
   * <pre>
   * stately_code is the error code that was returned by the Stately API.
   * The full list of codes is available at https://docs.stately.cloud/api/error-codes/
   * and documentation on a specific code can be found at https://docs.stately.cloud/api/error-codes/#{stately_code}
   * </pre>
   *
   * <code>string stately_code = 1 [json_name = "statelyCode"];</code>
   * @return The statelyCode.
   */
  @java.lang.Override
  public java.lang.String getStatelyCode() {
    java.lang.Object ref = statelyCode_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      statelyCode_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * stately_code is the error code that was returned by the Stately API.
   * The full list of codes is available at https://docs.stately.cloud/api/error-codes/
   * and documentation on a specific code can be found at https://docs.stately.cloud/api/error-codes/#{stately_code}
   * </pre>
   *
   * <code>string stately_code = 1 [json_name = "statelyCode"];</code>
   * @return The bytes for statelyCode.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getStatelyCodeBytes() {
    java.lang.Object ref = statelyCode_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      statelyCode_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int MESSAGE_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private volatile java.lang.Object message_ = "";
  /**
   * <pre>
   * message is a human-readable error message that can be displayed to the user that
   * provides more context about the error.
   * </pre>
   *
   * <code>string message = 2 [json_name = "message"];</code>
   * @return The message.
   */
  @java.lang.Override
  public java.lang.String getMessage() {
    java.lang.Object ref = message_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      message_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * message is a human-readable error message that can be displayed to the user that
   * provides more context about the error.
   * </pre>
   *
   * <code>string message = 2 [json_name = "message"];</code>
   * @return The bytes for message.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getMessageBytes() {
    java.lang.Object ref = message_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      message_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int UPSTREAM_CAUSE_FIELD_NUMBER = 3;
  @SuppressWarnings("serial")
  private volatile java.lang.Object upstreamCause_ = "";
  /**
   * <pre>
   * upstream_cause is additional information about the error that can be used to help debug the error,
   * This field will only optionally be supplied by the Stately API.
   * Note: This may row over as the error is passed through multiple services.
   * </pre>
   *
   * <code>string upstream_cause = 3 [json_name = "upstreamCause"];</code>
   * @return The upstreamCause.
   */
  @java.lang.Override
  public java.lang.String getUpstreamCause() {
    java.lang.Object ref = upstreamCause_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      upstreamCause_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * upstream_cause is additional information about the error that can be used to help debug the error,
   * This field will only optionally be supplied by the Stately API.
   * Note: This may row over as the error is passed through multiple services.
   * </pre>
   *
   * <code>string upstream_cause = 3 [json_name = "upstreamCause"];</code>
   * @return The bytes for upstreamCause.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getUpstreamCauseBytes() {
    java.lang.Object ref = upstreamCause_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      upstreamCause_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int CODE_FIELD_NUMBER = 4;
  private int code_ = 0;
  /**
   * <pre>
   * The Connect/gRPC code associated with this error. This generally isn't set,
   * because the overall API response has an error code. But this can be used in
   * the case that we're returning multiple different errors, or communicating
   * errors across non-Connect APIs.
   * </pre>
   *
   * <code>uint32 code = 4 [json_name = "code"];</code>
   * @return The code.
   */
  @java.lang.Override
  public int getCode() {
    return code_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(statelyCode_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 1, statelyCode_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(message_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 2, message_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(upstreamCause_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 3, upstreamCause_);
    }
    if (code_ != 0) {
      output.writeUInt32(4, code_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(statelyCode_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(1, statelyCode_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(message_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(2, message_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(upstreamCause_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(3, upstreamCause_);
    }
    if (code_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt32Size(4, code_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof cloud.stately.errors.StatelyErrorDetails)) {
      return super.equals(obj);
    }
    cloud.stately.errors.StatelyErrorDetails other = (cloud.stately.errors.StatelyErrorDetails) obj;

    if (!getStatelyCode()
        .equals(other.getStatelyCode())) return false;
    if (!getMessage()
        .equals(other.getMessage())) return false;
    if (!getUpstreamCause()
        .equals(other.getUpstreamCause())) return false;
    if (getCode()
        != other.getCode()) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + STATELY_CODE_FIELD_NUMBER;
    hash = (53 * hash) + getStatelyCode().hashCode();
    hash = (37 * hash) + MESSAGE_FIELD_NUMBER;
    hash = (53 * hash) + getMessage().hashCode();
    hash = (37 * hash) + UPSTREAM_CAUSE_FIELD_NUMBER;
    hash = (53 * hash) + getUpstreamCause().hashCode();
    hash = (37 * hash) + CODE_FIELD_NUMBER;
    hash = (53 * hash) + getCode();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static cloud.stately.errors.StatelyErrorDetails parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static cloud.stately.errors.StatelyErrorDetails parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static cloud.stately.errors.StatelyErrorDetails parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static cloud.stately.errors.StatelyErrorDetails parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static cloud.stately.errors.StatelyErrorDetails parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static cloud.stately.errors.StatelyErrorDetails parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static cloud.stately.errors.StatelyErrorDetails parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static cloud.stately.errors.StatelyErrorDetails parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static cloud.stately.errors.StatelyErrorDetails parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static cloud.stately.errors.StatelyErrorDetails parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static cloud.stately.errors.StatelyErrorDetails parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static cloud.stately.errors.StatelyErrorDetails parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(cloud.stately.errors.StatelyErrorDetails prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * StatelyErrorDetails is a message containing detailed error information.
   * This is returned from the Stately API via Connect error details:
   * https://connectrpc.com/docs/go/errors#error-details
   * Note: As a customer, you should not need to handle this message directly unless writing
   * a custom low-level SDK. Instead, language-specific SDKs will provide a more user-friendly
   * error object that wraps this message.
   * </pre>
   *
   * Protobuf type {@code stately.errors.StatelyErrorDetails}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:stately.errors.StatelyErrorDetails)
      cloud.stately.errors.StatelyErrorDetailsOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return cloud.stately.errors.ErrorDetailsProto.internal_static_stately_errors_StatelyErrorDetails_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return cloud.stately.errors.ErrorDetailsProto.internal_static_stately_errors_StatelyErrorDetails_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              cloud.stately.errors.StatelyErrorDetails.class, cloud.stately.errors.StatelyErrorDetails.Builder.class);
    }

    // Construct using cloud.stately.errors.StatelyErrorDetails.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      statelyCode_ = "";
      message_ = "";
      upstreamCause_ = "";
      code_ = 0;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return cloud.stately.errors.ErrorDetailsProto.internal_static_stately_errors_StatelyErrorDetails_descriptor;
    }

    @java.lang.Override
    public cloud.stately.errors.StatelyErrorDetails getDefaultInstanceForType() {
      return cloud.stately.errors.StatelyErrorDetails.getDefaultInstance();
    }

    @java.lang.Override
    public cloud.stately.errors.StatelyErrorDetails build() {
      cloud.stately.errors.StatelyErrorDetails result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public cloud.stately.errors.StatelyErrorDetails buildPartial() {
      cloud.stately.errors.StatelyErrorDetails result = new cloud.stately.errors.StatelyErrorDetails(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(cloud.stately.errors.StatelyErrorDetails result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.statelyCode_ = statelyCode_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.message_ = message_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.upstreamCause_ = upstreamCause_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.code_ = code_;
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof cloud.stately.errors.StatelyErrorDetails) {
        return mergeFrom((cloud.stately.errors.StatelyErrorDetails)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(cloud.stately.errors.StatelyErrorDetails other) {
      if (other == cloud.stately.errors.StatelyErrorDetails.getDefaultInstance()) return this;
      if (!other.getStatelyCode().isEmpty()) {
        statelyCode_ = other.statelyCode_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (!other.getMessage().isEmpty()) {
        message_ = other.message_;
        bitField0_ |= 0x00000002;
        onChanged();
      }
      if (!other.getUpstreamCause().isEmpty()) {
        upstreamCause_ = other.upstreamCause_;
        bitField0_ |= 0x00000004;
        onChanged();
      }
      if (other.getCode() != 0) {
        setCode(other.getCode());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              statelyCode_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              message_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 26: {
              upstreamCause_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000004;
              break;
            } // case 26
            case 32: {
              code_ = input.readUInt32();
              bitField0_ |= 0x00000008;
              break;
            } // case 32
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object statelyCode_ = "";
    /**
     * <pre>
     * stately_code is the error code that was returned by the Stately API.
     * The full list of codes is available at https://docs.stately.cloud/api/error-codes/
     * and documentation on a specific code can be found at https://docs.stately.cloud/api/error-codes/#{stately_code}
     * </pre>
     *
     * <code>string stately_code = 1 [json_name = "statelyCode"];</code>
     * @return The statelyCode.
     */
    public java.lang.String getStatelyCode() {
      java.lang.Object ref = statelyCode_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        statelyCode_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * stately_code is the error code that was returned by the Stately API.
     * The full list of codes is available at https://docs.stately.cloud/api/error-codes/
     * and documentation on a specific code can be found at https://docs.stately.cloud/api/error-codes/#{stately_code}
     * </pre>
     *
     * <code>string stately_code = 1 [json_name = "statelyCode"];</code>
     * @return The bytes for statelyCode.
     */
    public com.google.protobuf.ByteString
        getStatelyCodeBytes() {
      java.lang.Object ref = statelyCode_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        statelyCode_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * stately_code is the error code that was returned by the Stately API.
     * The full list of codes is available at https://docs.stately.cloud/api/error-codes/
     * and documentation on a specific code can be found at https://docs.stately.cloud/api/error-codes/#{stately_code}
     * </pre>
     *
     * <code>string stately_code = 1 [json_name = "statelyCode"];</code>
     * @param value The statelyCode to set.
     * @return This builder for chaining.
     */
    public Builder setStatelyCode(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      statelyCode_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * stately_code is the error code that was returned by the Stately API.
     * The full list of codes is available at https://docs.stately.cloud/api/error-codes/
     * and documentation on a specific code can be found at https://docs.stately.cloud/api/error-codes/#{stately_code}
     * </pre>
     *
     * <code>string stately_code = 1 [json_name = "statelyCode"];</code>
     * @return This builder for chaining.
     */
    public Builder clearStatelyCode() {
      statelyCode_ = getDefaultInstance().getStatelyCode();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * stately_code is the error code that was returned by the Stately API.
     * The full list of codes is available at https://docs.stately.cloud/api/error-codes/
     * and documentation on a specific code can be found at https://docs.stately.cloud/api/error-codes/#{stately_code}
     * </pre>
     *
     * <code>string stately_code = 1 [json_name = "statelyCode"];</code>
     * @param value The bytes for statelyCode to set.
     * @return This builder for chaining.
     */
    public Builder setStatelyCodeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      statelyCode_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private java.lang.Object message_ = "";
    /**
     * <pre>
     * message is a human-readable error message that can be displayed to the user that
     * provides more context about the error.
     * </pre>
     *
     * <code>string message = 2 [json_name = "message"];</code>
     * @return The message.
     */
    public java.lang.String getMessage() {
      java.lang.Object ref = message_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        message_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * message is a human-readable error message that can be displayed to the user that
     * provides more context about the error.
     * </pre>
     *
     * <code>string message = 2 [json_name = "message"];</code>
     * @return The bytes for message.
     */
    public com.google.protobuf.ByteString
        getMessageBytes() {
      java.lang.Object ref = message_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        message_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * message is a human-readable error message that can be displayed to the user that
     * provides more context about the error.
     * </pre>
     *
     * <code>string message = 2 [json_name = "message"];</code>
     * @param value The message to set.
     * @return This builder for chaining.
     */
    public Builder setMessage(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      message_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * message is a human-readable error message that can be displayed to the user that
     * provides more context about the error.
     * </pre>
     *
     * <code>string message = 2 [json_name = "message"];</code>
     * @return This builder for chaining.
     */
    public Builder clearMessage() {
      message_ = getDefaultInstance().getMessage();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * message is a human-readable error message that can be displayed to the user that
     * provides more context about the error.
     * </pre>
     *
     * <code>string message = 2 [json_name = "message"];</code>
     * @param value The bytes for message to set.
     * @return This builder for chaining.
     */
    public Builder setMessageBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      message_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }

    private java.lang.Object upstreamCause_ = "";
    /**
     * <pre>
     * upstream_cause is additional information about the error that can be used to help debug the error,
     * This field will only optionally be supplied by the Stately API.
     * Note: This may row over as the error is passed through multiple services.
     * </pre>
     *
     * <code>string upstream_cause = 3 [json_name = "upstreamCause"];</code>
     * @return The upstreamCause.
     */
    public java.lang.String getUpstreamCause() {
      java.lang.Object ref = upstreamCause_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        upstreamCause_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * upstream_cause is additional information about the error that can be used to help debug the error,
     * This field will only optionally be supplied by the Stately API.
     * Note: This may row over as the error is passed through multiple services.
     * </pre>
     *
     * <code>string upstream_cause = 3 [json_name = "upstreamCause"];</code>
     * @return The bytes for upstreamCause.
     */
    public com.google.protobuf.ByteString
        getUpstreamCauseBytes() {
      java.lang.Object ref = upstreamCause_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        upstreamCause_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * upstream_cause is additional information about the error that can be used to help debug the error,
     * This field will only optionally be supplied by the Stately API.
     * Note: This may row over as the error is passed through multiple services.
     * </pre>
     *
     * <code>string upstream_cause = 3 [json_name = "upstreamCause"];</code>
     * @param value The upstreamCause to set.
     * @return This builder for chaining.
     */
    public Builder setUpstreamCause(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      upstreamCause_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * upstream_cause is additional information about the error that can be used to help debug the error,
     * This field will only optionally be supplied by the Stately API.
     * Note: This may row over as the error is passed through multiple services.
     * </pre>
     *
     * <code>string upstream_cause = 3 [json_name = "upstreamCause"];</code>
     * @return This builder for chaining.
     */
    public Builder clearUpstreamCause() {
      upstreamCause_ = getDefaultInstance().getUpstreamCause();
      bitField0_ = (bitField0_ & ~0x00000004);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * upstream_cause is additional information about the error that can be used to help debug the error,
     * This field will only optionally be supplied by the Stately API.
     * Note: This may row over as the error is passed through multiple services.
     * </pre>
     *
     * <code>string upstream_cause = 3 [json_name = "upstreamCause"];</code>
     * @param value The bytes for upstreamCause to set.
     * @return This builder for chaining.
     */
    public Builder setUpstreamCauseBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      upstreamCause_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }

    private int code_ ;
    /**
     * <pre>
     * The Connect/gRPC code associated with this error. This generally isn't set,
     * because the overall API response has an error code. But this can be used in
     * the case that we're returning multiple different errors, or communicating
     * errors across non-Connect APIs.
     * </pre>
     *
     * <code>uint32 code = 4 [json_name = "code"];</code>
     * @return The code.
     */
    @java.lang.Override
    public int getCode() {
      return code_;
    }
    /**
     * <pre>
     * The Connect/gRPC code associated with this error. This generally isn't set,
     * because the overall API response has an error code. But this can be used in
     * the case that we're returning multiple different errors, or communicating
     * errors across non-Connect APIs.
     * </pre>
     *
     * <code>uint32 code = 4 [json_name = "code"];</code>
     * @param value The code to set.
     * @return This builder for chaining.
     */
    public Builder setCode(int value) {

      code_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The Connect/gRPC code associated with this error. This generally isn't set,
     * because the overall API response has an error code. But this can be used in
     * the case that we're returning multiple different errors, or communicating
     * errors across non-Connect APIs.
     * </pre>
     *
     * <code>uint32 code = 4 [json_name = "code"];</code>
     * @return This builder for chaining.
     */
    public Builder clearCode() {
      bitField0_ = (bitField0_ & ~0x00000008);
      code_ = 0;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:stately.errors.StatelyErrorDetails)
  }

  // @@protoc_insertion_point(class_scope:stately.errors.StatelyErrorDetails)
  private static final cloud.stately.errors.StatelyErrorDetails DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new cloud.stately.errors.StatelyErrorDetails();
  }

  public static cloud.stately.errors.StatelyErrorDetails getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<StatelyErrorDetails>
      PARSER = new com.google.protobuf.AbstractParser<StatelyErrorDetails>() {
    @java.lang.Override
    public StatelyErrorDetails parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<StatelyErrorDetails> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<StatelyErrorDetails> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public cloud.stately.errors.StatelyErrorDetails getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

